/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.2-pre4, Date: 04-Apr-2013.
 */
#include "TS24011IES.h"
#include "rtsrc/rtPrintToStream.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

int asn1PrtToStrm_TS24011IE_CPUserData (OSCTXT *pctxt, 
   const char* name, const TS24011IE_CPUserData* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamHexStr (pctxt, name, pvalue->numocts, pvalue->data);
   return 0;
}

int asn1PrtToStrm_TS24011IE_RPAddress (OSCTXT *pctxt, 
   const char* name, const TS24011IE_RPAddress* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "length", pvalue->length);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamBoolean (pctxt, "ext", pvalue->ext);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "typeOfNumber", pvalue->typeOfNumber);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "numberingPlanID", pvalue->numberingPlanID);

   asn1PrtToStrm_TS24008IE_TBCDString (pctxt, "number", pvalue->number);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24011IE_RPOriginatorAddress (OSCTXT *pctxt, 
   const char* name, const TS24011IE_RPOriginatorAddress* pvalue)
{
   asn1PrtToStrm_TS24011IE_RPAddress (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24011IE_RPDestinationAddress (OSCTXT *pctxt, 
   const char* name, const TS24011IE_RPDestinationAddress* pvalue)
{
   asn1PrtToStrm_TS24011IE_RPAddress (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24011IE_RPUserData (OSCTXT *pctxt, 
   const char* name, const TS24011IE_RPUserData* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamHexStr (pctxt, name, pvalue->numocts, pvalue->data);
   return 0;
}

int asn1PrtToStrm_TS24011IE_CPCauseValue (OSCTXT *pctxt, 
   const char* name, const TS24011IE_CPCauseValue* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamBoolean (pctxt, "ext", pvalue->ext);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "value", pvalue->value);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24011IE_RPCauseElem (OSCTXT *pctxt, 
   const char* name, const TS24011IE_RPCauseElem* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "length", pvalue->length);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamBoolean (pctxt, "ext", pvalue->ext);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "causeValue", pvalue->causeValue);

   {
   char namebuf[512], numbuf[32];
   OSUINT32 xx1;

   for (xx1 = 0; xx1 < pvalue->diagField.n; xx1++) {
      rtxUIntToCharStr (xx1, numbuf, sizeof(numbuf), 0);
      rtxStrJoin (namebuf, sizeof(namebuf), "diagField", "[", numbuf, "]", 0);
      rtPrintToStreamIndent (pctxt);
      rtPrintToStreamUnsigned (pctxt, namebuf, pvalue->diagField.elem[xx1]);
   }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

