/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.2-pre4, Date: 04-Apr-2013.
 */
#include "TS24011Msgs.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

void asn1Init_TS24011Msg_CPDATA (TS24011Msg_CPDATA* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_TS24011IE_CPUserData (&pvalue->cpUserData);
}

void asn1Init_TS24011Msg_CPERROR (TS24011Msg_CPERROR* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_TS24011IE_CPCauseValue (&pvalue->cpCause);
}

void asn1SetTC_TS24011Msg_CP_PDU_obj_CP_DATA
   (OSCTXT* pctxt, TS24011Msg_CP_PDU* pElem, TS24011Msg_CPDATA *pvalue)
{
   pElem->protoDiscr = TS24007L3_ProtoDiscr_sms;
   pElem->msgType = 1;
   pElem->data.t = T_TS24011Msgs_TS24011_OBJECTSET_obj_CP_DATA;
   pElem->data.u.obj_CP_DATA = pvalue;
}

void asn1SetTC_TS24011Msg_CP_PDU_obj_CP_ACK
   (OSCTXT* pctxt, TS24011Msg_CP_PDU* pElem)
{
   pElem->protoDiscr = TS24007L3_ProtoDiscr_sms;
   pElem->msgType = 4;
   pElem->data.t = T_TS24011Msgs_TS24011_OBJECTSET_obj_CP_ACK;
}

void asn1SetTC_TS24011Msg_CP_PDU_obj_CP_ERROR
   (OSCTXT* pctxt, TS24011Msg_CP_PDU* pElem, TS24011Msg_CPERROR *pvalue)
{
   pElem->protoDiscr = TS24007L3_ProtoDiscr_sms;
   pElem->msgType = 16;
   pElem->data.t = T_TS24011Msgs_TS24011_OBJECTSET_obj_CP_ERROR;
   pElem->data.u.obj_CP_ERROR = pvalue;
}

void asn1Init_TS24011Msg_CP_PDU (TS24011Msg_CP_PDU* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_TS24007L3_L3HdrOptions (&pvalue->l3HdrOpts);
   OSCRTLMEMSET (&pvalue->data, 0, sizeof(pvalue->data));
}

void asn1Init_TS24011Msg_RPHeader (TS24011Msg_RPHeader* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spare = 0;
}

void asn1Init_TS24011Msg_RPDataMSOriginating (
   TS24011Msg_RPDataMSOriginating* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_TS24011IE_RPDestinationAddress (&pvalue->destAddress);
   asn1Init_TS24011IE_RPUserData (&pvalue->userData);
}

void asn1Init_TS24011Msg_RPDataMSTerminated (
   TS24011Msg_RPDataMSTerminated* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_TS24011IE_RPOriginatorAddress (&pvalue->origAddress);
   asn1Init_TS24011IE_RPUserData (&pvalue->userData);
}

void asn1Init_TS24011Msg_RP_ACK (TS24011Msg_RP_ACK* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24011IE_RPUserData (&pvalue->userData);
}

void asn1Init_TS24011Msg_RP_ERROR (TS24011Msg_RP_ERROR* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_TS24011IE_RPCauseElem (&pvalue->rpCause);
   asn1Init_TS24011IE_RPUserData (&pvalue->userData);
}

void asn1Init_TS24011Msg_RP_PDU (TS24011Msg_RP_PDU* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_TS24011Msg_RPHeader (&pvalue->header);
   OSCRTLMEMSET (&pvalue->infoElem.u, 0, sizeof(pvalue->infoElem.u));
}

