/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.2-pre4, Date: 04-Apr-2013.
 */
#include "TS24301IES.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxBitEncode.h"
#include "rtxsrc/rtxIntEncode.h"
#include "rtxsrc/rtx3GPP.h"
#include "rtxsrc/rtxDiagBitTrace.h"

EXTERN int NASEnc_TS24301IE_AuthRespParam (OSCTXT* pctxt
   , TS24301IE_AuthRespParam* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "AuthRespParam");

   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   if (!((pvalue->numocts >= 4 && pvalue->numocts <= 16))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->numocts);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   ret = rtxEncUInt32 (pctxt, pvalue->numocts, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   ret = rtxWriteBytes (pctxt, pvalue->data, pvalue->numocts);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EMMCause (OSCTXT* pctxt, TS24301IE_EMMCause value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EMMCause");

   /* Encode ENUMERATED value */
   switch (value) {
      case TS24301IE_EMMCause_imsiUnkInHSS:
      case TS24301IE_EMMCause_illegalUE:
      case TS24301IE_EMMCause_imeiNotAccept:
      case TS24301IE_EMMCause_illegalME:
      case TS24301IE_EMMCause_epsSvcNotAllowed:
      case TS24301IE_EMMCause_epsAndNonEPSSvcNotAllowed:
      case TS24301IE_EMMCause_ueIdentNotDeriv:
      case TS24301IE_EMMCause_implDetach:
      case TS24301IE_EMMCause_plmnNotAllowed:
      case TS24301IE_EMMCause_trkAreaNotAllowed:
      case TS24301IE_EMMCause_roamNotAllowed:
      case TS24301IE_EMMCause_epsSvcNotAllowInPLMN:
      case TS24301IE_EMMCause_noCellsInTrkArea:
      case TS24301IE_EMMCause_mscTempNotReach:
      case TS24301IE_EMMCause_networkFailure:
      case TS24301IE_EMMCause_csDomainNotAvail:
      case TS24301IE_EMMCause_esmFailure:
      case TS24301IE_EMMCause_macFailure:
      case TS24301IE_EMMCause_synchFailure:
      case TS24301IE_EMMCause_congestion:
      case TS24301IE_EMMCause_ueSecCapMismat:
      case TS24301IE_EMMCause_secModeReject:
      case TS24301IE_EMMCause_notAuthForCSG:
      case TS24301IE_EMMCause_nonEPSAuthUnaccept:
      case TS24301IE_EMMCause_reqSvcOptNotAuth:
      case TS24301IE_EMMCause_csSvcTempUnavail:
      case TS24301IE_EMMCause_noEPSBearerCtxtAct:
      case TS24301IE_EMMCause_severeNetFailure:
      case TS24301IE_EMMCause_semIncorrectMsg:
      case TS24301IE_EMMCause_invMandInfo:
      case TS24301IE_EMMCause_msgTypeNotExist:
      case TS24301IE_EMMCause_msgTypeNotCompat:
      case TS24301IE_EMMCause_infoElemNotExist:
      case TS24301IE_EMMCause_condIEError:
      case TS24301IE_EMMCause_msgNotCompat:
      case TS24301IE_EMMCause_unspecProtoErr:
         break;

      default:
         rtxErrAddUIntParm (pctxt, value);
         return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 8);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_ESMMessageContainer (OSCTXT* pctxt
   , TS24301IE_ESMMessageContainer value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ESMMessageContainer");

   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   if (!(value.numocts <= 65535)) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)value.numocts);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   ret = rtxEncUInt32 (pctxt, value.numocts, 2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   ret = rtxWriteBytes (pctxt, value.data, value.numocts);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_NASMessageContainer (OSCTXT* pctxt
   , TS24301IE_NASMessageContainer* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "NASMessageContainer");

   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   if (!((pvalue->numocts >= 2 && pvalue->numocts <= 251))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->numocts);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   ret = rtxEncUInt32 (pctxt, pvalue->numocts, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   ret = rtxWriteBytes (pctxt, pvalue->data, pvalue->numocts);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_Nonce (OSCTXT* pctxt, TS24301IE_Nonce* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "Nonce");

   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   ret = rtxWriteBytes (pctxt, pvalue->data, 4);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_ServiceType (OSCTXT* pctxt
   , TS24301IE_ServiceType value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ServiceType");

   /* Encode INTEGER value */
   if (!((value <= OSUINTCONST(15)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)value);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, value, 4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_ShortMAC (OSCTXT* pctxt, TS24301IE_ShortMAC* pvalue
   )
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ShortMAC");

   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   ret = rtxWriteBytes (pctxt, pvalue->data, 2);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_TrackingAreaCode (OSCTXT* pctxt
   , TS24301IE_TrackingAreaCode* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "TrackingAreaCode");

   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   ret = rtxWriteBytes (pctxt, pvalue->data, 2);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_SSCode (OSCTXT* pctxt, TS24301IE_SSCode value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "SSCode");

   /* Encode INTEGER value */
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, value, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_LCSIndicator (OSCTXT* pctxt
   , TS24301IE_LCSIndicator value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "LCSIndicator");

   /* Encode INTEGER value */
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, value, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_LCSClientIdentity (OSCTXT* pctxt
   , TS24301IE_LCSClientIdentity* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "LCSClientIdentity");

   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   if (!((pvalue->numocts >= 1 && pvalue->numocts <= 255))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->numocts);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   ret = rtxEncUInt32 (pctxt, pvalue->numocts, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   ret = rtxWriteBytes (pctxt, pvalue->data, pvalue->numocts);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_GenMsgContainerType (OSCTXT* pctxt
   , TS24301IE_GenMsgContainerType value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "GenMsgContainerType");

   /* Encode ENUMERATED value */
   if (value >= 3) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 8);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_GenMessageContainer (OSCTXT* pctxt
   , TS24301IE_GenMessageContainer value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "GenMessageContainer");

   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   if (!(value.numocts <= 65535)) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)value.numocts);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   ret = rtxEncUInt32 (pctxt, value.numocts, 2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   ret = rtxWriteBytes (pctxt, value.data, value.numocts);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_ESMCause (OSCTXT* pctxt, TS24301IE_ESMCause value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ESMCause");

   /* Encode ENUMERATED value */
   switch (value) {
      case TS24301IE_ESMCause_operDeterBarring:
      case TS24301IE_ESMCause_insuffResources:
      case TS24301IE_ESMCause_unkOrMissAPN:
      case TS24301IE_ESMCause_unknownPDNType:
      case TS24301IE_ESMCause_userAutheFailed:
      case TS24301IE_ESMCause_reqRejectByServingGW:
      case TS24301IE_ESMCause_reqRejectUnspecified:
      case TS24301IE_ESMCause_svcOptNotSupp:
      case TS24301IE_ESMCause_reqSvcOptNotSubscr:
      case TS24301IE_ESMCause_svcOptTempOutOfOrder:
      case TS24301IE_ESMCause_ptiAlreadyInUse:
      case TS24301IE_ESMCause_regularDeactivation:
      case TS24301IE_ESMCause_epsQoSNotAccepted:
      case TS24301IE_ESMCause_networkFailure:
      case TS24301IE_ESMCause_reactivateRequest:
      case TS24301IE_ESMCause_semErrorInTFTOp:
      case TS24301IE_ESMCause_synErrorInTFTOp:
      case TS24301IE_ESMCause_invEPSBearerIdent:
      case TS24301IE_ESMCause_semErrorsInPktFilt:
      case TS24301IE_ESMCause_synErrorsInPktFilt:
      case TS24301IE_ESMCause_epsBearerCtxtWoTFTAlrActv:
      case TS24301IE_ESMCause_ptiMismatch:
      case TS24301IE_ESMCause_lastPDNDisconnNotAllow:
      case TS24301IE_ESMCause_pdnTypeIPv4OnlyAllow:
      case TS24301IE_ESMCause_pdnTypeIPv6OnlyAllow:
      case TS24301IE_ESMCause_singleAddrBearersOnlyAllow:
      case TS24301IE_ESMCause_esmInfoNotRcvd:
      case TS24301IE_ESMCause_pdnConnNotExist:
      case TS24301IE_ESMCause_multPDNConnsForAPNNotAllow:
      case TS24301IE_ESMCause_collWithNetwInitReq:
      case TS24301IE_ESMCause_unsuppQCIValue:
      case TS24301IE_ESMCause_bearerHandlingNotSupp:
      case TS24301IE_ESMCause_maxNumEPSBearersReached:
      case TS24301IE_ESMCause_reqAPNNotSupp:
      case TS24301IE_ESMCause_invPTIValue:
      case TS24301IE_ESMCause_semIncorrectMessage:
      case TS24301IE_ESMCause_invMandatoryInfo:
      case TS24301IE_ESMCause_msgTypeNonExistOrNotImpl:
      case TS24301IE_ESMCause_msgTypeNotCompatWithProtoState:
      case TS24301IE_ESMCause_ieNonExistOrNotImpl:
      case TS24301IE_ESMCause_condIEError:
      case TS24301IE_ESMCause_msgNotCompatWithProtoState:
      case TS24301IE_ESMCause_protocolErrorUnspecified:
      case TS24301IE_ESMCause_apnRestrValIncompWithBearerCtxt:
         break;

      default:
         rtxErrAddUIntParm (pctxt, value);
         return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 8);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_LinkedEPSBearerIdent (OSCTXT* pctxt
   , TS24301IE_LinkedEPSBearerIdent value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "LinkedEPSBearerIdent");

   /* Encode INTEGER value */
   if (!((value <= OSUINTCONST(15)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)value);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, value, 4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_PDNTypeValue (OSCTXT* pctxt
   , TS24301IE_PDNTypeValue value)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "PDNTypeValue");

   /* Encode ENUMERATED value */
   if (value >= 4) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_AddnUpdateResult_value (OSCTXT* pctxt
   , TS24301IE_AddnUpdateResult_value value)
{
   int ret = 0;

   /* Encode ENUMERATED value */
   if (value >= 4) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSMobileIdentity_typeOfIdent (OSCTXT* pctxt
   , TS24301IE_EPSMobileIdentity_typeOfIdent value)
{
   int ret = 0;

   /* Encode ENUMERATED value */
   switch (value) {
      case TS24301IE_EPSMobileIdentity_typeOfIdent_imsi:
      case TS24301IE_EPSMobileIdentity_typeOfIdent_imei:
      case TS24301IE_EPSMobileIdentity_typeOfIdent_guti:
         break;

      default:
         rtxErrAddUIntParm (pctxt, value);
         return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_NASSecurityAlgorithms_typeOfCiph (OSCTXT* pctxt
   , TS24301IE_NASSecurityAlgorithms_typeOfCiph value)
{
   int ret = 0;

   /* Encode ENUMERATED value */
   if (value >= 8) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_NASSecurityAlgorithms_typeOfProt (OSCTXT* pctxt
   , TS24301IE_NASSecurityAlgorithms_typeOfProt value)
{
   int ret = 0;

   /* Encode ENUMERATED value */
   if (value >= 8) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_PagingIdentity_ident (OSCTXT* pctxt
   , TS24301IE_PagingIdentity_ident value)
{
   int ret = 0;

   /* Encode ENUMERATED value */
   if (value >= 2) {
      rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   RTDIAG_NEWBITFIELD (pctxt, "ENUMERATED");

   ret = rtxEncBits (pctxt, value, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSBearerContextStatus (OSCTXT* pctxt
   , TS24301IE_EPSBearerContextStatus* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSBearerContextStatus");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi7 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi7");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi7);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi6 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi6");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi6);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi5 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi5");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi4 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi4");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi3 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi3");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi2 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi1 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi1");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi0 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi0");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi0);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi15 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi15");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi15);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi14 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi14");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi14);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi13 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi13");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi13);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi12 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi12");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi12);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi11 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi11");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi11);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi10 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi10");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi10);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi9 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi9");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi9);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ebi8 */

   RTXCTXTPUSHELEMNAME (pctxt, "ebi8");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ebi8);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;
   if (!(pvalue->length == 2)) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->length);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_NASSecParamsFromEUTRA (OSCTXT* pctxt
   , TS24301IE_NASSecParamsFromEUTRA* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "NASSecParamsFromEUTRA");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(15)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode dlNASCount */

   RTXCTXTPUSHELEMNAME (pctxt, "dlNASCount");
   if (!((pvalue->dlNASCount <= OSUINTCONST(15)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->dlNASCount);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->dlNASCount, 4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_NASSecParamsToEUTRA (OSCTXT* pctxt
   , TS24301IE_NASSecParamsToEUTRA* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "NASSecParamsToEUTRA");

   /* encode nonceMMEValue */

   RTXCTXTPUSHELEMNAME (pctxt, "nonceMMEValue");
   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   ret = rtxWriteBytes (pctxt, pvalue->nonceMMEValue, 4);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare1 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare1");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode typeOfCiphAlg */

   RTXCTXTPUSHELEMNAME (pctxt, "typeOfCiphAlg");
   if (!((pvalue->typeOfCiphAlg <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->typeOfCiphAlg);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->typeOfCiphAlg, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare2 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode typeOfProtAlg */

   RTXCTXTPUSHELEMNAME (pctxt, "typeOfProtAlg");
   if (!((pvalue->typeOfProtAlg <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->typeOfProtAlg);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->typeOfProtAlg, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare3 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare3");
   if (!((pvalue->spare3 <= OSUINTCONST(15)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare3);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare3, 4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode tsc */

   RTXCTXTPUSHELEMNAME (pctxt, "tsc");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->tsc);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode nasKeySetIdent */

   RTXCTXTPUSHELEMNAME (pctxt, "nasKeySetIdent");
   if (!((pvalue->nasKeySetIdent <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->nasKeySetIdent);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->nasKeySetIdent, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_AddnUpdateResult (OSCTXT* pctxt
   , TS24301IE_AddnUpdateResult* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "AddnUpdateResult");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(3)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode value */

   RTXCTXTPUSHELEMNAME (pctxt, "value");

   ret = NASEnc_TS24301IE_AddnUpdateResult_value (pctxt, pvalue->value);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_AddnUpdateType (OSCTXT* pctxt
   , TS24301IE_AddnUpdateType* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "AddnUpdateType");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode autv */

   RTXCTXTPUSHELEMNAME (pctxt, "autv");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->autv);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_CSFBResponse (OSCTXT* pctxt
   , TS24301IE_CSFBResponse* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "CSFBResponse");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode value */

   RTXCTXTPUSHELEMNAME (pctxt, "value");
   if (!((pvalue->value <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->value);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->value, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_DetachType (OSCTXT* pctxt
   , TS24301IE_DetachType* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "DetachType");

   /* encode switchOff */

   RTXCTXTPUSHELEMNAME (pctxt, "switchOff");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->switchOff);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode typeOfDetach */

   RTXCTXTPUSHELEMNAME (pctxt, "typeOfDetach");
   if (!((pvalue->typeOfDetach <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->typeOfDetach);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->typeOfDetach, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSAttachResult (OSCTXT* pctxt
   , TS24301IE_EPSAttachResult* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSAttachResult");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode result */

   RTXCTXTPUSHELEMNAME (pctxt, "result");
   if (!((pvalue->result <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->result);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->result, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSAttachType (OSCTXT* pctxt
   , TS24301IE_EPSAttachType* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSAttachType");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode value */

   RTXCTXTPUSHELEMNAME (pctxt, "value");
   if (!((pvalue->value <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->value);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->value, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSMobileIdentity_GUTI (OSCTXT* pctxt
   , TS24301IE_EPSMobileIdentity_GUTI* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSMobileIdentity-GUTI");

   /* encode mcc-mnc */

   RTXCTXTPUSHELEMNAME (pctxt, "mcc-mnc");

   ret = NASEnc_TS24008IE_MCCMNCPair (pctxt, &pvalue->mcc_mnc);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode mmeGroupID */

   RTXCTXTPUSHELEMNAME (pctxt, "mmeGroupID");
   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   ret = rtxWriteBytes (pctxt, pvalue->mmeGroupID, 2);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode mmeCode */

   RTXCTXTPUSHELEMNAME (pctxt, "mmeCode");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->mmeCode, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode tmsi */

   RTXCTXTPUSHELEMNAME (pctxt, "tmsi");
   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   ret = rtxWriteBytes (pctxt, pvalue->tmsi, 4);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSMobileIdentity (OSCTXT* pctxt
   , TS24301IE_EPSMobileIdentity* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSMobileIdentity");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode filler */

   RTXCTXTPUSHELEMNAME (pctxt, "filler");
   if (!((pvalue->filler <= OSUINTCONST(15)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->filler);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->filler, 4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode oddEvenInd */

   RTXCTXTPUSHELEMNAME (pctxt, "oddEvenInd");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->oddEvenInd);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode typeOfIdent */

   RTXCTXTPUSHELEMNAME (pctxt, "typeOfIdent");

   ret = NASEnc_TS24301IE_EPSMobileIdentity_typeOfIdent (pctxt, pvalue->
      typeOfIdent);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode content */

   RTXCTXTPUSHELEMNAME (pctxt, "content");
   /* Encode choice data value */

   switch (pvalue->typeOfIdent)
   {
      /* guti */
      case 6:
         RTXCTXTPUSHELEMNAME (pctxt, "guti");

         ret = NASEnc_TS24301IE_EPSMobileIdentity_GUTI (pctxt, &pvalue->content
            .u.guti);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPELEMNAME (pctxt);
         break;

      /* imsi */
      case 1:
         RTXCTXTPUSHELEMNAME (pctxt, "imsi");

         ret = NASEnc_TS24008IE_IMSI (pctxt, pvalue->content.u.imsi);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPELEMNAME (pctxt);
         break;

      /* imei */
      case 3:
         RTXCTXTPUSHELEMNAME (pctxt, "imei");

         ret = NASEnc_TS24008IE_IMEI (pctxt, pvalue->content.u.imei);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPELEMNAME (pctxt);
         break;

      default:
         return LOG_RTERR (pctxt, RTERR_INVOPT);
   }
   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSNetworkFeatureSupport (OSCTXT* pctxt
   , TS24301IE_EPSNetworkFeatureSupport* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSNetworkFeatureSupport");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(3)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode esr */

   RTXCTXTPUSHELEMNAME (pctxt, "esr");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->esr);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode csLCS */

   RTXCTXTPUSHELEMNAME (pctxt, "csLCS");
   if (!((pvalue->csLCS <= OSUINTCONST(3)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->csLCS);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->csLCS, 2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode epcLCS */

   RTXCTXTPUSHELEMNAME (pctxt, "epcLCS");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->epcLCS);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode emcBS */

   RTXCTXTPUSHELEMNAME (pctxt, "emcBS");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->emcBS);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode imsVoPS */

   RTXCTXTPUSHELEMNAME (pctxt, "imsVoPS");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->imsVoPS);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;
   if (!(pvalue->length == 1)) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->length);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSUpdateResult (OSCTXT* pctxt
   , TS24301IE_EPSUpdateResult* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSUpdateResult");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode result */

   RTXCTXTPUSHELEMNAME (pctxt, "result");
   if (!((pvalue->result <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->result);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->result, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSUpdateType (OSCTXT* pctxt
   , TS24301IE_EPSUpdateType* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSUpdateType");

   /* encode active */

   RTXCTXTPUSHELEMNAME (pctxt, "active");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->active);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode value */

   RTXCTXTPUSHELEMNAME (pctxt, "value");
   if (!((pvalue->value <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->value);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->value, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_KSIAndSequenceNumber (OSCTXT* pctxt
   , TS24301IE_KSIAndSequenceNumber* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "KSIAndSequenceNumber");

   /* encode ksi */

   RTXCTXTPUSHELEMNAME (pctxt, "ksi");
   if (!((pvalue->ksi <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->ksi);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->ksi, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode seqNo */

   RTXCTXTPUSHELEMNAME (pctxt, "seqNo");
   if (!((pvalue->seqNo <= OSUINTCONST(31)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->seqNo);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->seqNo, 5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_NASKeySetIdentifier (OSCTXT* pctxt
   , TS24301IE_NASKeySetIdentifier* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "NASKeySetIdentifier");

   /* encode tsc */

   RTXCTXTPUSHELEMNAME (pctxt, "tsc");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->tsc);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ident */

   RTXCTXTPUSHELEMNAME (pctxt, "ident");
   if (!((pvalue->ident <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->ident);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->ident, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_NASSecurityAlgorithms (OSCTXT* pctxt
   , TS24301IE_NASSecurityAlgorithms* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "NASSecurityAlgorithms");

   /* encode spare1 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare1");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode typeOfCiph */

   RTXCTXTPUSHELEMNAME (pctxt, "typeOfCiph");

   ret = NASEnc_TS24301IE_NASSecurityAlgorithms_typeOfCiph (pctxt, pvalue->
      typeOfCiph);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare2 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode typeOfProt */

   RTXCTXTPUSHELEMNAME (pctxt, "typeOfProt");

   ret = NASEnc_TS24301IE_NASSecurityAlgorithms_typeOfProt (pctxt, pvalue->
      typeOfProt);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_PagingIdentity (OSCTXT* pctxt
   , TS24301IE_PagingIdentity* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "PagingIdentity");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(127)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 7);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ident */

   RTXCTXTPUSHELEMNAME (pctxt, "ident");

   ret = NASEnc_TS24301IE_PagingIdentity_ident (pctxt, pvalue->ident);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_TrackingAreaIdent (OSCTXT* pctxt
   , TS24301IE_TrackingAreaIdent* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "TrackingAreaIdent");

   /* encode mcc-mnc */

   RTXCTXTPUSHELEMNAME (pctxt, "mcc-mnc");

   ret = NASEnc_TS24008IE_MCCMNCPair (pctxt, &pvalue->mcc_mnc);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode tac */

   RTXCTXTPUSHELEMNAME (pctxt, "tac");

   ret = NASEnc_TS24301IE_TrackingAreaCode (pctxt, &pvalue->tac);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_PartialTrkAreaIdent0 (OSCTXT* pctxt
   , TS24301IE_PartialTrkAreaIdent0* pvalue, OSUINT8 numElements)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "PartialTrkAreaIdent0");

   /* encode mcc-mnc */

   RTXCTXTPUSHELEMNAME (pctxt, "mcc-mnc");

   ret = NASEnc_TS24008IE_MCCMNCPair (pctxt, &pvalue->mcc_mnc);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode tacs */

   RTXCTXTPUSHELEMNAME (pctxt, "tacs");
   pvalue->tacs.n = numElements+1;
   {
      OSUINT8 i;
      if (!((pvalue->tacs.n >= 1 && pvalue->tacs.n <= 16))) {
         rtxErrAddElemNameParm (pctxt);
         rtxErrAddIntParm (pctxt, (int)pvalue->tacs.n);
         return LOG_RTERR (pctxt, RTERR_CONSVIO);
      }

      for (i = 0; i < pvalue->tacs.n; i++) {
         RTXCTXTPUSHARRAYELEMNAME (pctxt, "elem", i);

         ret = NASEnc_TS24301IE_TrackingAreaCode (pctxt, &pvalue->tacs.elem[i]
            );
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPARRAYELEMNAME (pctxt);
      }
   }

   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_PartialTrkAreaIdent1 (OSCTXT* pctxt
   , TS24301IE_PartialTrkAreaIdent1* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "PartialTrkAreaIdent1");

   /* encode mcc-mnc */

   RTXCTXTPUSHELEMNAME (pctxt, "mcc-mnc");

   ret = NASEnc_TS24008IE_MCCMNCPair (pctxt, &pvalue->mcc_mnc);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode tac */

   RTXCTXTPUSHELEMNAME (pctxt, "tac");

   ret = NASEnc_TS24301IE_TrackingAreaCode (pctxt, &pvalue->tac);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_PartialTrkAreaIdent2 (OSCTXT* pctxt
   , TS24301IE_PartialTrkAreaIdent2* pvalue, OSUINT8 numElements)
{
   OSUINT8 i;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "PartialTrkAreaIdent2");

   pvalue->n = numElements+1;
   if (!((pvalue->n >= 1 && pvalue->n <= 16))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->n);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   for (i = 0; i < pvalue->n; i++) {
      RTXCTXTPUSHARRAYELEMNAME (pctxt, "elem", i);

      ret = NASEnc_TS24301IE_TrackingAreaIdent (pctxt, &pvalue->elem[i]);
      if (ret < 0) return LOG_RTERR (pctxt, ret);

      RTXCTXTPOPARRAYELEMNAME (pctxt);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_TrackingAreaIdentListItem (OSCTXT* pctxt
   , TS24301IE_TrackingAreaIdentListItem* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "TrackingAreaIdentListItem");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode typeOfList */

   RTXCTXTPUSHELEMNAME (pctxt, "typeOfList");
   if (!((pvalue->typeOfList <= OSUINTCONST(2)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->typeOfList);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->typeOfList, 2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode numElements */

   RTXCTXTPUSHELEMNAME (pctxt, "numElements");
   if (!((pvalue->numElements <= OSUINTCONST(31)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->numElements);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->numElements, 5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode elements */

   RTXCTXTPUSHELEMNAME (pctxt, "elements");
   /* Encode choice data value */

   switch (pvalue->typeOfList)
   {
      /* partTrkIdentList0 */
      case 0:
         RTXCTXTPUSHELEMNAME (pctxt, "partTrkIdentList0");

         ret = NASEnc_TS24301IE_PartialTrkAreaIdent0 (pctxt, &pvalue->elements.
            u.partTrkIdentList0, pvalue->numElements);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPELEMNAME (pctxt);
         break;

      /* partTrkIdentList1 */
      case 1:
         RTXCTXTPUSHELEMNAME (pctxt, "partTrkIdentList1");

         ret = NASEnc_TS24301IE_PartialTrkAreaIdent1 (pctxt, &pvalue->elements.
            u.partTrkIdentList1);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPELEMNAME (pctxt);
         break;

      /* partTrkIdentList2 */
      case 2:
         RTXCTXTPUSHELEMNAME (pctxt, "partTrkIdentList2");

         ret = NASEnc_TS24301IE_PartialTrkAreaIdent2 (pctxt, &pvalue->elements.
            u.partTrkIdentList2, pvalue->numElements);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPELEMNAME (pctxt);
         break;

      default:
         return LOG_RTERR (pctxt, RTERR_INVOPT);
   }
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_TrackingAreaIdentList (OSCTXT* pctxt
   , TS24301IE_TrackingAreaIdentList* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "TrackingAreaIdentList");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode idents */

   RTXCTXTPUSHELEMNAME (pctxt, "idents");
   {
      OSUINT8 i;
      if (!((pvalue->idents.n >= 1 && pvalue->idents.n <= 16))) {
         rtxErrAddElemNameParm (pctxt);
         rtxErrAddIntParm (pctxt, (int)pvalue->idents.n);
         return LOG_RTERR (pctxt, RTERR_CONSVIO);
      }

      for (i = 0; i < pvalue->idents.n; i++) {
         RTXCTXTPUSHARRAYELEMNAME (pctxt, "elem", i);

         ret = NASEnc_TS24301IE_TrackingAreaIdentListItem (pctxt, &pvalue->
            idents.elem[i]);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPARRAYELEMNAME (pctxt);
      }
   }

   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;
   if (!((pvalue->length >= OSUINTCONST(6) && pvalue->length <= OSUINTCONST(96)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->length);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSEncryptAlgsSupported (OSCTXT* pctxt
   , TS24301IE_EPSEncryptAlgsSupported* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSEncryptAlgsSupported");

   /* encode eea0 */

   RTXCTXTPUSHELEMNAME (pctxt, "eea0");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eea0);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode x128-eea1 */

   RTXCTXTPUSHELEMNAME (pctxt, "x128-eea1");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->x128_eea1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode x128-eea2 */

   RTXCTXTPUSHELEMNAME (pctxt, "x128-eea2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->x128_eea2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eea3 */

   RTXCTXTPUSHELEMNAME (pctxt, "eea3");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eea3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eea4 */

   RTXCTXTPUSHELEMNAME (pctxt, "eea4");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eea4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eea5 */

   RTXCTXTPUSHELEMNAME (pctxt, "eea5");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eea5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eea6 */

   RTXCTXTPUSHELEMNAME (pctxt, "eea6");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eea6);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eea7 */

   RTXCTXTPUSHELEMNAME (pctxt, "eea7");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eea7);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSIntegAlgsSupported (OSCTXT* pctxt
   , TS24301IE_EPSIntegAlgsSupported* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSIntegAlgsSupported");

   /* encode eia0 */

   RTXCTXTPUSHELEMNAME (pctxt, "eia0");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eia0);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eia1 */

   RTXCTXTPUSHELEMNAME (pctxt, "eia1");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eia1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eia2 */

   RTXCTXTPUSHELEMNAME (pctxt, "eia2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eia2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eia3 */

   RTXCTXTPUSHELEMNAME (pctxt, "eia3");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eia3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eia4 */

   RTXCTXTPUSHELEMNAME (pctxt, "eia4");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eia4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eia5 */

   RTXCTXTPUSHELEMNAME (pctxt, "eia5");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eia5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eia6 */

   RTXCTXTPUSHELEMNAME (pctxt, "eia6");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eia6);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eia7 */

   RTXCTXTPUSHELEMNAME (pctxt, "eia7");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eia7);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_UMTSEncryptAlgsSupported (OSCTXT* pctxt
   , TS24301IE_UMTSEncryptAlgsSupported* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "UMTSEncryptAlgsSupported");

   /* encode uea0 */

   RTXCTXTPUSHELEMNAME (pctxt, "uea0");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uea0);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uea1 */

   RTXCTXTPUSHELEMNAME (pctxt, "uea1");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uea1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uea2 */

   RTXCTXTPUSHELEMNAME (pctxt, "uea2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uea2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uea3 */

   RTXCTXTPUSHELEMNAME (pctxt, "uea3");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uea3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uea4 */

   RTXCTXTPUSHELEMNAME (pctxt, "uea4");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uea4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uea5 */

   RTXCTXTPUSHELEMNAME (pctxt, "uea5");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uea5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uea6 */

   RTXCTXTPUSHELEMNAME (pctxt, "uea6");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uea6);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uea7 */

   RTXCTXTPUSHELEMNAME (pctxt, "uea7");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uea7);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_UMTSIntegAlgsSupported (OSCTXT* pctxt
   , TS24301IE_UMTSIntegAlgsSupported* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "UMTSIntegAlgsSupported");

   /* encode uia1 */

   RTXCTXTPUSHELEMNAME (pctxt, "uia1");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uia1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uia2 */

   RTXCTXTPUSHELEMNAME (pctxt, "uia2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uia2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uia3 */

   RTXCTXTPUSHELEMNAME (pctxt, "uia3");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uia3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uia4 */

   RTXCTXTPUSHELEMNAME (pctxt, "uia4");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uia4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uia5 */

   RTXCTXTPUSHELEMNAME (pctxt, "uia5");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uia5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uia6 */

   RTXCTXTPUSHELEMNAME (pctxt, "uia6");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uia6);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode uia7 */

   RTXCTXTPUSHELEMNAME (pctxt, "uia7");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->uia7);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_UENetworkCapability (OSCTXT* pctxt
   , TS24301IE_UENetworkCapability* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "UENetworkCapability");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode epsEncryptAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "epsEncryptAlgs");

   ret = NASEnc_TS24301IE_EPSEncryptAlgsSupported (pctxt, &pvalue->
      epsEncryptAlgs);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode epsIntegAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "epsIntegAlgs");

   ret = NASEnc_TS24301IE_EPSIntegAlgsSupported (pctxt, &pvalue->epsIntegAlgs
      );
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode umtsEncryptAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "umtsEncryptAlgs");

   ret = NASEnc_TS24301IE_UMTSEncryptAlgsSupported (pctxt, &pvalue->
      umtsEncryptAlgs);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ucs2 */

   RTXCTXTPUSHELEMNAME (pctxt, "ucs2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->ucs2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode umtsIntegAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "umtsIntegAlgs");

   ret = NASEnc_TS24301IE_UMTSIntegAlgsSupported (pctxt, &pvalue->umtsIntegAlgs
      );
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare2 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare2");
   if (!((pvalue->spare2 <= OSUINTCONST(3)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare2);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare2, 2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode h245-ash */

   RTXCTXTPUSHELEMNAME (pctxt, "h245-ash");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->h245_ash);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode acc-csfb */

   RTXCTXTPUSHELEMNAME (pctxt, "acc-csfb");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->acc_csfb);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode lpp */

   RTXCTXTPUSHELEMNAME (pctxt, "lpp");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->lpp);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode lcs */

   RTXCTXTPUSHELEMNAME (pctxt, "lcs");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->lcs);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode x1xSR-VCC */

   RTXCTXTPUSHELEMNAME (pctxt, "x1xSR-VCC");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->x1xSR_VCC);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode nf */

   RTXCTXTPUSHELEMNAME (pctxt, "nf");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->nf);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare4 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare4");
   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   if (!(pvalue->spare4.numocts <= 7)) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare4.numocts);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   ret = rtxWriteBytes (pctxt, pvalue->spare4.data, pvalue->spare4.numocts);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;
   if (!((pvalue->length >= OSUINTCONST(2) && pvalue->length <= OSUINTCONST(13)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->length);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_GPRSIntegAlgsSupported (OSCTXT* pctxt
   , TS24301IE_GPRSIntegAlgsSupported* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "GPRSIntegAlgsSupported");

   /* encode gea1 */

   RTXCTXTPUSHELEMNAME (pctxt, "gea1");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->gea1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode gea2 */

   RTXCTXTPUSHELEMNAME (pctxt, "gea2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->gea2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode gea3 */

   RTXCTXTPUSHELEMNAME (pctxt, "gea3");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->gea3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode gea4 */

   RTXCTXTPUSHELEMNAME (pctxt, "gea4");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->gea4);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode gea5 */

   RTXCTXTPUSHELEMNAME (pctxt, "gea5");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->gea5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode gea6 */

   RTXCTXTPUSHELEMNAME (pctxt, "gea6");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->gea6);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode gea7 */

   RTXCTXTPUSHELEMNAME (pctxt, "gea7");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->gea7);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_UERadioCapInfoUpdateNeeded (OSCTXT* pctxt
   , TS24301IE_UERadioCapInfoUpdateNeeded* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "UERadioCapInfoUpdateNeeded");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode value */

   RTXCTXTPUSHELEMNAME (pctxt, "value");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->value);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_UESecurityCapability (OSCTXT* pctxt
   , TS24301IE_UESecurityCapability* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "UESecurityCapability");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode epsEncryptAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "epsEncryptAlgs");

   ret = NASEnc_TS24301IE_EPSEncryptAlgsSupported (pctxt, &pvalue->
      epsEncryptAlgs);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode epsIntegAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "epsIntegAlgs");

   ret = NASEnc_TS24301IE_EPSIntegAlgsSupported (pctxt, &pvalue->epsIntegAlgs
      );
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode umtsEncryptAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "umtsEncryptAlgs");

   ret = NASEnc_TS24301IE_UMTSEncryptAlgsSupported (pctxt, &pvalue->
      umtsEncryptAlgs);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare2 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare2");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare2);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode umtsIntegAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "umtsIntegAlgs");

   ret = NASEnc_TS24301IE_UMTSIntegAlgsSupported (pctxt, &pvalue->umtsIntegAlgs
      );
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare3 */

   RTXCTXTPUSHELEMNAME (pctxt, "spare3");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode gprsIntegAlgs */

   RTXCTXTPUSHELEMNAME (pctxt, "gprsIntegAlgs");

   ret = NASEnc_TS24301IE_GPRSIntegAlgsSupported (pctxt, &pvalue->gprsIntegAlgs
      );
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;
   if (!((pvalue->length >= OSUINTCONST(2) && pvalue->length <= OSUINTCONST(13)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->length);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_CLI (OSCTXT* pctxt, TS24301IE_CLI* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "CLI");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode value */

   RTXCTXTPUSHELEMNAME (pctxt, "value");

   ret = NASEnc_TS24008IE_TBCDString (pctxt, pvalue->value);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_GUTIType (OSCTXT* pctxt, TS24301IE_GUTIType* pvalue
   )
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "GUTIType");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode mapped */

   RTXCTXTPUSHELEMNAME (pctxt, "mapped");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->mapped);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_APNAggMaxBitRateExt (OSCTXT* pctxt
   , TS24301IE_APNAggMaxBitRateExt* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "APNAggMaxBitRateExt");

   /* encode apnAmbrforDL */

   RTXCTXTPUSHELEMNAME (pctxt, "apnAmbrforDL");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->apnAmbrforDL, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode apnAmbrforUL */

   RTXCTXTPUSHELEMNAME (pctxt, "apnAmbrforUL");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->apnAmbrforUL, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_APNAggMaxBitRate (OSCTXT* pctxt
   , TS24301IE_APNAggMaxBitRate* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "APNAggMaxBitRate");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode apnAmbrforDL */

   RTXCTXTPUSHELEMNAME (pctxt, "apnAmbrforDL");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->apnAmbrforDL, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode apnAmbrforUL */

   RTXCTXTPUSHELEMNAME (pctxt, "apnAmbrforUL");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->apnAmbrforUL, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode ext */

   RTXCTXTPUSHELEMNAME (pctxt, "ext");
   {
      OSUINT8 i;
      if (!(pvalue->ext.n <= 2)) {
         rtxErrAddElemNameParm (pctxt);
         rtxErrAddIntParm (pctxt, (int)pvalue->ext.n);
         return LOG_RTERR (pctxt, RTERR_CONSVIO);
      }

      for (i = 0; i < pvalue->ext.n; i++) {
         RTXCTXTPUSHARRAYELEMNAME (pctxt, "elem", i);

         ret = NASEnc_TS24301IE_APNAggMaxBitRateExt (pctxt, &pvalue->ext.
            elem[i]);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPARRAYELEMNAME (pctxt);
      }
   }

   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;
   if (!((pvalue->length >= OSUINTCONST(2) && pvalue->length <= OSUINTCONST(6)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->length);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSQoSBitRates (OSCTXT* pctxt
   , TS24301IE_EPSQoSBitRates* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSQoSBitRates");

   /* encode maxBitRateforUL */

   RTXCTXTPUSHELEMNAME (pctxt, "maxBitRateforUL");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->maxBitRateforUL, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode maxBitRateforDL */

   RTXCTXTPUSHELEMNAME (pctxt, "maxBitRateforDL");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->maxBitRateforDL, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode guarBitRateforUL */

   RTXCTXTPUSHELEMNAME (pctxt, "guarBitRateforUL");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->guarBitRateforUL, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode guarBitRateforDL */

   RTXCTXTPUSHELEMNAME (pctxt, "guarBitRateforDL");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->guarBitRateforDL, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_EPSQualityOfService (OSCTXT* pctxt
   , TS24301IE_EPSQualityOfService* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "EPSQualityOfService");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode qci */

   RTXCTXTPUSHELEMNAME (pctxt, "qci");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, pvalue->qci, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode bitRates */

   RTXCTXTPUSHELEMNAME (pctxt, "bitRates");
   {
      OSUINT8 i;
      if (!(pvalue->bitRates.n <= 3)) {
         rtxErrAddElemNameParm (pctxt);
         rtxErrAddIntParm (pctxt, (int)pvalue->bitRates.n);
         return LOG_RTERR (pctxt, RTERR_CONSVIO);
      }

      for (i = 0; i < pvalue->bitRates.n; i++) {
         RTXCTXTPUSHARRAYELEMNAME (pctxt, "elem", i);

         ret = NASEnc_TS24301IE_EPSQoSBitRates (pctxt, &pvalue->bitRates.
            elem[i]);
         if (ret < 0) return LOG_RTERR (pctxt, ret);

         RTXCTXTPOPARRAYELEMNAME (pctxt);
      }
   }

   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;
   if (!((pvalue->length == 1 || pvalue->length == 5 || pvalue->length == 9))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->length);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_ESMInfoXferFlag (OSCTXT* pctxt
   , TS24301IE_ESMInfoXferFlag* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "ESMInfoXferFlag");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(7)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 3);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode eitValue */

   RTXCTXTPUSHELEMNAME (pctxt, "eitValue");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->eitValue);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_PDNAddress (OSCTXT* pctxt
   , TS24301IE_PDNAddress* pvalue)
{
   OSSIZE startIndex;
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "PDNAddress");

   /* encode length */

   RTXCTXTPUSHELEMNAME (pctxt, "length");
   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncUInt32 (pctxt, 0, 1);
   if (ret < 0) return LOG_RTERR (pctxt, ret);
   startIndex = pctxt->buffer.byteIndex;

   RTDIAG_SETBITFLDCOUNT (pctxt);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   if (!((pvalue->spare <= OSUINTCONST(31)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->spare);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTDIAG_NEWBITFIELD (pctxt, "INTEGER");

   ret = rtxEncBits (pctxt, pvalue->spare, 5);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode pdnTypeValue */

   RTXCTXTPUSHELEMNAME (pctxt, "pdnTypeValue");

   ret = NASEnc_TS24301IE_PDNTypeValue (pctxt, pvalue->pdnTypeValue);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   /* encode pdnAddrInfo */

   RTXCTXTPUSHELEMNAME (pctxt, "pdnAddrInfo");
   RTDIAG_NEWBITFIELD (pctxt, "OCTET STRING");

   if (!((pvalue->pdnAddrInfo.numocts >= 4 && pvalue->pdnAddrInfo.numocts <= 12))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->pdnAddrInfo.numocts);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   ret = rtxWriteBytes (pctxt, pvalue->pdnAddrInfo.data, pvalue->pdnAddrInfo.numocts);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   rtxByteAlign (pctxt);
   pvalue->length = pctxt->buffer.byteIndex - startIndex;
   pctxt->buffer.data[startIndex-1] = (OSUINT8) pvalue->length;
   if (!((pvalue->length >= OSUINTCONST(5) && pvalue->length <= OSUINTCONST(13)))) {
      rtxErrAddElemNameParm (pctxt);
      rtxErrAddIntParm (pctxt, (int)pvalue->length);
      return LOG_RTERR (pctxt, RTERR_CONSVIO);
   }

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

EXTERN int NASEnc_TS24301IE_PDNType (OSCTXT* pctxt, TS24301IE_PDNType* pvalue)
{
   int ret = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "PDNType");

   /* encode spare */

   RTXCTXTPUSHELEMNAME (pctxt, "spare");
   RTDIAG_NEWBITFIELD (pctxt, "BOOLEAN");

   ret = rtxEncBit (pctxt, pvalue->spare);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTDIAG_SETBITFLDCOUNT (pctxt);
   RTXCTXTPOPELEMNAME (pctxt);

   /* encode pdnTypeValue */

   RTXCTXTPUSHELEMNAME (pctxt, "pdnTypeValue");

   ret = NASEnc_TS24301IE_PDNTypeValue (pctxt, pvalue->pdnTypeValue);
   if (ret < 0) return LOG_RTERR (pctxt, ret);

   RTXCTXTPOPELEMNAME (pctxt);

   RTXCTXTPOPTYPENAME (pctxt);

   return (ret);
}

