/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.2-pre4, Date: 04-Apr-2013.
 */
#include "TS24011IES.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

void asn1Init_TS24011IE_CPUserData (TS24011IE_CPUserData* pvalue)
{
   if (0 == pvalue) return;
   pvalue->numocts = 0;
}

void asn1Init_TS24011IE_RPAddress (TS24011IE_RPAddress* pvalue)
{
   if (0 == pvalue) return;
   pvalue->ext = TRUE;
   pvalue->number = 0;
}

void asn1Init_TS24011IE_RPOriginatorAddress (
   TS24011IE_RPOriginatorAddress* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_TS24011IE_RPAddress (pvalue);
}

void asn1Init_TS24011IE_RPDestinationAddress (
   TS24011IE_RPDestinationAddress* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_TS24011IE_RPAddress (pvalue);
}

void asn1Init_TS24011IE_RPUserData (TS24011IE_RPUserData* pvalue)
{
   if (0 == pvalue) return;
   pvalue->numocts = 0;
}

void asn1Init_TS24011IE_CPCauseValue (TS24011IE_CPCauseValue* pvalue)
{
   if (0 == pvalue) return;
   pvalue->ext = FALSE;
}

void asn1Init_TS24011IE_RPCauseElem (TS24011IE_RPCauseElem* pvalue)
{
   if (0 == pvalue) return;
   pvalue->length = 1;
   pvalue->ext = FALSE;
   pvalue->diagField.n = 0;
}

