/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.2-pre4, Date: 04-Apr-2013.
 */
#include "TS24008Msgs.h"
#include "rtsrc/rtPrintToStream.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

int asn1PrtToStrm_TS24008Msg_StartDTMF (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_StartDTMF* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.keypadFacilityPresent) {
      asn1PrtToStrm_TS24008IE_KeypadFacilityInfo (pctxt, "keypadFacility", &pvalue->keypadFacility);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_StartDTMFAck (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_StartDTMFAck* pvalue)
{
   asn1PrtToStrm_TS24008Msg_StartDTMF (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtReject (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivatePDPCtxtReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_SMCauseValue (pctxt, "smCause", &pvalue->smCause);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3396ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3396Value", &pvalue->t3396Value);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivateSecondaryPDPCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivateSecondaryPDPCtxtRej* pvalue)
{
   asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtReject (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RequestPDPCtxtActRej (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RequestPDPCtxtActRej* pvalue)
{
   asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtReject (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ModifyPDPCtxtRej* pvalue)
{
   asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtReject (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RqstSecondaryPDPCtxtActRej (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RqstSecondaryPDPCtxtActRej* pvalue)
{
   asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtReject (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivateMBMSCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivateMBMSCtxtRej* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_SMCauseValue (pctxt, "smCause", &pvalue->smCause);

   if (pvalue->m.mbmsPCOPresent) {
      asn1PrtToStrm_TS24008IE_MBMS_PCO (pctxt, "mbmsPCO", &pvalue->mbmsPCO);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3396ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3396Value", &pvalue->t3396Value);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RequestMBMSCtxtActRej (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RequestMBMSCtxtActRej* pvalue)
{
   asn1PrtToStrm_TS24008Msg_ActivateMBMSCtxtRej (pctxt, name, pvalue);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AuthenticationRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AuthenticationRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "ciphKeySeqNum", &pvalue->ciphKeySeqNum);

   asn1PrtToStrm_TS24008IE_AuthParamRAND (pctxt, "authParamRAND", &pvalue->authParamRAND);

   if (pvalue->m.authParamAUTNPresent) {
      asn1PrtToStrm_TS24008IE_AuthParamAUTN (pctxt, "authParamAUTN", &pvalue->authParamAUTN);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AuthenticationResponse (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AuthenticationResponse* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_AuthRespParam (pctxt, "respParam", &pvalue->respParam);

   if (pvalue->m.respParamExtPresent) {
      asn1PrtToStrm_TS24008IE_AuthRespParamExt (pctxt, "respParamExt", &pvalue->respParamExt);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AuthenticationFailure (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AuthenticationFailure* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_RejectCauseValue (pctxt, "rejectCause", &pvalue->rejectCause);

   if (pvalue->m.failParamPresent) {
      asn1PrtToStrm_TS24008IE_AuthFailureParam (pctxt, "failParam", &pvalue->failParam);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_CMReestabRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_CMReestabRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "ciphKeySeqNum", &pvalue->ciphKeySeqNum);

   asn1PrtToStrm_TS24008IE_MobileStationClassmark2 (pctxt, "mobileStationClassmark2", &pvalue->mobileStationClassmark2);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

   if (pvalue->m.locAreaIdentPresent) {
      asn1PrtToStrm_TS24008IE_LocAreaIdent (pctxt, "locAreaIdent", &pvalue->locAreaIdent);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_CMServicePrompt (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_CMServicePrompt* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_PDAndSAPI (pctxt, "pdAndSAPI", &pvalue->pdAndSAPI);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_CMServiceReject (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_CMServiceReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_RejectCauseValue (pctxt, "rejectCause", &pvalue->rejectCause);

   if (pvalue->m._v10ExtPresent) {
      asn1PrtToStrm_TS24008IE_MMTimer (pctxt, "t3246Value", &pvalue->t3246Value);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Abort (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Abort* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_RejectCauseValue (pctxt, "rejectCause", &pvalue->rejectCause);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_CMServiceRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_CMServiceRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "ciphKeySeqNum", &pvalue->ciphKeySeqNum);

   asn1PrtToStrm_TS24008IE_CMServiceType (pctxt, "cmServiceType", &pvalue->cmServiceType);

   asn1PrtToStrm_TS24008IE_MobileStationClassmark2 (pctxt, "mobileStationClassmark2", &pvalue->mobileStationClassmark2);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

   if (pvalue->m.priorityLevelPresent) {
      asn1PrtToStrm_TS24008IE_PriorityLevel (pctxt, "priorityLevel", &pvalue->priorityLevel);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.addnUpdateParamsPresent) {
         asn1PrtToStrm_TS24008IE_AddnUpdateParams (pctxt, "addnUpdateParams", &pvalue->addnUpdateParams);
      }
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_IdentityRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_IdentityRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_IdentityTypeValue (pctxt, "value", &pvalue->value);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_IdentityResponse (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_IdentityResponse* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.p_TMSI_TypePresent) {
         asn1PrtToStrm_TS24008IE_P_TMSI_Type (pctxt, "p_TMSI_Type", &pvalue->p_TMSI_Type);
      }
      if (pvalue->m.routingAreaIdPresent) {
         asn1PrtToStrm_TS24008IE_RoutingAreaIdent2 (pctxt, "routingAreaId", &pvalue->routingAreaId);
      }
      if (pvalue->m.pTMSISignaturePresent) {
         asn1PrtToStrm_TS24008IE_P_TMSISignature2 (pctxt, "pTMSISignature", &pvalue->pTMSISignature);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_IMSIDetachInd (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_IMSIDetachInd* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_MobileStationClassmark1 (pctxt, "mobileStationClassmark1", &pvalue->mobileStationClassmark1);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_LocUpdatingAccept (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_LocUpdatingAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_LocAreaIdent (pctxt, "locAreaIdent", &pvalue->locAreaIdent);

   if (pvalue->m.mobileIdentityPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);
   }

   if (pvalue->m.followOnProceedPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "followOnProceed");
   }

   if (pvalue->m.ctsPermissionPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "ctsPermission");
   }

   if (pvalue->m.equivPLMNsPresent) {
      asn1PrtToStrm_TS24008IE_PLMNList (pctxt, "equivPLMNs", &pvalue->equivPLMNs);
   }

   if (pvalue->m.emergNumListPresent) {
      asn1PrtToStrm_TS24008IE_EmergencyNumberList (pctxt, "emergNumList", &pvalue->emergNumList);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.per_MS_T3212Present) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "per_MS_T3212", &pvalue->per_MS_T3212);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_LocUpdatingReject (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_LocUpdatingReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_RejectCauseValue (pctxt, "rejectCause", &pvalue->rejectCause);

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3246ValuePresent) {
         asn1PrtToStrm_TS24008IE_MMTimer (pctxt, "t3246Value", &pvalue->t3246Value);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_LocUpdatingRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_LocUpdatingRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "ciphKeySeqNum", &pvalue->ciphKeySeqNum);

   asn1PrtToStrm_TS24008IE_LocationUpdatingType (pctxt, "locUpdatingType", &pvalue->locUpdatingType);

   asn1PrtToStrm_TS24008IE_LocAreaIdent (pctxt, "locAreaIdent", &pvalue->locAreaIdent);

   asn1PrtToStrm_TS24008IE_MobileStationClassmark1 (pctxt, "mobileStationClassmark1", &pvalue->mobileStationClassmark1);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

   if (pvalue->m.mobStatCmark4UMTSPresent) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark2 (pctxt, "mobStatCmark4UMTS", &pvalue->mobStatCmark4UMTS);
   }

   if (pvalue->m._v9ExtPresent) {
      if (pvalue->m.addnUpdateParamsPresent) {
         asn1PrtToStrm_TS24008IE_AddnUpdateParams (pctxt, "addnUpdateParams", &pvalue->addnUpdateParams);
      }
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
      if (pvalue->m.msNetFeatureSupportPresent) {
         asn1PrtToStrm_TS24008IE_MSNetFeatureSupport (pctxt, "msNetFeatureSupport", &pvalue->msNetFeatureSupport);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_MMInformation (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_MMInformation* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.networkFullNamePresent) {
      asn1PrtToStrm_TS24008IE_NetworkName (pctxt, "networkFullName", &pvalue->networkFullName);
   }

   if (pvalue->m.networkShortNamePresent) {
      asn1PrtToStrm_TS24008IE_NetworkName (pctxt, "networkShortName", &pvalue->networkShortName);
   }

   if (pvalue->m.localTimeZonePresent) {
      asn1PrtToStrm_TS24008IE_TimeZone (pctxt, "localTimeZone", &pvalue->localTimeZone);
   }

   if (pvalue->m.univAndLocalTimeZonePresent) {
      asn1PrtToStrm_TS24008IE_TimeZoneAndTime (pctxt, "univAndLocalTimeZone", &pvalue->univAndLocalTimeZone);
   }

   if (pvalue->m.lsaIdentityPresent) {
      asn1PrtToStrm_TS24008IE_LSAIdentifier (pctxt, "lsaIdentity", &pvalue->lsaIdentity);
   }

   if (pvalue->m.networkDaylightSavingTimePresent) {
      asn1PrtToStrm_TS24008IE_DaylightSavingTime (pctxt, "networkDaylightSavingTime", &pvalue->networkDaylightSavingTime);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_MMStatus (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_MMStatus* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_RejectCauseValue (pctxt, "rejectCause", &pvalue->rejectCause);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_TMSIReallocCmd (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_TMSIReallocCmd* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_LocAreaIdent (pctxt, "locAreaIdent", &pvalue->locAreaIdent);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Alerting (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Alerting* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.facilityPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);
   }

   if (pvalue->m.progressIndPresent) {
      asn1PrtToStrm_TS24008IE_ProgressIndicator (pctxt, "progressInd", &pvalue->progressInd);
   }

   if (pvalue->m.user_userPresent) {
      asn1PrtToStrm_TS24008IE_UserUser (pctxt, "user_user", &pvalue->user_user);
   }

   if (pvalue->m.ssVersionPresent) {
      asn1PrtToStrm_TS24008IE_SSVersionIndicator (pctxt, "ssVersion", &pvalue->ssVersion);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_CallConfirmed (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_CallConfirmed* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.repeatIndPresent) {
      asn1PrtToStrm_TS24008IE_RepeatIndicator (pctxt, "repeatInd", &pvalue->repeatInd);
   }

   if (pvalue->m.bearerCap1Present) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap1", &pvalue->bearerCap1);
   }

   if (pvalue->m.bearerCap2Present) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap2", &pvalue->bearerCap2);
   }

   if (pvalue->m.causePresent) {
      asn1PrtToStrm_TS24008IE_Cause (pctxt, "cause", &pvalue->cause);
   }

   if (pvalue->m.callCtrlCapPresent) {
      asn1PrtToStrm_TS24008IE_CallControlCapabilities (pctxt, "callCtrlCap", &pvalue->callCtrlCap);
   }

   if (pvalue->m.streamIdPresent) {
      asn1PrtToStrm_TS24008IE_StreamIdentifierValue (pctxt, "streamId", &pvalue->streamId);
   }

   if (pvalue->m.supportedCodecsPresent) {
      asn1PrtToStrm_TS24008IE_SupportedCodecList (pctxt, "supportedCodecs", &pvalue->supportedCodecs);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_CallProceeding (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_CallProceeding* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.repeatIndPresent) {
      asn1PrtToStrm_TS24008IE_RepeatIndicator (pctxt, "repeatInd", &pvalue->repeatInd);
   }

   if (pvalue->m.bearerCap1Present) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap1", &pvalue->bearerCap1);
   }

   if (pvalue->m.bearerCap2Present) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap2", &pvalue->bearerCap2);
   }

   if (pvalue->m.facilityPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);
   }

   if (pvalue->m.progressIndPresent) {
      asn1PrtToStrm_TS24008IE_ProgressIndicator (pctxt, "progressInd", &pvalue->progressInd);
   }

   if (pvalue->m.priorityGrantedPresent) {
      asn1PrtToStrm_TS24008IE_PriorityLevel (pctxt, "priorityGranted", &pvalue->priorityGranted);
   }

   if (pvalue->m.netCallCtrlCapPresent) {
      asn1PrtToStrm_TS24008IE_NetCallCtrlCaps (pctxt, "netCallCtrlCap", &pvalue->netCallCtrlCap);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_CongestionControl (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_CongestionControl* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_CongestionLevel (pctxt, "congestionLevel", &pvalue->congestionLevel);

   if (pvalue->m.causePresent) {
      asn1PrtToStrm_TS24008IE_Cause (pctxt, "cause", &pvalue->cause);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Connect (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Connect* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.facilityPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);
   }

   if (pvalue->m.progressIndPresent) {
      asn1PrtToStrm_TS24008IE_ProgressIndicator (pctxt, "progressInd", &pvalue->progressInd);
   }

   if (pvalue->m.connNumberPresent) {
      asn1PrtToStrm_TS24008IE_ConnectedNumber (pctxt, "connNumber", &pvalue->connNumber);
   }

   if (pvalue->m.connSubaddrPresent) {
      asn1PrtToStrm_TS24008IE_ConnectedSubaddress (pctxt, "connSubaddr", &pvalue->connSubaddr);
   }

   if (pvalue->m.user_userPresent) {
      asn1PrtToStrm_TS24008IE_UserUser (pctxt, "user_user", &pvalue->user_user);
   }

   if (pvalue->m.ssVersionPresent) {
      asn1PrtToStrm_TS24008IE_SSVersionIndicator (pctxt, "ssVersion", &pvalue->ssVersion);
   }

   if (pvalue->m.streamIdPresent) {
      asn1PrtToStrm_TS24008IE_StreamIdentifierValue (pctxt, "streamId", &pvalue->streamId);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Disconnect (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Disconnect* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_Cause (pctxt, "cause", &pvalue->cause);

   if (pvalue->m.facilityPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);
   }

   if (pvalue->m.progressIndPresent) {
      asn1PrtToStrm_TS24008IE_ProgressIndicator (pctxt, "progressInd", &pvalue->progressInd);
   }

   if (pvalue->m.user_userPresent) {
      asn1PrtToStrm_TS24008IE_UserUser (pctxt, "user_user", &pvalue->user_user);
   }

   if (pvalue->m.allowedActionsPresent) {
      asn1PrtToStrm_TS24008IE_AllowedActions (pctxt, "allowedActions", &pvalue->allowedActions);
   }

   if (pvalue->m.ssVersionPresent) {
      asn1PrtToStrm_TS24008IE_SSVersionIndicator (pctxt, "ssVersion", &pvalue->ssVersion);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_EmergencySetup (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_EmergencySetup* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.bearerCapPresent) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap", &pvalue->bearerCap);
   }

   if (pvalue->m.streamIdPresent) {
      asn1PrtToStrm_TS24008IE_StreamIdentifierValue (pctxt, "streamId", &pvalue->streamId);
   }

   if (pvalue->m.supportedCodecsPresent) {
      asn1PrtToStrm_TS24008IE_SupportedCodecList (pctxt, "supportedCodecs", &pvalue->supportedCodecs);
   }

   if (pvalue->m.emergencyCatPresent) {
      asn1PrtToStrm_TS24008IE_ServiceCategoryValue (pctxt, "emergencyCat", &pvalue->emergencyCat);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_FacilityMsg (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_FacilityMsg* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);

   if (pvalue->m.ssVersionPresent) {
      asn1PrtToStrm_TS24008IE_SSVersionIndicator (pctxt, "ssVersion", &pvalue->ssVersion);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Modify (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Modify* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap", &pvalue->bearerCap);

   if (pvalue->m.lowLayerCompPresent) {
      asn1PrtToStrm_TS24008IE_LowLayerCompatibility (pctxt, "lowLayerComp", &pvalue->lowLayerComp);
   }

   if (pvalue->m.highLayerCompPresent) {
      asn1PrtToStrm_TS24008IE_HighLayerCompatibility (pctxt, "highLayerComp", &pvalue->highLayerComp);
   }

   if (pvalue->m.revCallSetupDirectionPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "revCallSetupDirection");
   }

   if (pvalue->m.netInitServUpgrdIndPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "netInitServUpgrdInd");
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ModifyComplete (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ModifyComplete* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap", &pvalue->bearerCap);

   if (pvalue->m.lowLayerCompPresent) {
      asn1PrtToStrm_TS24008IE_LowLayerCompatibility (pctxt, "lowLayerComp", &pvalue->lowLayerComp);
   }

   if (pvalue->m.highLayerCompPresent) {
      asn1PrtToStrm_TS24008IE_HighLayerCompatibility (pctxt, "highLayerComp", &pvalue->highLayerComp);
   }

   if (pvalue->m.revCallSetupDirectionPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "revCallSetupDirection");
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ModifyReject (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ModifyReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap", &pvalue->bearerCap);

   asn1PrtToStrm_TS24008IE_Cause (pctxt, "cause", &pvalue->cause);

   if (pvalue->m.lowLayerCompPresent) {
      asn1PrtToStrm_TS24008IE_LowLayerCompatibility (pctxt, "lowLayerComp", &pvalue->lowLayerComp);
   }

   if (pvalue->m.highLayerCompPresent) {
      asn1PrtToStrm_TS24008IE_HighLayerCompatibility (pctxt, "highLayerComp", &pvalue->highLayerComp);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Progress (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Progress* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_ProgressIndicator (pctxt, "progressInd", &pvalue->progressInd);

   if (pvalue->m.user_userPresent) {
      asn1PrtToStrm_TS24008IE_UserUser (pctxt, "user_user", &pvalue->user_user);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_CC_EstablishmentConfirmed (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_CC_EstablishmentConfirmed* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.repeatIndPresent) {
      asn1PrtToStrm_TS24008IE_RepeatIndicator (pctxt, "repeatInd", &pvalue->repeatInd);
   }

   if (pvalue->m.bearerCap1Present) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap1", &pvalue->bearerCap1);
   }

   if (pvalue->m.bearerCap2Present) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCap2", &pvalue->bearerCap2);
   }

   if (pvalue->m.causePresent) {
      asn1PrtToStrm_TS24008IE_Cause (pctxt, "cause", &pvalue->cause);
   }

   if (pvalue->m.supportedCodecsPresent) {
      asn1PrtToStrm_TS24008IE_SupportedCodecList (pctxt, "supportedCodecs", &pvalue->supportedCodecs);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Release (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Release* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.causePresent) {
      asn1PrtToStrm_TS24008IE_Cause (pctxt, "cause", &pvalue->cause);
   }

   if (pvalue->m.secondCausePresent) {
      asn1PrtToStrm_TS24008IE_Cause (pctxt, "secondCause", &pvalue->secondCause);
   }

   if (pvalue->m.facilityPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);
   }

   if (pvalue->m.user_userPresent) {
      asn1PrtToStrm_TS24008IE_UserUser (pctxt, "user_user", &pvalue->user_user);
   }

   if (pvalue->m.ssVersionPresent) {
      asn1PrtToStrm_TS24008IE_SSVersionIndicator (pctxt, "ssVersion", &pvalue->ssVersion);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Recall (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Recall* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_RecallType (pctxt, "recallType", &pvalue->recallType);

   asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ReleaseComplete (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ReleaseComplete* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.causePresent) {
      asn1PrtToStrm_TS24008IE_Cause (pctxt, "cause", &pvalue->cause);
   }

   if (pvalue->m.facilityPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);
   }

   if (pvalue->m.user_userPresent) {
      asn1PrtToStrm_TS24008IE_UserUser (pctxt, "user_user", &pvalue->user_user);
   }

   if (pvalue->m.ssVersionPresent) {
      asn1PrtToStrm_TS24008IE_SSVersionIndicator (pctxt, "ssVersion", &pvalue->ssVersion);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Setup (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Setup* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.bcRepeatIndPresent) {
      asn1PrtToStrm_TS24008IE_RepeatIndicator (pctxt, "bcRepeatInd", &pvalue->bcRepeatInd);
   }

   if (pvalue->m.bearerCapability1Present) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCapability1", &pvalue->bearerCapability1);
   }

   if (pvalue->m.bearerCapability2Present) {
      asn1PrtToStrm_TS24008IE_BearerCapability (pctxt, "bearerCapability2", &pvalue->bearerCapability2);
   }

   if (pvalue->m.facilityPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facility", &pvalue->facility);
   }

   if (pvalue->m.progressIndPresent) {
      asn1PrtToStrm_TS24008IE_ProgressIndicator (pctxt, "progressInd", &pvalue->progressInd);
   }

   if (pvalue->m.signal_Present) {
      asn1PrtToStrm_TS24008IE_Signal (pctxt, "signal_", &pvalue->signal_);
   }

   if (pvalue->m.callingPartyNumberPresent) {
      asn1PrtToStrm_TS24008IE_CallingPartyBCDNumber (pctxt, "callingPartyNumber", &pvalue->callingPartyNumber);
   }

   if (pvalue->m.callingPartySubaddressPresent) {
      asn1PrtToStrm_TS24008IE_PartySubaddress (pctxt, "callingPartySubaddress", &pvalue->callingPartySubaddress);
   }

   if (pvalue->m.calledPartyNumberPresent) {
      asn1PrtToStrm_TS24008IE_CalledPartyBCDNumber (pctxt, "calledPartyNumber", &pvalue->calledPartyNumber);
   }

   if (pvalue->m.calledPartySubaddressPresent) {
      asn1PrtToStrm_TS24008IE_PartySubaddress (pctxt, "calledPartySubaddress", &pvalue->calledPartySubaddress);
   }

   if (pvalue->m.redirectingPartyNumberPresent) {
      asn1PrtToStrm_TS24008IE_RedirectingPartyBCDNumber (pctxt, "redirectingPartyNumber", &pvalue->redirectingPartyNumber);
   }

   if (pvalue->m.redirectingPartySubaddressPresent) {
      asn1PrtToStrm_TS24008IE_PartySubaddress (pctxt, "redirectingPartySubaddress", &pvalue->redirectingPartySubaddress);
   }

   if (pvalue->m.llcRepeatIndPresent) {
      asn1PrtToStrm_TS24008IE_RepeatIndicator (pctxt, "llcRepeatInd", &pvalue->llcRepeatInd);
   }

   if (pvalue->m.lowLayerCompat1Present) {
      asn1PrtToStrm_TS24008IE_LowLayerCompatibility (pctxt, "lowLayerCompat1", &pvalue->lowLayerCompat1);
   }

   if (pvalue->m.lowLayerCompat2Present) {
      asn1PrtToStrm_TS24008IE_LowLayerCompatibility (pctxt, "lowLayerCompat2", &pvalue->lowLayerCompat2);
   }

   if (pvalue->m.hlcRepeatIndPresent) {
      asn1PrtToStrm_TS24008IE_RepeatIndicator (pctxt, "hlcRepeatInd", &pvalue->hlcRepeatInd);
   }

   if (pvalue->m.highLayerCompat1Present) {
      asn1PrtToStrm_TS24008IE_HighLayerCompatibility (pctxt, "highLayerCompat1", &pvalue->highLayerCompat1);
   }

   if (pvalue->m.highLayerCompat2Present) {
      asn1PrtToStrm_TS24008IE_HighLayerCompatibility (pctxt, "highLayerCompat2", &pvalue->highLayerCompat2);
   }

   if (pvalue->m.userUserPresent) {
      asn1PrtToStrm_TS24008IE_UserUser (pctxt, "userUser", &pvalue->userUser);
   }

   if (pvalue->m.priorityLevelPresent) {
      asn1PrtToStrm_TS24008IE_PriorityLevel (pctxt, "priorityLevel", &pvalue->priorityLevel);
   }

   if (pvalue->m.alertingPatternPresent) {
      asn1PrtToStrm_TS24008IE_AlertingPattern (pctxt, "alertingPattern", &pvalue->alertingPattern);
   }

   if (pvalue->m.netCallCtrlCapsPresent) {
      asn1PrtToStrm_TS24008IE_NetCallCtrlCaps (pctxt, "netCallCtrlCaps", &pvalue->netCallCtrlCaps);
   }

   if (pvalue->m.causeOfNoCLIPresent) {
      asn1PrtToStrm_TS24008IE_CauseOfNoCLI (pctxt, "causeOfNoCLI", &pvalue->causeOfNoCLI);
   }

   if (pvalue->m.backupBearerCapabilityPresent) {
      asn1PrtToStrm_TS24008IE_BackupBearerCapability (pctxt, "backupBearerCapability", &pvalue->backupBearerCapability);
   }

   if (pvalue->m.ssVersionPresent) {
      asn1PrtToStrm_TS24008IE_SSVersionIndicator (pctxt, "ssVersion", &pvalue->ssVersion);
   }

   if (pvalue->m.clirSuppressionPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "clirSuppression");
   }

   if (pvalue->m.clirInvocationPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "clirInvocation");
   }

   if (pvalue->m.callCtrlCapPresent) {
      asn1PrtToStrm_TS24008IE_CallControlCapabilities (pctxt, "callCtrlCap", &pvalue->callCtrlCap);
   }

   if (pvalue->m.facilityAdvRecallAlignPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facilityAdvRecallAlign", &pvalue->facilityAdvRecallAlign);
   }

   if (pvalue->m.facilityRecallAlignNotEssentialPresent) {
      asn1PrtToStrm_TS24008IE_Facility (pctxt, "facilityRecallAlignNotEssential", &pvalue->facilityRecallAlignNotEssential);
   }

   if (pvalue->m.streamIdPresent) {
      asn1PrtToStrm_TS24008IE_StreamIdentifierValue (pctxt, "streamId", &pvalue->streamId);
   }

   if (pvalue->m.supportedCodecsPresent) {
      asn1PrtToStrm_TS24008IE_SupportedCodecList (pctxt, "supportedCodecs", &pvalue->supportedCodecs);
   }

   if (pvalue->m.redialPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "redial");
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_StartCC (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_StartCC* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.ccCapabilitiesPresent) {
      asn1PrtToStrm_TS24008IE_CallControlCapabilities (pctxt, "ccCapabilities", &pvalue->ccCapabilities);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_Status (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_Status* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_Cause (pctxt, "cause", &pvalue->cause);

   asn1PrtToStrm_TS24008IE_CallState (pctxt, "callState", &pvalue->callState);

   if (pvalue->m.auxStatesPresent) {
      asn1PrtToStrm_TS24008IE_AuxiliaryStates (pctxt, "auxStates", &pvalue->auxStates);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_UserInfo (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_UserInfo* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_UserUser (pctxt, "userUser", &pvalue->userUser);

   if (pvalue->m.moreDataPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "moreData");
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AttachRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AttachRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_MSNetworkCapability (pctxt, "msNetCapability", &pvalue->msNetCapability);

   asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "gprsCiphKeySeq", &pvalue->gprsCiphKeySeq);

   asn1PrtToStrm_TS24008IE_AttachType (pctxt, "attachType", &pvalue->attachType);

   asn1PrtToStrm_TS24008IE_DRXParameter (pctxt, "drxParameter", &pvalue->drxParameter);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "pTMSIOrIMSI", &pvalue->pTMSIOrIMSI);

   asn1PrtToStrm_TS24008IE_RoutingAreaIdent (pctxt, "oldRoutingAreaId", &pvalue->oldRoutingAreaId);

   asn1PrtToStrm_TS24008IE_MSRadioAccessCapability (pctxt, "msRACapability", &pvalue->msRACapability);

   if (pvalue->m.oldPTMSISignaturePresent) {
      asn1PrtToStrm_TS24008IE_P_TMSISignature (pctxt, "oldPTMSISignature", &pvalue->oldPTMSISignature);
   }

   if (pvalue->m.reqREADYTimerValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "reqREADYTimerValue", &pvalue->reqREADYTimerValue);
   }

   if (pvalue->m.tmsiStatusPresent) {
      asn1PrtToStrm_TS24008IE_TMSIStatus (pctxt, "tmsiStatus", &pvalue->tmsiStatus);
   }

   if (pvalue->m.psLCSCapPresent) {
      asn1PrtToStrm_TS24008IE_PS_LCSCapbility (pctxt, "psLCSCap", &pvalue->psLCSCap);
   }

   if (pvalue->m.msClassmark2Present) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark2 (pctxt, "msClassmark2", &pvalue->msClassmark2);
   }

   if (pvalue->m.msClassmark3Present) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark3 (pctxt, "msClassmark3", &pvalue->msClassmark3);
   }

   if (pvalue->m.supportedCodecsPresent) {
      asn1PrtToStrm_TS24008IE_SupportedCodecList (pctxt, "supportedCodecs", &pvalue->supportedCodecs);
   }

   if (pvalue->m.ueNetCapPresent) {
      asn1PrtToStrm_TS24008IE_UENetCapability (pctxt, "ueNetCap", &pvalue->ueNetCap);
   }

   if (pvalue->m.addnMobileIdPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "addnMobileId", &pvalue->addnMobileId);
   }

   if (pvalue->m.addnOldRoutingAreaIdPresent) {
      asn1PrtToStrm_TS24008IE_RoutingAreaIdent2 (pctxt, "addnOldRoutingAreaId", &pvalue->addnOldRoutingAreaId);
   }

   if (pvalue->m._v9ExtPresent) {
      if (pvalue->m.voiceDomainPrefPresent) {
         asn1PrtToStrm_TS24008IE_VoiceDomainPref (pctxt, "voiceDomainPref", &pvalue->voiceDomainPref);
      }
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
      if (pvalue->m.p_TMSI_TypePresent) {
         asn1PrtToStrm_TS24008IE_P_TMSI_Type (pctxt, "p_TMSI_Type", &pvalue->p_TMSI_Type);
      }
      if (pvalue->m.msNetFeatureSupportPresent) {
         asn1PrtToStrm_TS24008IE_MSNetFeatureSupport (pctxt, "msNetFeatureSupport", &pvalue->msNetFeatureSupport);
      }
      if (pvalue->m.oldLocAreaIdentPresent) {
         asn1PrtToStrm_TS24008IE_LocAreaIdent2 (pctxt, "oldLocAreaIdent", &pvalue->oldLocAreaIdent);
      }
   }

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.addnUpdateTypePresent) {
         asn1PrtToStrm_TS24008IE_AddnUpdateType (pctxt, "addnUpdateType", &pvalue->addnUpdateType);
      }
      if (pvalue->m.tmsiBasedNRIContPresent) {
         asn1PrtToStrm_TS24008IE_NetResourceIdentContainer (pctxt, "tmsiBasedNRICont", &pvalue->tmsiBasedNRICont);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AttachAccept (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AttachAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_ForceToStandbyValue (pctxt, "forceToStandby", &pvalue->forceToStandby);

   asn1PrtToStrm_TS24008IE_AttachResult (pctxt, "attachResult", &pvalue->attachResult);

   asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "periodicRAUpdateTimer", &pvalue->periodicRAUpdateTimer);

   asn1PrtToStrm_TS24008IE_RadioPriorityValue2 (pctxt, "radioPriForTOM8", &pvalue->radioPriForTOM8);

   asn1PrtToStrm_TS24008IE_RadioPriorityValue (pctxt, "radioPriForSMS", &pvalue->radioPriForSMS);

   asn1PrtToStrm_TS24008IE_RoutingAreaIdent (pctxt, "routingAreaIdent", &pvalue->routingAreaIdent);

   if (pvalue->m.pTMSISignaturePresent) {
      asn1PrtToStrm_TS24008IE_P_TMSISignature (pctxt, "pTMSISignature", &pvalue->pTMSISignature);
   }

   if (pvalue->m.negotiatedREADYTimerValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "negotiatedREADYTimerValue", &pvalue->negotiatedREADYTimerValue);
   }

   if (pvalue->m.allocatedPTMSIPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "allocatedPTMSI", &pvalue->allocatedPTMSI);
   }

   if (pvalue->m.msIdentityPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "msIdentity", &pvalue->msIdentity);
   }

   if (pvalue->m.gmmCausePresent) {
      asn1PrtToStrm_TS24008IE_GMMCauseValue (pctxt, "gmmCause", &pvalue->gmmCause);
   }

   if (pvalue->m.t3302ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3302Value", &pvalue->t3302Value);
   }

   if (pvalue->m.cellNotificationPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "cellNotification");
   }

   if (pvalue->m.equivalentPLMNsPresent) {
      asn1PrtToStrm_TS24008IE_PLMNList (pctxt, "equivalentPLMNs", &pvalue->equivalentPLMNs);
   }

   if (pvalue->m.netFeatureSupportPresent) {
      asn1PrtToStrm_TS24008IE_NetFeatureSupp (pctxt, "netFeatureSupport", &pvalue->netFeatureSupport);
   }

   if (pvalue->m.emergencyNumListPresent) {
      asn1PrtToStrm_TS24008IE_EmergencyNumberList (pctxt, "emergencyNumList", &pvalue->emergencyNumList);
   }

   if (pvalue->m.requestedMSInfoPresent) {
      asn1PrtToStrm_TS24008IE_RequestedMSInfo (pctxt, "requestedMSInfo", &pvalue->requestedMSInfo);
   }

   if (pvalue->m.t3319ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3319Value", &pvalue->t3319Value);
   }

   if (pvalue->m.t3323ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3323Value", &pvalue->t3323Value);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3312ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3312Value", &pvalue->t3312Value);
      }
   }

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.addnNetFeatureSupportPresent) {
         asn1PrtToStrm_TS24008IE_AddnNetFeatureSupport (pctxt, "addnNetFeatureSupport", &pvalue->addnNetFeatureSupport);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AttachComplete (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AttachComplete* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.erRATInfoContainerPresent) {
      asn1PrtToStrm_TS24008IE_InterRATInfoContainer (pctxt, "erRATInfoContainer", &pvalue->erRATInfoContainer);
   }

   if (pvalue->m.eUTRANInterRATInfoContainerPresent) {
      asn1PrtToStrm_TS24008IE_E_UTRANInterRATInfoContainer (pctxt, "eUTRANInterRATInfoContainer", &pvalue->eUTRANInterRATInfoContainer);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AttachReject (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AttachReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_GMMCauseValue (pctxt, "gmmCause", &pvalue->gmmCause);

   if (pvalue->m.t3302ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3302Value", &pvalue->t3302Value);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3346ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3346Value", &pvalue->t3346Value);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_DetachRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_DetachRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_DetachType (pctxt, "detachType", &pvalue->detachType);

   asn1PrtToStrm_TS24008IE_ForceToStandbyValue (pctxt, "forceToStandby", &pvalue->forceToStandby);

   if (pvalue->m.gmmCausePresent) {
      asn1PrtToStrm_TS24008IE_GMMCauseValue (pctxt, "gmmCause", &pvalue->gmmCause);
   }

   if (pvalue->m.pTMSIPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "pTMSI", &pvalue->pTMSI);
   }

   if (pvalue->m.pTMSISignaturePresent) {
      asn1PrtToStrm_TS24008IE_P_TMSISignature2 (pctxt, "pTMSISignature", &pvalue->pTMSISignature);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_DetachAccept (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_DetachAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.forceToStandbyPresent) {
      asn1PrtToStrm_TS24008IE_ForceToStandbyValue (pctxt, "forceToStandby", &pvalue->forceToStandby);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_P_TMSIReallocCmd (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_P_TMSIReallocCmd* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "allocatedPTMSI", &pvalue->allocatedPTMSI);

   asn1PrtToStrm_TS24008IE_RoutingAreaIdent (pctxt, "routingAreaIdent", &pvalue->routingAreaIdent);

   asn1PrtToStrm_TS24008IE_ForceToStandbyValue (pctxt, "forceToStandby", &pvalue->forceToStandby);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   if (pvalue->m.pTMSISignaturePresent) {
      asn1PrtToStrm_TS24008IE_P_TMSISignature (pctxt, "pTMSISignature", &pvalue->pTMSISignature);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AuthAndCiphRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AuthAndCiphRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_CipheringAlgorithmType (pctxt, "cipheringAlgorithm", &pvalue->cipheringAlgorithm);

   asn1PrtToStrm_TS24008IE_IMEISVRequest (pctxt, "imeisvRequest", &pvalue->imeisvRequest);

   asn1PrtToStrm_TS24008IE_ForceToStandbyValue (pctxt, "forceToStandby", &pvalue->forceToStandby);

   asn1PrtToStrm_TS24008IE_AC_Reference_Number (pctxt, "acRefNumber", &pvalue->acRefNumber);

   if (pvalue->m.authParamRANDPresent) {
      asn1PrtToStrm_TS24008IE_AuthParamRAND (pctxt, "authParamRAND", &pvalue->authParamRAND);
   }

   if (pvalue->m.ciphKeySeqNumPresent) {
      asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "ciphKeySeqNum", &pvalue->ciphKeySeqNum);
   }

   if (pvalue->m.authParamAUTNPresent) {
      asn1PrtToStrm_TS24008IE_AuthParamAUTN (pctxt, "authParamAUTN", &pvalue->authParamAUTN);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AuthAndCiphResponse (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AuthAndCiphResponse* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_AC_Reference_Number (pctxt, "acRefNumber", &pvalue->acRefNumber);

   if (pvalue->m.authRespParamPresent) {
      asn1PrtToStrm_TS24008IE_AuthRespParam (pctxt, "authRespParam", &pvalue->authRespParam);
   }

   if (pvalue->m.imeisvPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "imeisv", &pvalue->imeisv);
   }

   if (pvalue->m.authRespParamExtPresent) {
      asn1PrtToStrm_TS24008IE_AuthRespParamExt (pctxt, "authRespParamExt", &pvalue->authRespParamExt);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_AuthAndCiphFailure (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_AuthAndCiphFailure* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_GMMCauseValue (pctxt, "gmmCause", &pvalue->gmmCause);

   if (pvalue->m.authFailureParamPresent) {
      asn1PrtToStrm_TS24008IE_AuthFailureParam (pctxt, "authFailureParam", &pvalue->authFailureParam);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_GMMIdentityRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_GMMIdentityRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_ForceToStandbyValue (pctxt, "forceToStandby", &pvalue->forceToStandby);

   asn1PrtToStrm_TS24008IE_IdentityType2Value (pctxt, "identityType", &pvalue->identityType);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_GMMIdentityResponse (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_GMMIdentityResponse* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RoutingAreaUpdateRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RoutingAreaUpdateRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "gprsCiphKeySeq", &pvalue->gprsCiphKeySeq);

   asn1PrtToStrm_TS24008IE_UpdateType (pctxt, "updateType", &pvalue->updateType);

   asn1PrtToStrm_TS24008IE_RoutingAreaIdent (pctxt, "oldRoutingAreaId", &pvalue->oldRoutingAreaId);

   asn1PrtToStrm_TS24008IE_MSRadioAccessCapability (pctxt, "msRACapability", &pvalue->msRACapability);

   if (pvalue->m.oldPTMSISignaturePresent) {
      asn1PrtToStrm_TS24008IE_P_TMSISignature (pctxt, "oldPTMSISignature", &pvalue->oldPTMSISignature);
   }

   if (pvalue->m.reqREADYTimerValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "reqREADYTimerValue", &pvalue->reqREADYTimerValue);
   }

   if (pvalue->m.drxParameterPresent) {
      asn1PrtToStrm_TS24008IE_DRXParameter (pctxt, "drxParameter", &pvalue->drxParameter);
   }

   if (pvalue->m.tmsiStatusPresent) {
      asn1PrtToStrm_TS24008IE_TMSIStatus (pctxt, "tmsiStatus", &pvalue->tmsiStatus);
   }

   if (pvalue->m.pTMSIPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "pTMSI", &pvalue->pTMSI);
   }

   if (pvalue->m.msNetCapabilityPresent) {
      asn1PrtToStrm_TS24008IE_MSNetworkCapability (pctxt, "msNetCapability", &pvalue->msNetCapability);
   }

   if (pvalue->m.pdpContextStatusPresent) {
      asn1PrtToStrm_TS24008IE_PDPContextStatus (pctxt, "pdpContextStatus", &pvalue->pdpContextStatus);
   }

   if (pvalue->m.psLCSCapPresent) {
      asn1PrtToStrm_TS24008IE_PS_LCSCapbility (pctxt, "psLCSCap", &pvalue->psLCSCap);
   }

   if (pvalue->m.mbmsContextStatusPresent) {
      asn1PrtToStrm_TS24008IE_MBMSContextStatus (pctxt, "mbmsContextStatus", &pvalue->mbmsContextStatus);
   }

   if (pvalue->m.ueNetCapPresent) {
      asn1PrtToStrm_TS24008IE_UENetCapability (pctxt, "ueNetCap", &pvalue->ueNetCap);
   }

   if (pvalue->m.addnMobileIdPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "addnMobileId", &pvalue->addnMobileId);
   }

   if (pvalue->m.addnOldRoutingAreaIdPresent) {
      asn1PrtToStrm_TS24008IE_RoutingAreaIdent2 (pctxt, "addnOldRoutingAreaId", &pvalue->addnOldRoutingAreaId);
   }

   if (pvalue->m.msClassmark2Present) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark2 (pctxt, "msClassmark2", &pvalue->msClassmark2);
   }

   if (pvalue->m.msClassmark3Present) {
      asn1PrtToStrm_TS24008IE_MobileStationClassmark3 (pctxt, "msClassmark3", &pvalue->msClassmark3);
   }

   if (pvalue->m.supportedCodecsPresent) {
      asn1PrtToStrm_TS24008IE_SupportedCodecList (pctxt, "supportedCodecs", &pvalue->supportedCodecs);
   }

   if (pvalue->m._v9ExtPresent) {
      if (pvalue->m.voiceDomainPrefPresent) {
         asn1PrtToStrm_TS24008IE_VoiceDomainPref (pctxt, "voiceDomainPref", &pvalue->voiceDomainPref);
      }
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.p_TMSI_TypePresent) {
         asn1PrtToStrm_TS24008IE_P_TMSI_Type (pctxt, "p_TMSI_Type", &pvalue->p_TMSI_Type);
      }
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
      if (pvalue->m.msNetFeatureSupportPresent) {
         asn1PrtToStrm_TS24008IE_MSNetFeatureSupport (pctxt, "msNetFeatureSupport", &pvalue->msNetFeatureSupport);
      }
      if (pvalue->m.oldLocAreaIdentPresent) {
         asn1PrtToStrm_TS24008IE_LocAreaIdent2 (pctxt, "oldLocAreaIdent", &pvalue->oldLocAreaIdent);
      }
   }

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.addnUpdateTypePresent) {
         asn1PrtToStrm_TS24008IE_AddnUpdateType (pctxt, "addnUpdateType", &pvalue->addnUpdateType);
      }
      if (pvalue->m.tmsiBasedNRIContPresent) {
         asn1PrtToStrm_TS24008IE_NetResourceIdentContainer (pctxt, "tmsiBasedNRICont", &pvalue->tmsiBasedNRICont);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RoutingAreaUpdateAccept (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RoutingAreaUpdateAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_ForceToStandbyValue (pctxt, "forceToStandby", &pvalue->forceToStandby);

   asn1PrtToStrm_TS24008IE_UpdateResult (pctxt, "updateResult", &pvalue->updateResult);

   asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "periodicRAUpdateTimer", &pvalue->periodicRAUpdateTimer);

   asn1PrtToStrm_TS24008IE_RoutingAreaIdent (pctxt, "routingAreaIdent", &pvalue->routingAreaIdent);

   if (pvalue->m.pTMSISignaturePresent) {
      asn1PrtToStrm_TS24008IE_P_TMSISignature (pctxt, "pTMSISignature", &pvalue->pTMSISignature);
   }

   if (pvalue->m.allocatedPTMSIPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "allocatedPTMSI", &pvalue->allocatedPTMSI);
   }

   if (pvalue->m.msIdentityPresent) {
      asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "msIdentity", &pvalue->msIdentity);
   }

   if (pvalue->m.receiveNPDUNumberListPresent) {
      asn1PrtToStrm_TS24008IE_ReceiveNPDUNumberList (pctxt, "receiveNPDUNumberList", &pvalue->receiveNPDUNumberList);
   }

   if (pvalue->m.negotiatedREADYTimerValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer (pctxt, "negotiatedREADYTimerValue", &pvalue->negotiatedREADYTimerValue);
   }

   if (pvalue->m.gmmCausePresent) {
      asn1PrtToStrm_TS24008IE_GMMCauseValue (pctxt, "gmmCause", &pvalue->gmmCause);
   }

   if (pvalue->m.t3302ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3302Value", &pvalue->t3302Value);
   }

   if (pvalue->m.cellNotificationPresent) {
      rtPrintToStreamIndent (pctxt);
      rtxPrintToStreamNull (pctxt, "cellNotification");
   }

   if (pvalue->m.equivalentPLMNsPresent) {
      asn1PrtToStrm_TS24008IE_PLMNList (pctxt, "equivalentPLMNs", &pvalue->equivalentPLMNs);
   }

   if (pvalue->m.pdpContextStatusPresent) {
      asn1PrtToStrm_TS24008IE_PDPContextStatus (pctxt, "pdpContextStatus", &pvalue->pdpContextStatus);
   }

   if (pvalue->m.netFeatureSupportPresent) {
      asn1PrtToStrm_TS24008IE_NetFeatureSupp (pctxt, "netFeatureSupport", &pvalue->netFeatureSupport);
   }

   if (pvalue->m.emergencyNumListPresent) {
      asn1PrtToStrm_TS24008IE_EmergencyNumberList (pctxt, "emergencyNumList", &pvalue->emergencyNumList);
   }

   if (pvalue->m.mbmsContextStatusPresent) {
      asn1PrtToStrm_TS24008IE_MBMSContextStatus (pctxt, "mbmsContextStatus", &pvalue->mbmsContextStatus);
   }

   if (pvalue->m.requestedMSInfoPresent) {
      asn1PrtToStrm_TS24008IE_RequestedMSInfo (pctxt, "requestedMSInfo", &pvalue->requestedMSInfo);
   }

   if (pvalue->m.t3319ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3319Value", &pvalue->t3319Value);
   }

   if (pvalue->m.t3323ValuePresent) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3323Value", &pvalue->t3323Value);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3312ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3312Value", &pvalue->t3312Value);
      }
   }

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.addnNetFeatureSupportPresent) {
         asn1PrtToStrm_TS24008IE_AddnNetFeatureSupport (pctxt, "addnNetFeatureSupport", &pvalue->addnNetFeatureSupport);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RoutingAreaUpdateComplete (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RoutingAreaUpdateComplete* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.receiveNPDUNumberListPresent) {
      asn1PrtToStrm_TS24008IE_ReceiveNPDUNumberList (pctxt, "receiveNPDUNumberList", &pvalue->receiveNPDUNumberList);
   }

   if (pvalue->m.interRATInfoContainerPresent) {
      asn1PrtToStrm_TS24008IE_InterRATInfoContainer (pctxt, "interRATInfoContainer", &pvalue->interRATInfoContainer);
   }

   if (pvalue->m.eUTRANInterRATInfoContainerPresent) {
      asn1PrtToStrm_TS24008IE_E_UTRANInterRATInfoContainer (pctxt, "eUTRANInterRATInfoContainer", &pvalue->eUTRANInterRATInfoContainer);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RoutingAreaUpdateReject (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RoutingAreaUpdateReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_GMMCauseValue (pctxt, "gmmCause", &pvalue->gmmCause);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_ForceToStandbyValue (pctxt, "forceToStandby", &pvalue->forceToStandby);

   if (pvalue->m.gprsTimer2Present) {
      asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "gprsTimer2", &pvalue->gprsTimer2);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3346ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3346Value", &pvalue->t3346Value);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_GMMInformation (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_GMMInformation* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.fullNetNamePresent) {
      asn1PrtToStrm_TS24008IE_NetworkName (pctxt, "fullNetName", &pvalue->fullNetName);
   }

   if (pvalue->m.shortNetNamePresent) {
      asn1PrtToStrm_TS24008IE_NetworkName (pctxt, "shortNetName", &pvalue->shortNetName);
   }

   if (pvalue->m.localTimeZonePresent) {
      asn1PrtToStrm_TS24008IE_TimeZone (pctxt, "localTimeZone", &pvalue->localTimeZone);
   }

   if (pvalue->m.universalAndLocalTimeZonePresent) {
      asn1PrtToStrm_TS24008IE_TimeZoneAndTime (pctxt, "universalAndLocalTimeZone", &pvalue->universalAndLocalTimeZone);
   }

   if (pvalue->m.lsaIdentityPresent) {
      asn1PrtToStrm_TS24008IE_LSAIdentifier (pctxt, "lsaIdentity", &pvalue->lsaIdentity);
   }

   if (pvalue->m.networkDSTPresent) {
      asn1PrtToStrm_TS24008IE_DaylightSavingTime (pctxt, "networkDST", &pvalue->networkDST);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ServiceRequest (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ServiceRequest* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_ServiceType (pctxt, "serviceType", &pvalue->serviceType);

   asn1PrtToStrm_TS24008IE_CiphKeySeqNum (pctxt, "ciphKeySeqNum", &pvalue->ciphKeySeqNum);

   asn1PrtToStrm_TS24008IE_MobileIdentity (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

   if (pvalue->m.pdpContextStatusPresent) {
      asn1PrtToStrm_TS24008IE_PDPContextStatus (pctxt, "pdpContextStatus", &pvalue->pdpContextStatus);
   }

   if (pvalue->m.mbmsContextStatusPresent) {
      asn1PrtToStrm_TS24008IE_MBMSContextStatus (pctxt, "mbmsContextStatus", &pvalue->mbmsContextStatus);
   }

   if (pvalue->m.uplinkDataStatusPresent) {
      asn1PrtToStrm_TS24008IE_UplinkDataStatus (pctxt, "uplinkDataStatus", &pvalue->uplinkDataStatus);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ServiceAccept (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ServiceAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.pdpContextStatusPresent) {
      asn1PrtToStrm_TS24008IE_PDPContextStatus (pctxt, "pdpContextStatus", &pvalue->pdpContextStatus);
   }

   if (pvalue->m.mbmsContextStatusPresent) {
      asn1PrtToStrm_TS24008IE_MBMSContextStatus (pctxt, "mbmsContextStatus", &pvalue->mbmsContextStatus);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ServiceReject (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ServiceReject* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_GMMCauseValue (pctxt, "gmmCause", &pvalue->gmmCause);

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.t3346ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer2 (pctxt, "t3346Value", &pvalue->t3346Value);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivatePDPCtxtReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_NSAPIValue (pctxt, "requestedNSAPI", &pvalue->requestedNSAPI);

   asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "requestedLLCSAPI", &pvalue->requestedLLCSAPI);

   asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "requestedQOS", &pvalue->requestedQOS);

   asn1PrtToStrm_TS24008IE_PacketDataProtoAddr (pctxt, "requestedPDPAddr", &pvalue->requestedPDPAddr);

   if (pvalue->m.accessPointNamePresent) {
      asn1PrtToStrm_TS24008IE_AccessPointName (pctxt, "accessPointName", pvalue->accessPointName);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m.requestTypePresent) {
      asn1PrtToStrm_TS24008IE_RequestTypeValue (pctxt, "requestType", &pvalue->requestType);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtAccept (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivatePDPCtxtAccept* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "negotiatedLLCSAPI", &pvalue->negotiatedLLCSAPI);

   asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "negotiatedQOS", &pvalue->negotiatedQOS);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_RadioPriorityValue (pctxt, "radioPriority", &pvalue->radioPriority);

   if (pvalue->m.pdpAddressPresent) {
      asn1PrtToStrm_TS24008IE_PacketDataProtoAddr (pctxt, "pdpAddress", &pvalue->pdpAddress);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m.packetFlowIdentPresent) {
      asn1PrtToStrm_TS24008IE_PacketFlowIdentValue (pctxt, "packetFlowIdent", &pvalue->packetFlowIdent);
   }

   if (pvalue->m.smCausePresent) {
      asn1PrtToStrm_TS24008IE_SMCause2Value (pctxt, "smCause", &pvalue->smCause);
   }

   if (pvalue->m._v10ExtPresent) {
      asn1PrtToStrm_TS24008IE_ConnectivityType (pctxt, "connectivityType", &pvalue->connectivityType);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivateSecondaryPDPCtxtRqst (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivateSecondaryPDPCtxtRqst* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_NSAPIValue (pctxt, "requestedNSAPI", &pvalue->requestedNSAPI);

   asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "requestedLLCSAPI", &pvalue->requestedLLCSAPI);

   asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "requestedQOS", &pvalue->requestedQOS);

   asn1PrtToStrm_TS24008IE_LinkedTI (pctxt, "linkedTI", &pvalue->linkedTI);

   if (pvalue->m.trafficFlowTemplatePresent) {
      asn1PrtToStrm_TS24008IE_TFT (pctxt, "trafficFlowTemplate", &pvalue->trafficFlowTemplate);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivateSecondaryPDPCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivateSecondaryPDPCtxtAcc* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "negotiatedLLCSAPI", &pvalue->negotiatedLLCSAPI);

   asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "negotiatedQOS", &pvalue->negotiatedQOS);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_RadioPriorityValue (pctxt, "radioPriority", &pvalue->radioPriority);

   if (pvalue->m.packetFlowIdentPresent) {
      asn1PrtToStrm_TS24008IE_PacketFlowIdentValue (pctxt, "packetFlowIdent", &pvalue->packetFlowIdent);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RequestPDPCtxtAct (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RequestPDPCtxtAct* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_PacketDataProtoAddr (pctxt, "offeredPDPAddress", &pvalue->offeredPDPAddress);

   if (pvalue->m.accessPointNamePresent) {
      asn1PrtToStrm_TS24008IE_AccessPointName (pctxt, "accessPointName", pvalue->accessPointName);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtRqstNetToMS (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ModifyPDPCtxtRqstNetToMS* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

   asn1PrtToStrm_TS24008IE_RadioPriorityValue (pctxt, "radioPriority", &pvalue->radioPriority);

   asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "requestedLLCSAPI", &pvalue->requestedLLCSAPI);

   asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "newQOS", &pvalue->newQOS);

   if (pvalue->m.pdpAddressPresent) {
      asn1PrtToStrm_TS24008IE_PacketDataProtoAddr (pctxt, "pdpAddress", &pvalue->pdpAddress);
   }

   if (pvalue->m.packetFlowIdentPresent) {
      asn1PrtToStrm_TS24008IE_PacketFlowIdentValue (pctxt, "packetFlowIdent", &pvalue->packetFlowIdent);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m.trafficFlowTemplatePresent) {
      asn1PrtToStrm_TS24008IE_TFT (pctxt, "trafficFlowTemplate", &pvalue->trafficFlowTemplate);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtRqstMSToNet (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ModifyPDPCtxtRqstMSToNet* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.requestedLLCSAPIPresent) {
      asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "requestedLLCSAPI", &pvalue->requestedLLCSAPI);
   }

   if (pvalue->m.requestedNewQOSPresent) {
      asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "requestedNewQOS", &pvalue->requestedNewQOS);
   }

   if (pvalue->m.newTFTPresent) {
      asn1PrtToStrm_TS24008IE_TFT (pctxt, "newTFT", &pvalue->newTFT);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtAccMSToNet (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ModifyPDPCtxtAccMSToNet* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtAccNetToMS (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ModifyPDPCtxtAccNetToMS* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.negotiatedQOSPresent) {
      asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "negotiatedQOS", &pvalue->negotiatedQOS);
   }

   if (pvalue->m.negotiatedLLCSAPIPresent) {
      asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "negotiatedLLCSAPI", &pvalue->negotiatedLLCSAPI);
   }

   if (pvalue->m.newRadioPriorityPresent) {
      asn1PrtToStrm_TS24008IE_RadioPriorityValue (pctxt, "newRadioPriority", &pvalue->newRadioPriority);
   }

   if (pvalue->m.packetFlowIdentPresent) {
      asn1PrtToStrm_TS24008IE_PacketFlowIdentValue (pctxt, "packetFlowIdent", &pvalue->packetFlowIdent);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_DeactivatePDPCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_DeactivatePDPCtxtReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_SMCauseValue (pctxt, "smCause", &pvalue->smCause);

   if (pvalue->m.tearDownIndicatorPresent) {
      asn1PrtToStrm_TS24008IE_TDIValue (pctxt, "tearDownIndicator", &pvalue->tearDownIndicator);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m.mbmsPCOPresent) {
      asn1PrtToStrm_TS24008IE_MBMS_PCO (pctxt, "mbmsPCO", &pvalue->mbmsPCO);
   }

   if (pvalue->m._v11ExtPresent) {
      if (pvalue->m.t3396ValuePresent) {
         asn1PrtToStrm_TS24008IE_GPRSTimer3 (pctxt, "t3396Value", &pvalue->t3396Value);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_DeactivatePDPCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_DeactivatePDPCtxtAcc* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   if (pvalue->m.mbmsPCOPresent) {
      asn1PrtToStrm_TS24008IE_MBMS_PCO (pctxt, "mbmsPCO", &pvalue->mbmsPCO);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RqstSecondaryPDPCtxtAct (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RqstSecondaryPDPCtxtAct* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_QualityOfService (pctxt, "requiredQOS", &pvalue->requiredQOS);

   asn1PrtToStrm_TS24008IE_LinkedTI (pctxt, "linkedTI", &pvalue->linkedTI);

   if (pvalue->m.trafficFlowTemplatePresent) {
      asn1PrtToStrm_TS24008IE_TFT (pctxt, "trafficFlowTemplate", &pvalue->trafficFlowTemplate);
   }

   if (pvalue->m.protocolConfigOptionsPresent) {
      asn1PrtToStrm_TS24008IE_ProtocolConfigOptions (pctxt, "protocolConfigOptions", &pvalue->protocolConfigOptions);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivateMBMSCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivateMBMSCtxtReq* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_EnhancedNSAPIValue (pctxt, "requestedMBMSNSAPI", &pvalue->requestedMBMSNSAPI);

   asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "requestedLLCSAPI", &pvalue->requestedLLCSAPI);

   asn1PrtToStrm_TS24008IE_MBMSBearerCaps (pctxt, "supportedMBMSBearerCaps", &pvalue->supportedMBMSBearerCaps);

   asn1PrtToStrm_TS24008IE_PacketDataProtoAddr (pctxt, "requestedMulticastAddr", &pvalue->requestedMulticastAddr);

   asn1PrtToStrm_TS24008IE_AccessPointName (pctxt, "accessPointName", pvalue->accessPointName);

   if (pvalue->m.mbmsPCOPresent) {
      asn1PrtToStrm_TS24008IE_MBMS_PCO (pctxt, "mbmsPCO", &pvalue->mbmsPCO);
   }

   if (pvalue->m._v10ExtPresent) {
      if (pvalue->m.devicePropertiesPresent) {
         asn1PrtToStrm_TS24008IE_DeviceProperties (pctxt, "deviceProperties", &pvalue->deviceProperties);
      }
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_ActivateMBMSCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_ActivateMBMSCtxtAcc* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_TMGI (pctxt, "tmgi", &pvalue->tmgi);

   asn1PrtToStrm_TS24008IE_LLCSAPIValue (pctxt, "negotiatedLLCSAPI", &pvalue->negotiatedLLCSAPI);

   if (pvalue->m.mbmsPCOPresent) {
      asn1PrtToStrm_TS24008IE_MBMS_PCO (pctxt, "mbmsPCO", &pvalue->mbmsPCO);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_RequestMBMSCtxtAct (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_RequestMBMSCtxtAct* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24008IE_NSAPIValue (pctxt, "linkedNSAPI", &pvalue->linkedNSAPI);

   asn1PrtToStrm_TS24008IE_PacketDataProtoAddr (pctxt, "offeredMulticastAddr", &pvalue->offeredMulticastAddr);

   asn1PrtToStrm_TS24008IE_AccessPointName (pctxt, "accessPointName", pvalue->accessPointName);

   if (pvalue->m.mbmsPCOPresent) {
      asn1PrtToStrm_TS24008IE_MBMS_PCO (pctxt, "mbmsPCO", &pvalue->mbmsPCO);
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_TS24008Msg_PDU (OSCTXT *pctxt, 
   const char* name, const TS24008Msg_PDU* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_TS24007L3_L3HdrOptions (pctxt, "l3HdrOpts", &pvalue->l3HdrOpts);

   asn1PrtToStrm_TS24007L3_ProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

   if (pvalue->m.sendSeqNumPresent) {
      rtPrintToStreamIndent (pctxt);
      rtPrintToStreamUnsigned (pctxt, "sendSeqNum", pvalue->sendSeqNum);
   }

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "msgType", pvalue->msgType);

   rtPrintToStreamOpenBrace (pctxt, "data");

   switch (pvalue->data.t)
   {
      /* obj_AuthenticationReject */
      case 1:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_AuthenticationReject");
         break;
      }
      /* obj_AuthenticationRequest */
      case 2:
      {
         asn1PrtToStrm_TS24008Msg_AuthenticationRequest (pctxt, "obj_AuthenticationRequest", pvalue->data.u.obj_AuthenticationRequest);
         break;
      }
      /* obj_AuthenticationResponse */
      case 3:
      {
         asn1PrtToStrm_TS24008Msg_AuthenticationResponse (pctxt, "obj_AuthenticationResponse", pvalue->data.u.obj_AuthenticationResponse);
         break;
      }
      /* obj_AuthenticationFailure */
      case 4:
      {
         asn1PrtToStrm_TS24008Msg_AuthenticationFailure (pctxt, "obj_AuthenticationFailure", pvalue->data.u.obj_AuthenticationFailure);
         break;
      }
      /* obj_CMReestabRequest */
      case 5:
      {
         asn1PrtToStrm_TS24008Msg_CMReestabRequest (pctxt, "obj_CMReestabRequest", pvalue->data.u.obj_CMReestabRequest);
         break;
      }
      /* obj_CMServiceAccept */
      case 6:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_CMServiceAccept");
         break;
      }
      /* obj_CMServicePrompt */
      case 7:
      {
         asn1PrtToStrm_TS24008Msg_CMServicePrompt (pctxt, "obj_CMServicePrompt", pvalue->data.u.obj_CMServicePrompt);
         break;
      }
      /* obj_CMServiceReject */
      case 8:
      {
         asn1PrtToStrm_TS24008Msg_CMServiceReject (pctxt, "obj_CMServiceReject", pvalue->data.u.obj_CMServiceReject);
         break;
      }
      /* obj_CMServiceAbort */
      case 9:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_CMServiceAbort");
         break;
      }
      /* obj_Abort */
      case 10:
      {
         asn1PrtToStrm_TS24008Msg_Abort (pctxt, "obj_Abort", pvalue->data.u.obj_Abort);
         break;
      }
      /* obj_CMServiceRequest */
      case 11:
      {
         asn1PrtToStrm_TS24008Msg_CMServiceRequest (pctxt, "obj_CMServiceRequest", pvalue->data.u.obj_CMServiceRequest);
         break;
      }
      /* obj_IdentityRequest */
      case 12:
      {
         asn1PrtToStrm_TS24008Msg_IdentityRequest (pctxt, "obj_IdentityRequest", pvalue->data.u.obj_IdentityRequest);
         break;
      }
      /* obj_IdentityResponse */
      case 13:
      {
         asn1PrtToStrm_TS24008Msg_IdentityResponse (pctxt, "obj_IdentityResponse", pvalue->data.u.obj_IdentityResponse);
         break;
      }
      /* obj_IMSIDetachInd */
      case 14:
      {
         asn1PrtToStrm_TS24008Msg_IMSIDetachInd (pctxt, "obj_IMSIDetachInd", pvalue->data.u.obj_IMSIDetachInd);
         break;
      }
      /* obj_LocUpdatingAccept */
      case 15:
      {
         asn1PrtToStrm_TS24008Msg_LocUpdatingAccept (pctxt, "obj_LocUpdatingAccept", pvalue->data.u.obj_LocUpdatingAccept);
         break;
      }
      /* obj_LocUpdatingReject */
      case 16:
      {
         asn1PrtToStrm_TS24008Msg_LocUpdatingReject (pctxt, "obj_LocUpdatingReject", pvalue->data.u.obj_LocUpdatingReject);
         break;
      }
      /* obj_LocUpdatingRequest */
      case 17:
      {
         asn1PrtToStrm_TS24008Msg_LocUpdatingRequest (pctxt, "obj_LocUpdatingRequest", pvalue->data.u.obj_LocUpdatingRequest);
         break;
      }
      /* obj_MMInformation */
      case 18:
      {
         asn1PrtToStrm_TS24008Msg_MMInformation (pctxt, "obj_MMInformation", pvalue->data.u.obj_MMInformation);
         break;
      }
      /* obj_MMStatus */
      case 19:
      {
         asn1PrtToStrm_TS24008Msg_MMStatus (pctxt, "obj_MMStatus", pvalue->data.u.obj_MMStatus);
         break;
      }
      /* obj_TMSIReallocCmd */
      case 20:
      {
         asn1PrtToStrm_TS24008Msg_TMSIReallocCmd (pctxt, "obj_TMSIReallocCmd", pvalue->data.u.obj_TMSIReallocCmd);
         break;
      }
      /* obj_TMSIReallocCmplt */
      case 21:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_TMSIReallocCmplt");
         break;
      }
      /* obj_MMNull */
      case 22:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_MMNull");
         break;
      }
      /* obj_Alerting */
      case 23:
      {
         asn1PrtToStrm_TS24008Msg_Alerting (pctxt, "obj_Alerting", pvalue->data.u.obj_Alerting);
         break;
      }
      /* obj_CallConfirmed */
      case 24:
      {
         asn1PrtToStrm_TS24008Msg_CallConfirmed (pctxt, "obj_CallConfirmed", pvalue->data.u.obj_CallConfirmed);
         break;
      }
      /* obj_CallProceeding */
      case 25:
      {
         asn1PrtToStrm_TS24008Msg_CallProceeding (pctxt, "obj_CallProceeding", pvalue->data.u.obj_CallProceeding);
         break;
      }
      /* obj_CongestionControl */
      case 26:
      {
         asn1PrtToStrm_TS24008Msg_CongestionControl (pctxt, "obj_CongestionControl", pvalue->data.u.obj_CongestionControl);
         break;
      }
      /* obj_Connect */
      case 27:
      {
         asn1PrtToStrm_TS24008Msg_Connect (pctxt, "obj_Connect", pvalue->data.u.obj_Connect);
         break;
      }
      /* obj_ConnectAck */
      case 28:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_ConnectAck");
         break;
      }
      /* obj_Disconnect */
      case 29:
      {
         asn1PrtToStrm_TS24008Msg_Disconnect (pctxt, "obj_Disconnect", pvalue->data.u.obj_Disconnect);
         break;
      }
      /* obj_EmergencySetup */
      case 30:
      {
         asn1PrtToStrm_TS24008Msg_EmergencySetup (pctxt, "obj_EmergencySetup", pvalue->data.u.obj_EmergencySetup);
         break;
      }
      /* obj_FacilityMsg */
      case 31:
      {
         asn1PrtToStrm_TS24008Msg_FacilityMsg (pctxt, "obj_FacilityMsg", pvalue->data.u.obj_FacilityMsg);
         break;
      }
      /* obj_Hold */
      case 32:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_Hold");
         break;
      }
      /* obj_HoldAck */
      case 33:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_HoldAck");
         break;
      }
      /* obj_HoldReject */
      case 34:
      {
         asn1PrtToStrm_TS24008IE_Cause (pctxt, "obj_HoldReject", pvalue->data.u.obj_HoldReject);
         break;
      }
      /* obj_Modify */
      case 35:
      {
         asn1PrtToStrm_TS24008Msg_Modify (pctxt, "obj_Modify", pvalue->data.u.obj_Modify);
         break;
      }
      /* obj_ModifyComplete */
      case 36:
      {
         asn1PrtToStrm_TS24008Msg_ModifyComplete (pctxt, "obj_ModifyComplete", pvalue->data.u.obj_ModifyComplete);
         break;
      }
      /* obj_ModifyReject */
      case 37:
      {
         asn1PrtToStrm_TS24008Msg_ModifyReject (pctxt, "obj_ModifyReject", pvalue->data.u.obj_ModifyReject);
         break;
      }
      /* obj_Notify */
      case 38:
      {
         asn1PrtToStrm_TS24008IE_NotificationIndicator (pctxt, "obj_Notify", pvalue->data.u.obj_Notify);
         break;
      }
      /* obj_Progress */
      case 39:
      {
         asn1PrtToStrm_TS24008Msg_Progress (pctxt, "obj_Progress", pvalue->data.u.obj_Progress);
         break;
      }
      /* obj_CC_Establishment */
      case 40:
      {
         asn1PrtToStrm_TS24008IE_Setup_Container (pctxt, "obj_CC_Establishment", pvalue->data.u.obj_CC_Establishment);
         break;
      }
      /* obj_CC_EstablishmentConfirmed */
      case 41:
      {
         asn1PrtToStrm_TS24008Msg_CC_EstablishmentConfirmed (pctxt, "obj_CC_EstablishmentConfirmed", pvalue->data.u.obj_CC_EstablishmentConfirmed);
         break;
      }
      /* obj_Release */
      case 42:
      {
         asn1PrtToStrm_TS24008Msg_Release (pctxt, "obj_Release", pvalue->data.u.obj_Release);
         break;
      }
      /* obj_Recall */
      case 43:
      {
         asn1PrtToStrm_TS24008Msg_Recall (pctxt, "obj_Recall", pvalue->data.u.obj_Recall);
         break;
      }
      /* obj_ReleaseComplete */
      case 44:
      {
         asn1PrtToStrm_TS24008Msg_ReleaseComplete (pctxt, "obj_ReleaseComplete", pvalue->data.u.obj_ReleaseComplete);
         break;
      }
      /* obj_Retrieve */
      case 45:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_Retrieve");
         break;
      }
      /* obj_RetrieveAck */
      case 46:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_RetrieveAck");
         break;
      }
      /* obj_RetrieveReject */
      case 47:
      {
         asn1PrtToStrm_TS24008IE_Cause (pctxt, "obj_RetrieveReject", pvalue->data.u.obj_RetrieveReject);
         break;
      }
      /* obj_Setup */
      case 48:
      {
         asn1PrtToStrm_TS24008Msg_Setup (pctxt, "obj_Setup", pvalue->data.u.obj_Setup);
         break;
      }
      /* obj_StartCC */
      case 49:
      {
         asn1PrtToStrm_TS24008Msg_StartCC (pctxt, "obj_StartCC", pvalue->data.u.obj_StartCC);
         break;
      }
      /* obj_StartDTMF */
      case 50:
      {
         asn1PrtToStrm_TS24008Msg_StartDTMF (pctxt, "obj_StartDTMF", pvalue->data.u.obj_StartDTMF);
         break;
      }
      /* obj_StartDTMFAck */
      case 51:
      {
         asn1PrtToStrm_TS24008Msg_StartDTMFAck (pctxt, "obj_StartDTMFAck", pvalue->data.u.obj_StartDTMFAck);
         break;
      }
      /* obj_StartDTMFReject */
      case 52:
      {
         asn1PrtToStrm_TS24008IE_Cause (pctxt, "obj_StartDTMFReject", pvalue->data.u.obj_StartDTMFReject);
         break;
      }
      /* obj_Status */
      case 53:
      {
         asn1PrtToStrm_TS24008Msg_Status (pctxt, "obj_Status", pvalue->data.u.obj_Status);
         break;
      }
      /* obj_StatusEnquiry */
      case 54:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_StatusEnquiry");
         break;
      }
      /* obj_StopDTMF */
      case 55:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_StopDTMF");
         break;
      }
      /* obj_StopDTMFAck */
      case 56:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_StopDTMFAck");
         break;
      }
      /* obj_UserInfo */
      case 57:
      {
         asn1PrtToStrm_TS24008Msg_UserInfo (pctxt, "obj_UserInfo", pvalue->data.u.obj_UserInfo);
         break;
      }
      /* obj_AttachRequest */
      case 58:
      {
         asn1PrtToStrm_TS24008Msg_AttachRequest (pctxt, "obj_AttachRequest", pvalue->data.u.obj_AttachRequest);
         break;
      }
      /* obj_AttachAccept */
      case 59:
      {
         asn1PrtToStrm_TS24008Msg_AttachAccept (pctxt, "obj_AttachAccept", pvalue->data.u.obj_AttachAccept);
         break;
      }
      /* obj_AttachComplete */
      case 60:
      {
         asn1PrtToStrm_TS24008Msg_AttachComplete (pctxt, "obj_AttachComplete", pvalue->data.u.obj_AttachComplete);
         break;
      }
      /* obj_AttachReject */
      case 61:
      {
         asn1PrtToStrm_TS24008Msg_AttachReject (pctxt, "obj_AttachReject", pvalue->data.u.obj_AttachReject);
         break;
      }
      /* obj_DetachRequest */
      case 62:
      {
         asn1PrtToStrm_TS24008Msg_DetachRequest (pctxt, "obj_DetachRequest", pvalue->data.u.obj_DetachRequest);
         break;
      }
      /* obj_DetachAccept */
      case 63:
      {
         asn1PrtToStrm_TS24008Msg_DetachAccept (pctxt, "obj_DetachAccept", pvalue->data.u.obj_DetachAccept);
         break;
      }
      /* obj_P_TMSIReallocCmd */
      case 64:
      {
         asn1PrtToStrm_TS24008Msg_P_TMSIReallocCmd (pctxt, "obj_P_TMSIReallocCmd", pvalue->data.u.obj_P_TMSIReallocCmd);
         break;
      }
      /* obj_P_TMSIReallocCmplt */
      case 65:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_P_TMSIReallocCmplt");
         break;
      }
      /* obj_AuthAndCiphRequest */
      case 66:
      {
         asn1PrtToStrm_TS24008Msg_AuthAndCiphRequest (pctxt, "obj_AuthAndCiphRequest", pvalue->data.u.obj_AuthAndCiphRequest);
         break;
      }
      /* obj_AuthAndCiphResponse */
      case 67:
      {
         asn1PrtToStrm_TS24008Msg_AuthAndCiphResponse (pctxt, "obj_AuthAndCiphResponse", pvalue->data.u.obj_AuthAndCiphResponse);
         break;
      }
      /* obj_AuthAndCiphFailure */
      case 68:
      {
         asn1PrtToStrm_TS24008Msg_AuthAndCiphFailure (pctxt, "obj_AuthAndCiphFailure", pvalue->data.u.obj_AuthAndCiphFailure);
         break;
      }
      /* obj_AuthAndCiphReject */
      case 69:
      {
         rtPrintToStreamIndent (pctxt);
         rtxPrintToStreamNull (pctxt, "obj_AuthAndCiphReject");
         break;
      }
      /* obj_GMMIdentityRequest */
      case 70:
      {
         asn1PrtToStrm_TS24008Msg_GMMIdentityRequest (pctxt, "obj_GMMIdentityRequest", pvalue->data.u.obj_GMMIdentityRequest);
         break;
      }
      /* obj_GMMIdentityResponse */
      case 71:
      {
         asn1PrtToStrm_TS24008Msg_GMMIdentityResponse (pctxt, "obj_GMMIdentityResponse", pvalue->data.u.obj_GMMIdentityResponse);
         break;
      }
      /* obj_RoutingAreaUpdateRequest */
      case 72:
      {
         asn1PrtToStrm_TS24008Msg_RoutingAreaUpdateRequest (pctxt, "obj_RoutingAreaUpdateRequest", pvalue->data.u.obj_RoutingAreaUpdateRequest);
         break;
      }
      /* obj_RoutingAreaUpdateAccept */
      case 73:
      {
         asn1PrtToStrm_TS24008Msg_RoutingAreaUpdateAccept (pctxt, "obj_RoutingAreaUpdateAccept", pvalue->data.u.obj_RoutingAreaUpdateAccept);
         break;
      }
      /* obj_RoutingAreaUpdateComplete */
      case 74:
      {
         asn1PrtToStrm_TS24008Msg_RoutingAreaUpdateComplete (pctxt, "obj_RoutingAreaUpdateComplete", pvalue->data.u.obj_RoutingAreaUpdateComplete);
         break;
      }
      /* obj_RoutingAreaUpdateReject */
      case 75:
      {
         asn1PrtToStrm_TS24008Msg_RoutingAreaUpdateReject (pctxt, "obj_RoutingAreaUpdateReject", pvalue->data.u.obj_RoutingAreaUpdateReject);
         break;
      }
      /* obj_GMMStatus */
      case 76:
      {
         asn1PrtToStrm_TS24008IE_GMMCauseValue (pctxt, "obj_GMMStatus", &pvalue->data.u.obj_GMMStatus);
         break;
      }
      /* obj_GMMInformation */
      case 77:
      {
         asn1PrtToStrm_TS24008Msg_GMMInformation (pctxt, "obj_GMMInformation", pvalue->data.u.obj_GMMInformation);
         break;
      }
      /* obj_ServiceRequest */
      case 78:
      {
         asn1PrtToStrm_TS24008Msg_ServiceRequest (pctxt, "obj_ServiceRequest", pvalue->data.u.obj_ServiceRequest);
         break;
      }
      /* obj_ServiceAccept */
      case 79:
      {
         asn1PrtToStrm_TS24008Msg_ServiceAccept (pctxt, "obj_ServiceAccept", pvalue->data.u.obj_ServiceAccept);
         break;
      }
      /* obj_ServiceReject */
      case 80:
      {
         asn1PrtToStrm_TS24008Msg_ServiceReject (pctxt, "obj_ServiceReject", pvalue->data.u.obj_ServiceReject);
         break;
      }
      /* obj_ActivatePDPCtxtReq */
      case 81:
      {
         asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtReq (pctxt, "obj_ActivatePDPCtxtReq", pvalue->data.u.obj_ActivatePDPCtxtReq);
         break;
      }
      /* obj_ActivatePDPCtxtAccept */
      case 82:
      {
         asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtAccept (pctxt, "obj_ActivatePDPCtxtAccept", pvalue->data.u.obj_ActivatePDPCtxtAccept);
         break;
      }
      /* obj_ActivatePDPCtxtReject */
      case 83:
      {
         asn1PrtToStrm_TS24008Msg_ActivatePDPCtxtReject (pctxt, "obj_ActivatePDPCtxtReject", pvalue->data.u.obj_ActivatePDPCtxtReject);
         break;
      }
      /* obj_ActivateSecondaryPDPCtxtRqst */
      case 84:
      {
         asn1PrtToStrm_TS24008Msg_ActivateSecondaryPDPCtxtRqst (pctxt, "obj_ActivateSecondaryPDPCtxtRqst", pvalue->data.u.obj_ActivateSecondaryPDPCtxtRqst);
         break;
      }
      /* obj_ActivateSecondaryPDPCtxtAcc */
      case 85:
      {
         asn1PrtToStrm_TS24008Msg_ActivateSecondaryPDPCtxtAcc (pctxt, "obj_ActivateSecondaryPDPCtxtAcc", pvalue->data.u.obj_ActivateSecondaryPDPCtxtAcc);
         break;
      }
      /* obj_ActivateSecondaryPDPCtxtRej */
      case 86:
      {
         asn1PrtToStrm_TS24008Msg_ActivateSecondaryPDPCtxtRej (pctxt, "obj_ActivateSecondaryPDPCtxtRej", pvalue->data.u.obj_ActivateSecondaryPDPCtxtRej);
         break;
      }
      /* obj_RequestPDPCtxtAct */
      case 87:
      {
         asn1PrtToStrm_TS24008Msg_RequestPDPCtxtAct (pctxt, "obj_RequestPDPCtxtAct", pvalue->data.u.obj_RequestPDPCtxtAct);
         break;
      }
      /* obj_RequestPDPCtxtActRej */
      case 88:
      {
         asn1PrtToStrm_TS24008Msg_RequestPDPCtxtActRej (pctxt, "obj_RequestPDPCtxtActRej", pvalue->data.u.obj_RequestPDPCtxtActRej);
         break;
      }
      /* obj_ModifyPDPCtxtRqstNetToMS */
      case 89:
      {
         asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtRqstNetToMS (pctxt, "obj_ModifyPDPCtxtRqstNetToMS", pvalue->data.u.obj_ModifyPDPCtxtRqstNetToMS);
         break;
      }
      /* obj_ModifyPDPCtxtRqstMSToNet */
      case 90:
      {
         asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtRqstMSToNet (pctxt, "obj_ModifyPDPCtxtRqstMSToNet", pvalue->data.u.obj_ModifyPDPCtxtRqstMSToNet);
         break;
      }
      /* obj_ModifyPDPCtxtAccMSToNet */
      case 91:
      {
         asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtAccMSToNet (pctxt, "obj_ModifyPDPCtxtAccMSToNet", pvalue->data.u.obj_ModifyPDPCtxtAccMSToNet);
         break;
      }
      /* obj_ModifyPDPCtxtAccNetToMS */
      case 92:
      {
         asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtAccNetToMS (pctxt, "obj_ModifyPDPCtxtAccNetToMS", pvalue->data.u.obj_ModifyPDPCtxtAccNetToMS);
         break;
      }
      /* obj_ModifyPDPCtxtRej */
      case 93:
      {
         asn1PrtToStrm_TS24008Msg_ModifyPDPCtxtRej (pctxt, "obj_ModifyPDPCtxtRej", pvalue->data.u.obj_ModifyPDPCtxtRej);
         break;
      }
      /* obj_DeactivatePDPCtxtReq */
      case 94:
      {
         asn1PrtToStrm_TS24008Msg_DeactivatePDPCtxtReq (pctxt, "obj_DeactivatePDPCtxtReq", pvalue->data.u.obj_DeactivatePDPCtxtReq);
         break;
      }
      /* obj_DeactivatePDPCtxtAcc */
      case 95:
      {
         asn1PrtToStrm_TS24008Msg_DeactivatePDPCtxtAcc (pctxt, "obj_DeactivatePDPCtxtAcc", pvalue->data.u.obj_DeactivatePDPCtxtAcc);
         break;
      }
      /* obj_RqstSecondaryPDPCtxtAct */
      case 96:
      {
         asn1PrtToStrm_TS24008Msg_RqstSecondaryPDPCtxtAct (pctxt, "obj_RqstSecondaryPDPCtxtAct", pvalue->data.u.obj_RqstSecondaryPDPCtxtAct);
         break;
      }
      /* obj_RqstSecondaryPDPCtxtActRej */
      case 97:
      {
         asn1PrtToStrm_TS24008Msg_RqstSecondaryPDPCtxtActRej (pctxt, "obj_RqstSecondaryPDPCtxtActRej", pvalue->data.u.obj_RqstSecondaryPDPCtxtActRej);
         break;
      }
      /* obj_SMStatus */
      case 98:
      {
         asn1PrtToStrm_TS24008IE_SMCauseValue (pctxt, "obj_SMStatus", &pvalue->data.u.obj_SMStatus);
         break;
      }
      /* obj_ActivateMBMSCtxtReq */
      case 99:
      {
         asn1PrtToStrm_TS24008Msg_ActivateMBMSCtxtReq (pctxt, "obj_ActivateMBMSCtxtReq", pvalue->data.u.obj_ActivateMBMSCtxtReq);
         break;
      }
      /* obj_ActivateMBMSCtxtAcc */
      case 100:
      {
         asn1PrtToStrm_TS24008Msg_ActivateMBMSCtxtAcc (pctxt, "obj_ActivateMBMSCtxtAcc", pvalue->data.u.obj_ActivateMBMSCtxtAcc);
         break;
      }
      /* obj_ActivateMBMSCtxtRej */
      case 101:
      {
         asn1PrtToStrm_TS24008Msg_ActivateMBMSCtxtRej (pctxt, "obj_ActivateMBMSCtxtRej", pvalue->data.u.obj_ActivateMBMSCtxtRej);
         break;
      }
      /* obj_RequestMBMSCtxtAct */
      case 102:
      {
         asn1PrtToStrm_TS24008Msg_RequestMBMSCtxtAct (pctxt, "obj_RequestMBMSCtxtAct", pvalue->data.u.obj_RequestMBMSCtxtAct);
         break;
      }
      /* obj_RequestMBMSCtxtActRej */
      case 103:
      {
         asn1PrtToStrm_TS24008Msg_RequestMBMSCtxtActRej (pctxt, "obj_RequestMBMSCtxtActRej", pvalue->data.u.obj_RequestMBMSCtxtActRej);
         break;
      }
      default:;
   }

   rtPrintToStreamCloseBrace (pctxt);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

