/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.2-pre4, Date: 04-Apr-2013.
 */
#ifndef TS24301MSGS_H
#define TS24301MSGS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtxsrc/rtxContext.h"
#include "rtsrc/asn1type.h"

#include "TS24007L3.h"
#include "TS24008IES.h"
#include "TS24301IES.h"

/**
 * Header file for ASN.1 module TS24301Msgs
 */
typedef enum {
   T_TS24301Msgs_TS24301_IE_OBJECTSET_UNDEF_,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AttachAccept,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AttachComplete,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AttachReject,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AttachRequest,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AuthFailure,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AuthReject,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AuthRequest,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_AuthResponse,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_CSServiceNotif,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DetachAccept,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DetachRequest,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DLNASTransport,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_EMMInformation,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_EMMStatus,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ExtServiceReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_GUTIReallocCmd,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_GUTIReallocCmplt,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_IdentReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_IdentResp,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_SecModeCmd,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_SecModeCmplt,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_SecModeReject,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ServiceReject,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_TrkAreaUpdAccept,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_TrkAreaUpdCmplt,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_TrkAreaUpdReject,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_TrkAreaUpdRequest,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ULNASTransport,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ULGenNASTransport,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DLGenNASTransport,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDedEPSBearerCtxtAcc,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDedEPSBearerCtxtRej,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDedEPSBearerCtxtReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDfltEPSBearerCtxtAcc,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDfltEPSBearerCtxtRej,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ActvDfltEPSBearerCtxtReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_BearerResAllocRej,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_BearerResAllocReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_BearerResModRej,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_BearerResModReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DeactEPSBearerCtxtAcc,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_DeactEPSBearerCtxtReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ESMInfoReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ESMInfoResp,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ESMStatus,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ModEPSBearerCtxtAcc,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ModEPSBearerCtxtRej,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_ModEPSBearerCtxtReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_PDNConnectRej,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_PDNConnectReq,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_PDNDisconnRej,
   T_TS24301Msgs_TS24301_IE_OBJECTSET_obj_PDNDisconnReq
} TS24301_IE_OBJECTSET_TVALUE;

/**************************************************************/
/*                                                            */
/*  AttachComplete                                            */
/*                                                            */
/**************************************************************/
/*
AttachComplete ::= ESMMessageContainer
*/
typedef TS24301IE_ESMMessageContainer TS24301Msg_AttachComplete;

EXTERN int NASEnc_TS24301Msg_AttachComplete (OSCTXT* pctxt
   , TS24301Msg_AttachComplete value);

EXTERN int NASDec_TS24301Msg_AttachComplete (OSCTXT* pctxt
   , TS24301Msg_AttachComplete* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_AttachComplete (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AttachComplete* pvalue);

EXTERN void asn1Init_TS24301Msg_AttachComplete (TS24301Msg_AttachComplete* pvalue);

/**************************************************************/
/*                                                            */
/*  AuthResponse                                              */
/*                                                            */
/**************************************************************/
/*
AuthResponse ::= AuthRespParam
*/
typedef TS24301IE_AuthRespParam TS24301Msg_AuthResponse;

EXTERN int NASEnc_TS24301Msg_AuthResponse (OSCTXT* pctxt
   , TS24301Msg_AuthResponse* pvalue);

EXTERN int NASDec_TS24301Msg_AuthResponse (OSCTXT* pctxt
   , TS24301Msg_AuthResponse* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_AuthResponse (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AuthResponse* pvalue);

EXTERN void asn1Init_TS24301Msg_AuthResponse (TS24301Msg_AuthResponse* pvalue);

/**************************************************************/
/*                                                            */
/*  DLNASTransport                                            */
/*                                                            */
/**************************************************************/
/*
DLNASTransport ::= NASMessageContainer
*/
typedef TS24301IE_NASMessageContainer TS24301Msg_DLNASTransport;

EXTERN int NASEnc_TS24301Msg_DLNASTransport (OSCTXT* pctxt
   , TS24301Msg_DLNASTransport* pvalue);

EXTERN int NASDec_TS24301Msg_DLNASTransport (OSCTXT* pctxt
   , TS24301Msg_DLNASTransport* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_DLNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DLNASTransport* pvalue);

EXTERN void asn1Init_TS24301Msg_DLNASTransport (TS24301Msg_DLNASTransport* pvalue);

/**************************************************************/
/*                                                            */
/*  EMMStatus                                                 */
/*                                                            */
/**************************************************************/
/*
EMMStatus ::= EMMCause
*/
typedef TS24301IE_EMMCause TS24301Msg_EMMStatus;

EXTERN int NASEnc_TS24301Msg_EMMStatus (OSCTXT* pctxt
   , TS24301Msg_EMMStatus value);

EXTERN int NASDec_TS24301Msg_EMMStatus (OSCTXT* pctxt
   , TS24301Msg_EMMStatus* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_EMMStatus (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_EMMStatus* pvalue);

/**************************************************************/
/*                                                            */
/*  IdentResp                                                 */
/*                                                            */
/**************************************************************/
/*
IdentResp ::= MobileIdentity
*/
typedef TS24008IE_MobileIdentity TS24301Msg_IdentResp;

EXTERN int NASEnc_TS24301Msg_IdentResp (OSCTXT* pctxt
   , TS24301Msg_IdentResp* pvalue);

EXTERN int NASDec_TS24301Msg_IdentResp (OSCTXT* pctxt
   , TS24301Msg_IdentResp* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_IdentResp (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_IdentResp* pvalue);

EXTERN void asn1Init_TS24301Msg_IdentResp (TS24301Msg_IdentResp* pvalue);

/**************************************************************/
/*                                                            */
/*  SecModeReject                                             */
/*                                                            */
/**************************************************************/
/*
SecModeReject ::= EMMCause
*/
typedef TS24301IE_EMMCause TS24301Msg_SecModeReject;

EXTERN int NASEnc_TS24301Msg_SecModeReject (OSCTXT* pctxt
   , TS24301Msg_SecModeReject value);

EXTERN int NASDec_TS24301Msg_SecModeReject (OSCTXT* pctxt
   , TS24301Msg_SecModeReject* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_SecModeReject (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_SecModeReject* pvalue);

/**************************************************************/
/*                                                            */
/*  ULNASTransport                                            */
/*                                                            */
/**************************************************************/
/*
ULNASTransport ::= NASMessageContainer
*/
typedef TS24301IE_NASMessageContainer TS24301Msg_ULNASTransport;

EXTERN int NASEnc_TS24301Msg_ULNASTransport (OSCTXT* pctxt
   , TS24301Msg_ULNASTransport* pvalue);

EXTERN int NASDec_TS24301Msg_ULNASTransport (OSCTXT* pctxt
   , TS24301Msg_ULNASTransport* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ULNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ULNASTransport* pvalue);

EXTERN void asn1Init_TS24301Msg_ULNASTransport (TS24301Msg_ULNASTransport* pvalue);

/**************************************************************/
/*                                                            */
/*  GenNASTransport_addnInfo                                  */
/*                                                            */
/**************************************************************/
/*
Type was extracted from 'GenNASTransport'
*/
typedef struct EXTERN TS24301Msg_GenNASTransport_addnInfo {
   OSUINT8 numocts;
   OSOCTET data[253];
} TS24301Msg_GenNASTransport_addnInfo;

EXTERN int NASEnc_TS24301Msg_GenNASTransport_addnInfo (OSCTXT* pctxt
   , TS24301Msg_GenNASTransport_addnInfo* pvalue);

EXTERN int NASDec_TS24301Msg_GenNASTransport_addnInfo (OSCTXT* pctxt
   , TS24301Msg_GenNASTransport_addnInfo* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_GenNASTransport_addnInfo (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_GenNASTransport_addnInfo* pvalue);

EXTERN void asn1Init_TS24301Msg_GenNASTransport_addnInfo (
   TS24301Msg_GenNASTransport_addnInfo* pvalue);

/**************************************************************/
/*                                                            */
/*  GenNASTransport                                           */
/*                                                            */
/**************************************************************/
/*
GenNASTransport ::= SEQUENCE {
   genMsgContainerType [0] GenMsgContainerType,
   genMsgContainer [1] GenMessageContainer,
   addnInfo [2] OCTET STRING (SIZE (0..253)) OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_GenNASTransport {
   struct {
      unsigned addnInfoPresent : 1;
   } m;
   TS24301IE_GenMsgContainerType genMsgContainerType;
   TS24301IE_GenMessageContainer genMsgContainer;
   TS24301Msg_GenNASTransport_addnInfo addnInfo;
} TS24301Msg_GenNASTransport;

EXTERN int NASEnc_TS24301Msg_GenNASTransport (OSCTXT* pctxt
   , TS24301Msg_GenNASTransport* pvalue);

EXTERN int NASDec_TS24301Msg_GenNASTransport (OSCTXT* pctxt
   , TS24301Msg_GenNASTransport* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_GenNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_GenNASTransport* pvalue);

EXTERN void asn1Init_TS24301Msg_GenNASTransport (TS24301Msg_GenNASTransport* pvalue);

/**************************************************************/
/*                                                            */
/*  DLGenNASTransport                                         */
/*                                                            */
/**************************************************************/
/*
DLGenNASTransport ::= GenNASTransport
*/
typedef TS24301Msg_GenNASTransport TS24301Msg_DLGenNASTransport;

EXTERN int NASEnc_TS24301Msg_DLGenNASTransport (OSCTXT* pctxt
   , TS24301Msg_DLGenNASTransport* pvalue);

EXTERN int NASDec_TS24301Msg_DLGenNASTransport (OSCTXT* pctxt
   , TS24301Msg_DLGenNASTransport* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_DLGenNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DLGenNASTransport* pvalue);

EXTERN void asn1Init_TS24301Msg_DLGenNASTransport (
   TS24301Msg_DLGenNASTransport* pvalue);

/**************************************************************/
/*                                                            */
/*  ULGenNASTransport                                         */
/*                                                            */
/**************************************************************/
/*
ULGenNASTransport ::= GenNASTransport
*/
typedef TS24301Msg_GenNASTransport TS24301Msg_ULGenNASTransport;

EXTERN int NASEnc_TS24301Msg_ULGenNASTransport (OSCTXT* pctxt
   , TS24301Msg_ULGenNASTransport* pvalue);

EXTERN int NASDec_TS24301Msg_ULGenNASTransport (OSCTXT* pctxt
   , TS24301Msg_ULGenNASTransport* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ULGenNASTransport (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ULGenNASTransport* pvalue);

EXTERN void asn1Init_TS24301Msg_ULGenNASTransport (
   TS24301Msg_ULGenNASTransport* pvalue);

/**************************************************************/
/*                                                            */
/*  ESMStatus                                                 */
/*                                                            */
/**************************************************************/
/*
ESMStatus ::= ESMCause
*/
typedef TS24301IE_ESMCause TS24301Msg_ESMStatus;

EXTERN int NASEnc_TS24301Msg_ESMStatus (OSCTXT* pctxt
   , TS24301Msg_ESMStatus value);

EXTERN int NASDec_TS24301Msg_ESMStatus (OSCTXT* pctxt
   , TS24301Msg_ESMStatus* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ESMStatus (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ESMStatus* pvalue);

/**************************************************************/
/*                                                            */
/*  AttachAccept                                              */
/*                                                            */
/**************************************************************/
/*
AttachAccept ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   result [1] EPSAttachResult,
   t3412Value [2] GPRSTimer,
   taiList [3] TrackingAreaIdentList,
   esmMessageContainer [4] ESMMessageContainer,
   guti [5] EPSMobileIdentity OPTIONAL,
   locAreaIdent [6] LocAreaIdent OPTIONAL,
   msIdentity [7] MobileIdentity OPTIONAL,
   emmCause [8] EMMCause OPTIONAL,
   t3402 [9] GPRSTimer OPTIONAL,
   t3423 [10] GPRSTimer OPTIONAL,
   equivPLMNs [11] PLMNList OPTIONAL,
   emergNumList [12] EmergencyNumberList OPTIONAL,
   epsNetFeatSupp [13] EPSNetworkFeatureSupport OPTIONAL,
   addnUpdateResult [14] AddnUpdateResult OPTIONAL,
   ...,
   [[ 10:
      t3412ExtValue [15] GPRSTimer3 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_AttachAccept {
   struct {
      unsigned gutiPresent : 1;
      unsigned locAreaIdentPresent : 1;
      unsigned msIdentityPresent : 1;
      unsigned emmCausePresent : 1;
      unsigned t3402Present : 1;
      unsigned t3423Present : 1;
      unsigned equivPLMNsPresent : 1;
      unsigned emergNumListPresent : 1;
      unsigned epsNetFeatSuppPresent : 1;
      unsigned addnUpdateResultPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned t3412ExtValuePresent : 1;
   } m;
   OSUINT8 spare;
   TS24301IE_EPSAttachResult result;
   TS24008IE_GPRSTimer t3412Value;
   TS24301IE_TrackingAreaIdentList taiList;
   TS24301IE_ESMMessageContainer esmMessageContainer;
   TS24301IE_EPSMobileIdentity guti;
   TS24008IE_LocAreaIdent locAreaIdent;
   TS24008IE_MobileIdentity msIdentity;
   TS24301IE_EMMCause emmCause;
   TS24008IE_GPRSTimer t3402;
   TS24008IE_GPRSTimer t3423;
   TS24008IE_PLMNList equivPLMNs;
   TS24008IE_EmergencyNumberList emergNumList;
   TS24301IE_EPSNetworkFeatureSupport epsNetFeatSupp;
   TS24301IE_AddnUpdateResult addnUpdateResult;
   TS24008IE_GPRSTimer3 t3412ExtValue;
} TS24301Msg_AttachAccept;

EXTERN int NASEnc_TS24301Msg_AttachAccept (OSCTXT* pctxt
   , TS24301Msg_AttachAccept* pvalue);

EXTERN int NASDec_TS24301Msg_AttachAccept (OSCTXT* pctxt
   , TS24301Msg_AttachAccept* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_AttachAccept (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AttachAccept* pvalue);

EXTERN void asn1Init_TS24301Msg_AttachAccept (TS24301Msg_AttachAccept* pvalue);

/**************************************************************/
/*                                                            */
/*  AttachReject                                              */
/*                                                            */
/**************************************************************/
/*
AttachReject ::= SEQUENCE {
   emmCause [0] EMMCause,
   esmMsgCont [1] ESMMessageContainer OPTIONAL,
   ...,
   [[ 10:
      t3346Value [2] GPRSTimer2 OPTIONAL,
      t3402Value [3] GPRSTimer2 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_AttachReject {
   struct {
      unsigned esmMsgContPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned t3346ValuePresent : 1;
      unsigned t3402ValuePresent : 1;
   } m;
   TS24301IE_EMMCause emmCause;
   TS24301IE_ESMMessageContainer esmMsgCont;
   TS24008IE_GPRSTimer2 t3346Value;
   TS24008IE_GPRSTimer2 t3402Value;
} TS24301Msg_AttachReject;

EXTERN int NASEnc_TS24301Msg_AttachReject (OSCTXT* pctxt
   , TS24301Msg_AttachReject* pvalue);

EXTERN int NASDec_TS24301Msg_AttachReject (OSCTXT* pctxt
   , TS24301Msg_AttachReject* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_AttachReject (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AttachReject* pvalue);

EXTERN void asn1Init_TS24301Msg_AttachReject (TS24301Msg_AttachReject* pvalue);

/**************************************************************/
/*                                                            */
/*  AttachRequest                                             */
/*                                                            */
/**************************************************************/
/*
AttachRequest ::= SEQUENCE {
   nasKeySetIdentifier [0] NASKeySetIdentifier,
   epsAttachType [1] EPSAttachType,
   oldGUTIOrIMSI [2] EPSMobileIdentity,
   ueNetworkCapability [3] UENetworkCapability,
   esmMessageContainer [4] ESMMessageContainer,
   oldP-TMSISignature [5] P-TMSISignature OPTIONAL,
   additionalGUTI [6] EPSMobileIdentity OPTIONAL,
   lastVisitedRegisteredTAI [7] TrackingAreaIdent OPTIONAL,
   drxParameter [8] DRXParameter OPTIONAL,
   msNetworkCapability [9] MSNetworkCapability OPTIONAL,
   oldLocAreaIdent [10] LocAreaIdent OPTIONAL,
   tmsiStatus [11] TMSIStatus OPTIONAL,
   mobileStationClassmark2 [12] MobileStationClassmark2 OPTIONAL,
   mobileStationClassmark3 [13] MobileStationClassmark3 OPTIONAL,
   supportedCodecs [14] SupportedCodecList OPTIONAL,
   addnUpdateType [15] AddnUpdateType OPTIONAL,
   ...,
   [[ 9:
      voiceDomainPref [16] VoiceDomainPref OPTIONAL
   ]],
   [[ 10:
      deviceProperties [17] DeviceProperties OPTIONAL,
      oldGUTIType [18] GUTIType OPTIONAL,
      msNetFeatureSupport [19] MSNetFeatureSupport OPTIONAL
   ]],
   [[ 11:
      tmsiBasedNRIContainer [20] NetResourceIdentContainer OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_AttachRequest {
   struct {
      unsigned oldP_TMSISignaturePresent : 1;
      unsigned additionalGUTIPresent : 1;
      unsigned lastVisitedRegisteredTAIPresent : 1;
      unsigned drxParameterPresent : 1;
      unsigned msNetworkCapabilityPresent : 1;
      unsigned oldLocAreaIdentPresent : 1;
      unsigned tmsiStatusPresent : 1;
      unsigned mobileStationClassmark2Present : 1;
      unsigned mobileStationClassmark3Present : 1;
      unsigned supportedCodecsPresent : 1;
      unsigned addnUpdateTypePresent : 1;
      unsigned _v9ExtPresent : 1;
      unsigned voiceDomainPrefPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned devicePropertiesPresent : 1;
      unsigned oldGUTITypePresent : 1;
      unsigned msNetFeatureSupportPresent : 1;
      unsigned _v11ExtPresent : 1;
      unsigned tmsiBasedNRIContainerPresent : 1;
   } m;
   TS24301IE_NASKeySetIdentifier nasKeySetIdentifier;
   TS24301IE_EPSAttachType epsAttachType;
   TS24301IE_EPSMobileIdentity oldGUTIOrIMSI;
   TS24301IE_UENetworkCapability ueNetworkCapability;
   TS24301IE_ESMMessageContainer esmMessageContainer;
   TS24008IE_P_TMSISignature oldP_TMSISignature;
   TS24301IE_EPSMobileIdentity additionalGUTI;
   TS24301IE_TrackingAreaIdent lastVisitedRegisteredTAI;
   TS24008IE_DRXParameter drxParameter;
   TS24008IE_MSNetworkCapability msNetworkCapability;
   TS24008IE_LocAreaIdent oldLocAreaIdent;
   TS24008IE_TMSIStatus tmsiStatus;
   TS24008IE_MobileStationClassmark2 mobileStationClassmark2;
   TS24008IE_MobileStationClassmark3 mobileStationClassmark3;
   TS24008IE_SupportedCodecList supportedCodecs;
   TS24301IE_AddnUpdateType addnUpdateType;
   TS24008IE_VoiceDomainPref voiceDomainPref;
   TS24008IE_DeviceProperties deviceProperties;
   TS24301IE_GUTIType oldGUTIType;
   TS24008IE_MSNetFeatureSupport msNetFeatureSupport;
   TS24008IE_NetResourceIdentContainer tmsiBasedNRIContainer;
} TS24301Msg_AttachRequest;

EXTERN int NASEnc_TS24301Msg_AttachRequest (OSCTXT* pctxt
   , TS24301Msg_AttachRequest* pvalue);

EXTERN int NASDec_TS24301Msg_AttachRequest (OSCTXT* pctxt
   , TS24301Msg_AttachRequest* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_AttachRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AttachRequest* pvalue);

EXTERN void asn1Init_TS24301Msg_AttachRequest (TS24301Msg_AttachRequest* pvalue);

/**************************************************************/
/*                                                            */
/*  AuthFailure                                               */
/*                                                            */
/**************************************************************/
/*
AuthFailure ::= SEQUENCE {
   emmCause [0] EMMCause,
   authFailureParam [1] AuthFailureParam OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_AuthFailure {
   struct {
      unsigned authFailureParamPresent : 1;
   } m;
   TS24301IE_EMMCause emmCause;
   TS24008IE_AuthFailureParam authFailureParam;
} TS24301Msg_AuthFailure;

EXTERN int NASEnc_TS24301Msg_AuthFailure (OSCTXT* pctxt
   , TS24301Msg_AuthFailure* pvalue);

EXTERN int NASDec_TS24301Msg_AuthFailure (OSCTXT* pctxt
   , TS24301Msg_AuthFailure* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_AuthFailure (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AuthFailure* pvalue);

EXTERN void asn1Init_TS24301Msg_AuthFailure (TS24301Msg_AuthFailure* pvalue);

/**************************************************************/
/*                                                            */
/*  AuthRequest                                               */
/*                                                            */
/**************************************************************/
/*
AuthRequest ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   nasKeySetIdent [1] NASKeySetIdentifier,
   authParamRAND [2] AuthParamRAND,
   authParamAUTN [3] AuthParamAUTN
}
*/
typedef struct EXTERN TS24301Msg_AuthRequest {
   OSUINT8 spare;
   TS24301IE_NASKeySetIdentifier nasKeySetIdent;
   TS24008IE_AuthParamRAND authParamRAND;
   TS24008IE_AuthParamAUTN authParamAUTN;
} TS24301Msg_AuthRequest;

EXTERN int NASEnc_TS24301Msg_AuthRequest (OSCTXT* pctxt
   , TS24301Msg_AuthRequest* pvalue);

EXTERN int NASDec_TS24301Msg_AuthRequest (OSCTXT* pctxt
   , TS24301Msg_AuthRequest* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_AuthRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_AuthRequest* pvalue);

EXTERN void asn1Init_TS24301Msg_AuthRequest (TS24301Msg_AuthRequest* pvalue);

/**************************************************************/
/*                                                            */
/*  CSServiceNotif                                            */
/*                                                            */
/**************************************************************/
/*
CSServiceNotif ::= SEQUENCE {
   pagingIdentity [0] PagingIdentity,
   cli [1] CLI OPTIONAL,
   ssCode [2] SSCode OPTIONAL,
   lcsIndicator [3] LCSIndicator OPTIONAL,
   lcsClientIdentity [4] LCSClientIdentity OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_CSServiceNotif {
   struct {
      unsigned cliPresent : 1;
      unsigned ssCodePresent : 1;
      unsigned lcsIndicatorPresent : 1;
      unsigned lcsClientIdentityPresent : 1;
   } m;
   TS24301IE_PagingIdentity pagingIdentity;
   TS24301IE_CLI cli;
   TS24301IE_SSCode ssCode;
   TS24301IE_LCSIndicator lcsIndicator;
   TS24301IE_LCSClientIdentity lcsClientIdentity;
} TS24301Msg_CSServiceNotif;

EXTERN int NASEnc_TS24301Msg_CSServiceNotif (OSCTXT* pctxt
   , TS24301Msg_CSServiceNotif* pvalue);

EXTERN int NASDec_TS24301Msg_CSServiceNotif (OSCTXT* pctxt
   , TS24301Msg_CSServiceNotif* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_CSServiceNotif (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_CSServiceNotif* pvalue);

EXTERN void asn1Init_TS24301Msg_CSServiceNotif (TS24301Msg_CSServiceNotif* pvalue);

/**************************************************************/
/*                                                            */
/*  DetachRequestUEOrig                                       */
/*                                                            */
/**************************************************************/
/*
DetachRequestUEOrig ::= SEQUENCE {
   nasKeySetIdent [0] NASKeySetIdentifier,
   detachType [1] DetachType,
   gUTIOrIMSI [2] EPSMobileIdentity
}
*/
typedef struct EXTERN TS24301Msg_DetachRequestUEOrig {
   TS24301IE_NASKeySetIdentifier nasKeySetIdent;
   TS24301IE_DetachType detachType;
   TS24301IE_EPSMobileIdentity gUTIOrIMSI;
} TS24301Msg_DetachRequestUEOrig;

EXTERN int NASEnc_TS24301Msg_DetachRequestUEOrig (OSCTXT* pctxt
   , TS24301Msg_DetachRequestUEOrig* pvalue);

EXTERN int NASDec_TS24301Msg_DetachRequestUEOrig (OSCTXT* pctxt
   , TS24301Msg_DetachRequestUEOrig* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_DetachRequestUEOrig (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DetachRequestUEOrig* pvalue);

EXTERN void asn1Init_TS24301Msg_DetachRequestUEOrig (
   TS24301Msg_DetachRequestUEOrig* pvalue);

/**************************************************************/
/*                                                            */
/*  DetachRequestUETerm                                       */
/*                                                            */
/**************************************************************/
/*
DetachRequestUETerm ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   detachType [1] DetachType,
   emmCause [2] EMMCause
}
*/
typedef struct EXTERN TS24301Msg_DetachRequestUETerm {
   OSUINT8 spare;
   TS24301IE_DetachType detachType;
   TS24301IE_EMMCause emmCause;
} TS24301Msg_DetachRequestUETerm;

EXTERN int NASEnc_TS24301Msg_DetachRequestUETerm (OSCTXT* pctxt
   , TS24301Msg_DetachRequestUETerm* pvalue);

EXTERN int NASDec_TS24301Msg_DetachRequestUETerm (OSCTXT* pctxt
   , TS24301Msg_DetachRequestUETerm* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_DetachRequestUETerm (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DetachRequestUETerm* pvalue);

EXTERN void asn1Init_TS24301Msg_DetachRequestUETerm (
   TS24301Msg_DetachRequestUETerm* pvalue);

/**************************************************************/
/*                                                            */
/*  DetachRequest                                             */
/*                                                            */
/**************************************************************/
/*
<cEncFuncFname>TS24301MsgEnc_DetachRequest.c</cEncFuncFname>
<cDecFuncFname>TS24301MsgDec_DetachRequest.c</cDecFuncFname>

DetachRequest ::= CHOICE {
   ueOrig [0] DetachRequestUEOrig,
   ueTerm [1] DetachRequestUETerm
}
*/
typedef struct EXTERN TS24301Msg_DetachRequest {
   enum {
      T_DetachRequest_UNKNOWN_ = 0,
      T_DetachRequest_ueOrig = 1,
      T_DetachRequest_ueTerm = 2
   } t;
   union {
      /* t = 1 */
      TS24301Msg_DetachRequestUEOrig ueOrig;
      /* t = 2 */
      TS24301Msg_DetachRequestUETerm ueTerm;
   } u;
} TS24301Msg_DetachRequest;

EXTERN int NASEnc_TS24301Msg_DetachRequest (OSCTXT* pctxt
   , TS24301Msg_DetachRequest* pvalue);

EXTERN int NASDec_TS24301Msg_DetachRequest (OSCTXT* pctxt
   , TS24301Msg_DetachRequest* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_DetachRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DetachRequest* pvalue);

EXTERN void asn1Init_TS24301Msg_DetachRequest (TS24301Msg_DetachRequest* pvalue);

/**************************************************************/
/*                                                            */
/*  EMMInformation                                            */
/*                                                            */
/**************************************************************/
/*
EMMInformation ::= SEQUENCE {
   fullNameForNetwork [0] NetworkName OPTIONAL,
   shortNameForNetwork [1] NetworkName OPTIONAL,
   localTimeZone [2] TimeZone OPTIONAL,
   univTimeAndLclTimeZone [3] TimeZoneAndTime OPTIONAL,
   networkDaylightSavingTime [4] DaylightSavingTime OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_EMMInformation {
   struct {
      unsigned fullNameForNetworkPresent : 1;
      unsigned shortNameForNetworkPresent : 1;
      unsigned localTimeZonePresent : 1;
      unsigned univTimeAndLclTimeZonePresent : 1;
      unsigned networkDaylightSavingTimePresent : 1;
   } m;
   TS24008IE_NetworkName fullNameForNetwork;
   TS24008IE_NetworkName shortNameForNetwork;
   TS24008IE_TimeZone localTimeZone;
   TS24008IE_TimeZoneAndTime univTimeAndLclTimeZone;
   TS24008IE_DaylightSavingTime networkDaylightSavingTime;
} TS24301Msg_EMMInformation;

EXTERN int NASEnc_TS24301Msg_EMMInformation (OSCTXT* pctxt
   , TS24301Msg_EMMInformation* pvalue);

EXTERN int NASDec_TS24301Msg_EMMInformation (OSCTXT* pctxt
   , TS24301Msg_EMMInformation* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_EMMInformation (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_EMMInformation* pvalue);

EXTERN void asn1Init_TS24301Msg_EMMInformation (TS24301Msg_EMMInformation* pvalue);

/**************************************************************/
/*                                                            */
/*  ExtServiceReq                                             */
/*                                                            */
/**************************************************************/
/*
ExtServiceReq ::= SEQUENCE {
   nasKeySetIdentifier [0] NASKeySetIdentifier,
   serviceType [1] ServiceType,
   m-tmsi [2] MobileIdentity,
   csfbResponse [3] CSFBResponse OPTIONAL,
   ...,
   [[ 9:
      epsBearerContextStatus [4] EPSBearerContextStatus OPTIONAL
   ]],
   [[ 10:
      deviceProperties [5] DeviceProperties OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_ExtServiceReq {
   struct {
      unsigned csfbResponsePresent : 1;
      unsigned _v9ExtPresent : 1;
      unsigned epsBearerContextStatusPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned devicePropertiesPresent : 1;
   } m;
   TS24301IE_NASKeySetIdentifier nasKeySetIdentifier;
   TS24301IE_ServiceType serviceType;
   TS24008IE_MobileIdentity m_tmsi;
   TS24301IE_CSFBResponse csfbResponse;
   TS24301IE_EPSBearerContextStatus epsBearerContextStatus;
   TS24008IE_DeviceProperties deviceProperties;
} TS24301Msg_ExtServiceReq;

EXTERN int NASEnc_TS24301Msg_ExtServiceReq (OSCTXT* pctxt
   , TS24301Msg_ExtServiceReq* pvalue);

EXTERN int NASDec_TS24301Msg_ExtServiceReq (OSCTXT* pctxt
   , TS24301Msg_ExtServiceReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ExtServiceReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ExtServiceReq* pvalue);

EXTERN void asn1Init_TS24301Msg_ExtServiceReq (TS24301Msg_ExtServiceReq* pvalue);

/**************************************************************/
/*                                                            */
/*  GUTIReallocCmd                                            */
/*                                                            */
/**************************************************************/
/*
GUTIReallocCmd ::= SEQUENCE {
   guti [0] EPSMobileIdentity,
   taiList [1] TrackingAreaIdentList OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_GUTIReallocCmd {
   struct {
      unsigned taiListPresent : 1;
   } m;
   TS24301IE_EPSMobileIdentity guti;
   TS24301IE_TrackingAreaIdentList taiList;
} TS24301Msg_GUTIReallocCmd;

EXTERN int NASEnc_TS24301Msg_GUTIReallocCmd (OSCTXT* pctxt
   , TS24301Msg_GUTIReallocCmd* pvalue);

EXTERN int NASDec_TS24301Msg_GUTIReallocCmd (OSCTXT* pctxt
   , TS24301Msg_GUTIReallocCmd* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_GUTIReallocCmd (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_GUTIReallocCmd* pvalue);

EXTERN void asn1Init_TS24301Msg_GUTIReallocCmd (TS24301Msg_GUTIReallocCmd* pvalue);

/**************************************************************/
/*                                                            */
/*  IdentReq                                                  */
/*                                                            */
/**************************************************************/
/*
IdentReq ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   identType [1] IdentityType2Value
}
*/
typedef struct EXTERN TS24301Msg_IdentReq {
   OSUINT8 spare;
   TS24008IE_IdentityType2Value identType;
} TS24301Msg_IdentReq;

EXTERN int NASEnc_TS24301Msg_IdentReq (OSCTXT* pctxt
   , TS24301Msg_IdentReq* pvalue);

EXTERN int NASDec_TS24301Msg_IdentReq (OSCTXT* pctxt
   , TS24301Msg_IdentReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_IdentReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_IdentReq* pvalue);

EXTERN void asn1Init_TS24301Msg_IdentReq (TS24301Msg_IdentReq* pvalue);

/**************************************************************/
/*                                                            */
/*  SecModeCmd                                                */
/*                                                            */
/**************************************************************/
/*
SecModeCmd ::= SEQUENCE {
   selNASSecurityAlgs [0] NASSecurityAlgorithms,
   spare [1] INTEGER (0..15) DEFAULT 0,
   nasKeySetIdentifier [2] NASKeySetIdentifier,
   replayedUESecurityCapabilities [3] UESecurityCapability,
   imeisvRequest [4] IMEISVRequest OPTIONAL,
   replayedNonce [5] Nonce OPTIONAL,
   nonce [6] Nonce OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_SecModeCmd {
   struct {
      unsigned imeisvRequestPresent : 1;
      unsigned replayedNoncePresent : 1;
      unsigned noncePresent : 1;
   } m;
   TS24301IE_NASSecurityAlgorithms selNASSecurityAlgs;
   OSUINT8 spare;
   TS24301IE_NASKeySetIdentifier nasKeySetIdentifier;
   TS24301IE_UESecurityCapability replayedUESecurityCapabilities;
   TS24008IE_IMEISVRequest imeisvRequest;
   TS24301IE_Nonce replayedNonce;
   TS24301IE_Nonce nonce;
} TS24301Msg_SecModeCmd;

EXTERN int NASEnc_TS24301Msg_SecModeCmd (OSCTXT* pctxt
   , TS24301Msg_SecModeCmd* pvalue);

EXTERN int NASDec_TS24301Msg_SecModeCmd (OSCTXT* pctxt
   , TS24301Msg_SecModeCmd* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_SecModeCmd (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_SecModeCmd* pvalue);

EXTERN void asn1Init_TS24301Msg_SecModeCmd (TS24301Msg_SecModeCmd* pvalue);

/**************************************************************/
/*                                                            */
/*  SecModeCmplt                                              */
/*                                                            */
/**************************************************************/
/*
SecModeCmplt ::= SEQUENCE {
   imeisv [0] MobileIdentity OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_SecModeCmplt {
   struct {
      unsigned imeisvPresent : 1;
   } m;
   TS24008IE_MobileIdentity imeisv;
} TS24301Msg_SecModeCmplt;

EXTERN int NASEnc_TS24301Msg_SecModeCmplt (OSCTXT* pctxt
   , TS24301Msg_SecModeCmplt* pvalue);

EXTERN int NASDec_TS24301Msg_SecModeCmplt (OSCTXT* pctxt
   , TS24301Msg_SecModeCmplt* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_SecModeCmplt (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_SecModeCmplt* pvalue);

EXTERN void asn1Init_TS24301Msg_SecModeCmplt (TS24301Msg_SecModeCmplt* pvalue);

/**************************************************************/
/*                                                            */
/*  ServiceReject                                             */
/*                                                            */
/**************************************************************/
/*
ServiceReject ::= SEQUENCE {
   emmCause [0] EMMCause,
   t3442Value [1] GPRSTimer OPTIONAL,
   ...,
   [[ 10:
      t3346Value [2] GPRSTimer2 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_ServiceReject {
   struct {
      unsigned t3442ValuePresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned t3346ValuePresent : 1;
   } m;
   TS24301IE_EMMCause emmCause;
   TS24008IE_GPRSTimer t3442Value;
   TS24008IE_GPRSTimer2 t3346Value;
} TS24301Msg_ServiceReject;

EXTERN int NASEnc_TS24301Msg_ServiceReject (OSCTXT* pctxt
   , TS24301Msg_ServiceReject* pvalue);

EXTERN int NASDec_TS24301Msg_ServiceReject (OSCTXT* pctxt
   , TS24301Msg_ServiceReject* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ServiceReject (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ServiceReject* pvalue);

EXTERN void asn1Init_TS24301Msg_ServiceReject (TS24301Msg_ServiceReject* pvalue);

/**************************************************************/
/*                                                            */
/*  TrkAreaUpdAccept                                          */
/*                                                            */
/**************************************************************/
/*
TrkAreaUpdAccept ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   epsUpdateResult [1] EPSUpdateResult,
   t3412Value [2] GPRSTimer OPTIONAL,
   guti [3] EPSMobileIdentity OPTIONAL,
   taiList [4] TrackingAreaIdentList OPTIONAL,
   epsBearerContextStatus [5] EPSBearerContextStatus OPTIONAL,
   locAreaIdent [6] LocAreaIdent OPTIONAL,
   msIdentity [7] MobileIdentity OPTIONAL,
   emmCause [8] EMMCause OPTIONAL,
   t3402Value [9] GPRSTimer OPTIONAL,
   t3423Value [10] GPRSTimer OPTIONAL,
   equivalentPLMNs [11] PLMNList OPTIONAL,
   emergencyNumberList [12] EmergencyNumberList OPTIONAL,
   epsNetworkFeatureSupport [13] EPSNetworkFeatureSupport OPTIONAL,
   addnUpdateResult [14] AddnUpdateResult OPTIONAL,
   ...,
   [[ 10:
      t3412ExtValue [15] GPRSTimer3 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_TrkAreaUpdAccept {
   struct {
      unsigned t3412ValuePresent : 1;
      unsigned gutiPresent : 1;
      unsigned taiListPresent : 1;
      unsigned epsBearerContextStatusPresent : 1;
      unsigned locAreaIdentPresent : 1;
      unsigned msIdentityPresent : 1;
      unsigned emmCausePresent : 1;
      unsigned t3402ValuePresent : 1;
      unsigned t3423ValuePresent : 1;
      unsigned equivalentPLMNsPresent : 1;
      unsigned emergencyNumberListPresent : 1;
      unsigned epsNetworkFeatureSupportPresent : 1;
      unsigned addnUpdateResultPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned t3412ExtValuePresent : 1;
   } m;
   OSUINT8 spare;
   TS24301IE_EPSUpdateResult epsUpdateResult;
   TS24008IE_GPRSTimer t3412Value;
   TS24301IE_EPSMobileIdentity guti;
   TS24301IE_TrackingAreaIdentList taiList;
   TS24301IE_EPSBearerContextStatus epsBearerContextStatus;
   TS24008IE_LocAreaIdent locAreaIdent;
   TS24008IE_MobileIdentity msIdentity;
   TS24301IE_EMMCause emmCause;
   TS24008IE_GPRSTimer t3402Value;
   TS24008IE_GPRSTimer t3423Value;
   TS24008IE_PLMNList equivalentPLMNs;
   TS24008IE_EmergencyNumberList emergencyNumberList;
   TS24301IE_EPSNetworkFeatureSupport epsNetworkFeatureSupport;
   TS24301IE_AddnUpdateResult addnUpdateResult;
   TS24008IE_GPRSTimer3 t3412ExtValue;
} TS24301Msg_TrkAreaUpdAccept;

EXTERN int NASEnc_TS24301Msg_TrkAreaUpdAccept (OSCTXT* pctxt
   , TS24301Msg_TrkAreaUpdAccept* pvalue);

EXTERN int NASDec_TS24301Msg_TrkAreaUpdAccept (OSCTXT* pctxt
   , TS24301Msg_TrkAreaUpdAccept* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_TrkAreaUpdAccept (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_TrkAreaUpdAccept* pvalue);

EXTERN void asn1Init_TS24301Msg_TrkAreaUpdAccept (TS24301Msg_TrkAreaUpdAccept* pvalue);

/**************************************************************/
/*                                                            */
/*  TrkAreaUpdReject                                          */
/*                                                            */
/**************************************************************/
/*
TrkAreaUpdReject ::= SEQUENCE {
   cause [0] EMMCause,
   ...,
   [[ 10:
      t3346Value [1] GPRSTimer2 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_TrkAreaUpdReject {
   struct {
      unsigned _v10ExtPresent : 1;
      unsigned t3346ValuePresent : 1;
   } m;
   TS24301IE_EMMCause cause;
   TS24008IE_GPRSTimer2 t3346Value;
} TS24301Msg_TrkAreaUpdReject;

EXTERN int NASEnc_TS24301Msg_TrkAreaUpdReject (OSCTXT* pctxt
   , TS24301Msg_TrkAreaUpdReject* pvalue);

EXTERN int NASDec_TS24301Msg_TrkAreaUpdReject (OSCTXT* pctxt
   , TS24301Msg_TrkAreaUpdReject* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_TrkAreaUpdReject (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_TrkAreaUpdReject* pvalue);

EXTERN void asn1Init_TS24301Msg_TrkAreaUpdReject (TS24301Msg_TrkAreaUpdReject* pvalue);

/**************************************************************/
/*                                                            */
/*  TrkAreaUpdRequest                                         */
/*                                                            */
/**************************************************************/
/*
TrkAreaUpdRequest ::= SEQUENCE {
   nasKeySetIdentifier [0] NASKeySetIdentifier,
   epsUpdateType [1] EPSUpdateType,
   oldGUTI [2] EPSMobileIdentity,
   nonCurrNativeNASKeySetIdent [3] NASKeySetIdentifier OPTIONAL,
   gprsCiphKeySeqNum [4] CiphKeySeqNum OPTIONAL,
   oldP-TMSISignature [5] P-TMSISignature OPTIONAL,
   additionalGUTI [6] EPSMobileIdentity OPTIONAL,
   nonce [7] Nonce OPTIONAL,
   ueNetworkCapability [8] UENetworkCapability OPTIONAL,
   lastVisitedRegisteredTAI [9] TrackingAreaIdent OPTIONAL,
   drxParameter [10] DRXParameter OPTIONAL,
   ueRadioCapInfoUpdateNeeded [11] UERadioCapInfoUpdateNeeded OPTIONAL,
   epsBearerContextStatus [12] EPSBearerContextStatus OPTIONAL,
   msNetworkCapability [13] MSNetworkCapability OPTIONAL,
   oldLocAreaIdent [14] LocAreaIdent OPTIONAL,
   tmsiStatus [15] TMSIStatus OPTIONAL,
   mobileStationClassmark2 [16] MobileStationClassmark2 OPTIONAL,
   mobileStationClassmark3 [17] MobileStationClassmark3 OPTIONAL,
   supportedCodecs [18] SupportedCodecList OPTIONAL,
   addnUpdateType [19] AddnUpdateType OPTIONAL,
   ...,
   [[ 9:
      voiceDomainPref [20] VoiceDomainPref OPTIONAL
   ]],
   [[ 10:
      oldGUTIType [21] GUTIType OPTIONAL,
      deviceProperties [22] DeviceProperties OPTIONAL,
      msNetFeatureSupport [23] MSNetFeatureSupport OPTIONAL
   ]],
   [[ 11:
      tmsiBasedNRIContainer [24] NetResourceIdentContainer OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_TrkAreaUpdRequest {
   struct {
      unsigned nonCurrNativeNASKeySetIdentPresent : 1;
      unsigned gprsCiphKeySeqNumPresent : 1;
      unsigned oldP_TMSISignaturePresent : 1;
      unsigned additionalGUTIPresent : 1;
      unsigned noncePresent : 1;
      unsigned ueNetworkCapabilityPresent : 1;
      unsigned lastVisitedRegisteredTAIPresent : 1;
      unsigned drxParameterPresent : 1;
      unsigned ueRadioCapInfoUpdateNeededPresent : 1;
      unsigned epsBearerContextStatusPresent : 1;
      unsigned msNetworkCapabilityPresent : 1;
      unsigned oldLocAreaIdentPresent : 1;
      unsigned tmsiStatusPresent : 1;
      unsigned mobileStationClassmark2Present : 1;
      unsigned mobileStationClassmark3Present : 1;
      unsigned supportedCodecsPresent : 1;
      unsigned addnUpdateTypePresent : 1;
      unsigned _v9ExtPresent : 1;
      unsigned voiceDomainPrefPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned oldGUTITypePresent : 1;
      unsigned devicePropertiesPresent : 1;
      unsigned msNetFeatureSupportPresent : 1;
      unsigned _v11ExtPresent : 1;
      unsigned tmsiBasedNRIContainerPresent : 1;
   } m;
   TS24301IE_NASKeySetIdentifier nasKeySetIdentifier;
   TS24301IE_EPSUpdateType epsUpdateType;
   TS24301IE_EPSMobileIdentity oldGUTI;
   TS24301IE_NASKeySetIdentifier nonCurrNativeNASKeySetIdent;
   TS24008IE_CiphKeySeqNum gprsCiphKeySeqNum;
   TS24008IE_P_TMSISignature oldP_TMSISignature;
   TS24301IE_EPSMobileIdentity additionalGUTI;
   TS24301IE_Nonce nonce;
   TS24301IE_UENetworkCapability ueNetworkCapability;
   TS24301IE_TrackingAreaIdent lastVisitedRegisteredTAI;
   TS24008IE_DRXParameter drxParameter;
   TS24301IE_UERadioCapInfoUpdateNeeded ueRadioCapInfoUpdateNeeded;
   TS24301IE_EPSBearerContextStatus epsBearerContextStatus;
   TS24008IE_MSNetworkCapability msNetworkCapability;
   TS24008IE_LocAreaIdent oldLocAreaIdent;
   TS24008IE_TMSIStatus tmsiStatus;
   TS24008IE_MobileStationClassmark2 mobileStationClassmark2;
   TS24008IE_MobileStationClassmark3 mobileStationClassmark3;
   TS24008IE_SupportedCodecList supportedCodecs;
   TS24301IE_AddnUpdateType addnUpdateType;
   TS24008IE_VoiceDomainPref voiceDomainPref;
   TS24301IE_GUTIType oldGUTIType;
   TS24008IE_DeviceProperties deviceProperties;
   TS24008IE_MSNetFeatureSupport msNetFeatureSupport;
   TS24008IE_NetResourceIdentContainer tmsiBasedNRIContainer;
} TS24301Msg_TrkAreaUpdRequest;

EXTERN int NASEnc_TS24301Msg_TrkAreaUpdRequest (OSCTXT* pctxt
   , TS24301Msg_TrkAreaUpdRequest* pvalue);

EXTERN int NASDec_TS24301Msg_TrkAreaUpdRequest (OSCTXT* pctxt
   , TS24301Msg_TrkAreaUpdRequest* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_TrkAreaUpdRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_TrkAreaUpdRequest* pvalue);

EXTERN void asn1Init_TS24301Msg_TrkAreaUpdRequest (
   TS24301Msg_TrkAreaUpdRequest* pvalue);

/**************************************************************/
/*                                                            */
/*  ActvDedEPSBearerCtxtAcc                                   */
/*                                                            */
/**************************************************************/
/*
ActvDedEPSBearerCtxtAcc ::= SEQUENCE {
   protocolConfigOptions [0] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ActvDedEPSBearerCtxtAcc {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ActvDedEPSBearerCtxtAcc;

EXTERN int NASEnc_TS24301Msg_ActvDedEPSBearerCtxtAcc (OSCTXT* pctxt
   , TS24301Msg_ActvDedEPSBearerCtxtAcc* pvalue);

EXTERN int NASDec_TS24301Msg_ActvDedEPSBearerCtxtAcc (OSCTXT* pctxt
   , TS24301Msg_ActvDedEPSBearerCtxtAcc* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDedEPSBearerCtxtAcc* pvalue);

EXTERN void asn1Init_TS24301Msg_ActvDedEPSBearerCtxtAcc (
   TS24301Msg_ActvDedEPSBearerCtxtAcc* pvalue);

/**************************************************************/
/*                                                            */
/*  ActvDedEPSBearerCtxtRej                                   */
/*                                                            */
/**************************************************************/
/*
ActvDedEPSBearerCtxtRej ::= SEQUENCE {
   esmCause [0] ESMCause,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ActvDedEPSBearerCtxtRej {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ActvDedEPSBearerCtxtRej;

EXTERN int NASEnc_TS24301Msg_ActvDedEPSBearerCtxtRej (OSCTXT* pctxt
   , TS24301Msg_ActvDedEPSBearerCtxtRej* pvalue);

EXTERN int NASDec_TS24301Msg_ActvDedEPSBearerCtxtRej (OSCTXT* pctxt
   , TS24301Msg_ActvDedEPSBearerCtxtRej* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDedEPSBearerCtxtRej* pvalue);

EXTERN void asn1Init_TS24301Msg_ActvDedEPSBearerCtxtRej (
   TS24301Msg_ActvDedEPSBearerCtxtRej* pvalue);

/**************************************************************/
/*                                                            */
/*  ActvDedEPSBearerCtxtReq                                   */
/*                                                            */
/**************************************************************/
/*
ActvDedEPSBearerCtxtReq ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   linkedEPSBearerIdent [1] LinkedEPSBearerIdent,
   epsQoS [2] EPSQualityOfService,
   tft [3] TFT,
   transIdent [4] LinkedTI OPTIONAL,
   negotiatedQoS [5] QualityOfService OPTIONAL,
   negotiatedLLCSAPI [6] LLCSAPIValue OPTIONAL,
   radioPriority [7] RadioPriorityValue OPTIONAL,
   packetFlowIdentifier [8] PacketFlowIdentValue OPTIONAL,
   protocolConfigOptions [9] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ActvDedEPSBearerCtxtReq {
   struct {
      unsigned transIdentPresent : 1;
      unsigned negotiatedQoSPresent : 1;
      unsigned negotiatedLLCSAPIPresent : 1;
      unsigned radioPriorityPresent : 1;
      unsigned packetFlowIdentifierPresent : 1;
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   OSUINT8 spare;
   TS24301IE_LinkedEPSBearerIdent linkedEPSBearerIdent;
   TS24301IE_EPSQualityOfService epsQoS;
   TS24008IE_TFT tft;
   TS24008IE_LinkedTI transIdent;
   TS24008IE_QualityOfService negotiatedQoS;
   TS24008IE_LLCSAPIValue negotiatedLLCSAPI;
   TS24008IE_RadioPriorityValue radioPriority;
   TS24008IE_PacketFlowIdentValue packetFlowIdentifier;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ActvDedEPSBearerCtxtReq;

EXTERN int NASEnc_TS24301Msg_ActvDedEPSBearerCtxtReq (OSCTXT* pctxt
   , TS24301Msg_ActvDedEPSBearerCtxtReq* pvalue);

EXTERN int NASDec_TS24301Msg_ActvDedEPSBearerCtxtReq (OSCTXT* pctxt
   , TS24301Msg_ActvDedEPSBearerCtxtReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ActvDedEPSBearerCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDedEPSBearerCtxtReq* pvalue);

EXTERN void asn1Init_TS24301Msg_ActvDedEPSBearerCtxtReq (
   TS24301Msg_ActvDedEPSBearerCtxtReq* pvalue);

/**************************************************************/
/*                                                            */
/*  ActvDfltEPSBearerCtxtAcc                                  */
/*                                                            */
/**************************************************************/
/*
ActvDfltEPSBearerCtxtAcc ::= SEQUENCE {
   protocolConfigOptions [0] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ActvDfltEPSBearerCtxtAcc {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ActvDfltEPSBearerCtxtAcc;

EXTERN int NASEnc_TS24301Msg_ActvDfltEPSBearerCtxtAcc (OSCTXT* pctxt
   , TS24301Msg_ActvDfltEPSBearerCtxtAcc* pvalue);

EXTERN int NASDec_TS24301Msg_ActvDfltEPSBearerCtxtAcc (OSCTXT* pctxt
   , TS24301Msg_ActvDfltEPSBearerCtxtAcc* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDfltEPSBearerCtxtAcc* pvalue);

EXTERN void asn1Init_TS24301Msg_ActvDfltEPSBearerCtxtAcc (
   TS24301Msg_ActvDfltEPSBearerCtxtAcc* pvalue);

/**************************************************************/
/*                                                            */
/*  ActvDfltEPSBearerCtxtRej                                  */
/*                                                            */
/**************************************************************/
/*
ActvDfltEPSBearerCtxtRej ::= SEQUENCE {
   esmCause [0] ESMCause,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ActvDfltEPSBearerCtxtRej {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ActvDfltEPSBearerCtxtRej;

EXTERN int NASEnc_TS24301Msg_ActvDfltEPSBearerCtxtRej (OSCTXT* pctxt
   , TS24301Msg_ActvDfltEPSBearerCtxtRej* pvalue);

EXTERN int NASDec_TS24301Msg_ActvDfltEPSBearerCtxtRej (OSCTXT* pctxt
   , TS24301Msg_ActvDfltEPSBearerCtxtRej* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDfltEPSBearerCtxtRej* pvalue);

EXTERN void asn1Init_TS24301Msg_ActvDfltEPSBearerCtxtRej (
   TS24301Msg_ActvDfltEPSBearerCtxtRej* pvalue);

/**************************************************************/
/*                                                            */
/*  ActvDfltEPSBearerCtxtReq                                  */
/*                                                            */
/**************************************************************/
/*
ActvDfltEPSBearerCtxtReq ::= SEQUENCE {
   epsQoS [0] EPSQualityOfService,
   accessPointName [1] AccessPointName,
   pdnAddress [2] PDNAddress,
   transIdent [3] LinkedTI OPTIONAL,
   negotiatedQoS [4] QualityOfService OPTIONAL,
   negotiatedLLCSAPI [5] LLCSAPIValue OPTIONAL,
   radioPriority [6] RadioPriorityValue OPTIONAL,
   packetFlowIdentifier [7] PacketFlowIdentValue OPTIONAL,
   apn-AMBR [8] APNAggMaxBitRate OPTIONAL,
   esmCause [9] ESMCause OPTIONAL,
   protocolConfigOptions [10] ProtocolConfigOptions OPTIONAL,
   ...,
   [[ 10:
      connectivityType [11] ConnectivityType OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_ActvDfltEPSBearerCtxtReq {
   struct {
      unsigned transIdentPresent : 1;
      unsigned negotiatedQoSPresent : 1;
      unsigned negotiatedLLCSAPIPresent : 1;
      unsigned radioPriorityPresent : 1;
      unsigned packetFlowIdentifierPresent : 1;
      unsigned apn_AMBRPresent : 1;
      unsigned esmCausePresent : 1;
      unsigned protocolConfigOptionsPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned connectivityTypePresent : 1;
   } m;
   TS24301IE_EPSQualityOfService epsQoS;
   TS24008IE_AccessPointName accessPointName;
   TS24301IE_PDNAddress pdnAddress;
   TS24008IE_LinkedTI transIdent;
   TS24008IE_QualityOfService negotiatedQoS;
   TS24008IE_LLCSAPIValue negotiatedLLCSAPI;
   TS24008IE_RadioPriorityValue radioPriority;
   TS24008IE_PacketFlowIdentValue packetFlowIdentifier;
   TS24301IE_APNAggMaxBitRate apn_AMBR;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
   TS24008IE_ConnectivityType connectivityType;
} TS24301Msg_ActvDfltEPSBearerCtxtReq;

EXTERN int NASEnc_TS24301Msg_ActvDfltEPSBearerCtxtReq (OSCTXT* pctxt
   , TS24301Msg_ActvDfltEPSBearerCtxtReq* pvalue);

EXTERN int NASDec_TS24301Msg_ActvDfltEPSBearerCtxtReq (OSCTXT* pctxt
   , TS24301Msg_ActvDfltEPSBearerCtxtReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ActvDfltEPSBearerCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ActvDfltEPSBearerCtxtReq* pvalue);

EXTERN void asn1Init_TS24301Msg_ActvDfltEPSBearerCtxtReq (
   TS24301Msg_ActvDfltEPSBearerCtxtReq* pvalue);

/**************************************************************/
/*                                                            */
/*  BearerResAllocRej                                         */
/*                                                            */
/**************************************************************/
/*
BearerResAllocRej ::= SEQUENCE {
   esmCause [0] ESMCause,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL,
   ...,
   [[ 10:
      t3396Value [2] GPRSTimer3 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_BearerResAllocRej {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned t3396ValuePresent : 1;
   } m;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
   TS24008IE_GPRSTimer3 t3396Value;
} TS24301Msg_BearerResAllocRej;

EXTERN int NASEnc_TS24301Msg_BearerResAllocRej (OSCTXT* pctxt
   , TS24301Msg_BearerResAllocRej* pvalue);

EXTERN int NASDec_TS24301Msg_BearerResAllocRej (OSCTXT* pctxt
   , TS24301Msg_BearerResAllocRej* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_BearerResAllocRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_BearerResAllocRej* pvalue);

EXTERN void asn1Init_TS24301Msg_BearerResAllocRej (
   TS24301Msg_BearerResAllocRej* pvalue);

/**************************************************************/
/*                                                            */
/*  BearerResAllocReq                                         */
/*                                                            */
/**************************************************************/
/*
BearerResAllocReq ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   linkedEPSBearerIdent [1] LinkedEPSBearerIdent,
   trafficFlowAgg [2] TFT,
   epsQoS [3] EPSQualityOfService,
   protocolConfigOptions [4] ProtocolConfigOptions OPTIONAL,
   ...,
   [[ 10:
      deviceProperties [5] DeviceProperties OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_BearerResAllocReq {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned devicePropertiesPresent : 1;
   } m;
   OSUINT8 spare;
   TS24301IE_LinkedEPSBearerIdent linkedEPSBearerIdent;
   TS24008IE_TFT trafficFlowAgg;
   TS24301IE_EPSQualityOfService epsQoS;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
   TS24008IE_DeviceProperties deviceProperties;
} TS24301Msg_BearerResAllocReq;

EXTERN int NASEnc_TS24301Msg_BearerResAllocReq (OSCTXT* pctxt
   , TS24301Msg_BearerResAllocReq* pvalue);

EXTERN int NASDec_TS24301Msg_BearerResAllocReq (OSCTXT* pctxt
   , TS24301Msg_BearerResAllocReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_BearerResAllocReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_BearerResAllocReq* pvalue);

EXTERN void asn1Init_TS24301Msg_BearerResAllocReq (
   TS24301Msg_BearerResAllocReq* pvalue);

/**************************************************************/
/*                                                            */
/*  BearerResModRej                                           */
/*                                                            */
/**************************************************************/
/*
BearerResModRej ::= SEQUENCE {
   esmCause [0] ESMCause,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL,
   ...,
   [[ 10:
      t3396Value [2] GPRSTimer3 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_BearerResModRej {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned t3396ValuePresent : 1;
   } m;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
   TS24008IE_GPRSTimer3 t3396Value;
} TS24301Msg_BearerResModRej;

EXTERN int NASEnc_TS24301Msg_BearerResModRej (OSCTXT* pctxt
   , TS24301Msg_BearerResModRej* pvalue);

EXTERN int NASDec_TS24301Msg_BearerResModRej (OSCTXT* pctxt
   , TS24301Msg_BearerResModRej* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_BearerResModRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_BearerResModRej* pvalue);

EXTERN void asn1Init_TS24301Msg_BearerResModRej (TS24301Msg_BearerResModRej* pvalue);

/**************************************************************/
/*                                                            */
/*  BearerResModReq                                           */
/*                                                            */
/**************************************************************/
/*
BearerResModReq ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   linkedEPSBearerIdent [1] LinkedEPSBearerIdent,
   trafficFlowAgg [2] TFT,
   reqTrafficFlowQoS [3] EPSQualityOfService OPTIONAL,
   esmCause [4] ESMCause OPTIONAL,
   protocolConfigOptions [5] ProtocolConfigOptions OPTIONAL,
   ...,
   [[ 10:
      deviceProperties [6] DeviceProperties OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_BearerResModReq {
   struct {
      unsigned reqTrafficFlowQoSPresent : 1;
      unsigned esmCausePresent : 1;
      unsigned protocolConfigOptionsPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned devicePropertiesPresent : 1;
   } m;
   OSUINT8 spare;
   TS24301IE_LinkedEPSBearerIdent linkedEPSBearerIdent;
   TS24008IE_TFT trafficFlowAgg;
   TS24301IE_EPSQualityOfService reqTrafficFlowQoS;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
   TS24008IE_DeviceProperties deviceProperties;
} TS24301Msg_BearerResModReq;

EXTERN int NASEnc_TS24301Msg_BearerResModReq (OSCTXT* pctxt
   , TS24301Msg_BearerResModReq* pvalue);

EXTERN int NASDec_TS24301Msg_BearerResModReq (OSCTXT* pctxt
   , TS24301Msg_BearerResModReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_BearerResModReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_BearerResModReq* pvalue);

EXTERN void asn1Init_TS24301Msg_BearerResModReq (TS24301Msg_BearerResModReq* pvalue);

/**************************************************************/
/*                                                            */
/*  DeactEPSBearerCtxtAcc                                     */
/*                                                            */
/**************************************************************/
/*
DeactEPSBearerCtxtAcc ::= SEQUENCE {
   protocolConfigOptions [0] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_DeactEPSBearerCtxtAcc {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_DeactEPSBearerCtxtAcc;

EXTERN int NASEnc_TS24301Msg_DeactEPSBearerCtxtAcc (OSCTXT* pctxt
   , TS24301Msg_DeactEPSBearerCtxtAcc* pvalue);

EXTERN int NASDec_TS24301Msg_DeactEPSBearerCtxtAcc (OSCTXT* pctxt
   , TS24301Msg_DeactEPSBearerCtxtAcc* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_DeactEPSBearerCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DeactEPSBearerCtxtAcc* pvalue);

EXTERN void asn1Init_TS24301Msg_DeactEPSBearerCtxtAcc (
   TS24301Msg_DeactEPSBearerCtxtAcc* pvalue);

/**************************************************************/
/*                                                            */
/*  DeactEPSBearerCtxtReq                                     */
/*                                                            */
/**************************************************************/
/*
DeactEPSBearerCtxtReq ::= SEQUENCE {
   esmCause [0] ESMCause,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL,
   ...,
   [[ 11:
      t3396Value [2] GPRSTimer3 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_DeactEPSBearerCtxtReq {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
      unsigned _v11ExtPresent : 1;
      unsigned t3396ValuePresent : 1;
   } m;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
   TS24008IE_GPRSTimer3 t3396Value;
} TS24301Msg_DeactEPSBearerCtxtReq;

EXTERN int NASEnc_TS24301Msg_DeactEPSBearerCtxtReq (OSCTXT* pctxt
   , TS24301Msg_DeactEPSBearerCtxtReq* pvalue);

EXTERN int NASDec_TS24301Msg_DeactEPSBearerCtxtReq (OSCTXT* pctxt
   , TS24301Msg_DeactEPSBearerCtxtReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_DeactEPSBearerCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_DeactEPSBearerCtxtReq* pvalue);

EXTERN void asn1Init_TS24301Msg_DeactEPSBearerCtxtReq (
   TS24301Msg_DeactEPSBearerCtxtReq* pvalue);

/**************************************************************/
/*                                                            */
/*  ESMInfoResp                                               */
/*                                                            */
/**************************************************************/
/*
ESMInfoResp ::= SEQUENCE {
   accessPointName [0] AccessPointName OPTIONAL,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ESMInfoResp {
   struct {
      unsigned accessPointNamePresent : 1;
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24008IE_AccessPointName accessPointName;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ESMInfoResp;

EXTERN int NASEnc_TS24301Msg_ESMInfoResp (OSCTXT* pctxt
   , TS24301Msg_ESMInfoResp* pvalue);

EXTERN int NASDec_TS24301Msg_ESMInfoResp (OSCTXT* pctxt
   , TS24301Msg_ESMInfoResp* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ESMInfoResp (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ESMInfoResp* pvalue);

EXTERN void asn1Init_TS24301Msg_ESMInfoResp (TS24301Msg_ESMInfoResp* pvalue);

/**************************************************************/
/*                                                            */
/*  ModEPSBearerCtxtAcc                                       */
/*                                                            */
/**************************************************************/
/*
ModEPSBearerCtxtAcc ::= SEQUENCE {
   protocolConfigOptions [0] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ModEPSBearerCtxtAcc {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ModEPSBearerCtxtAcc;

EXTERN int NASEnc_TS24301Msg_ModEPSBearerCtxtAcc (OSCTXT* pctxt
   , TS24301Msg_ModEPSBearerCtxtAcc* pvalue);

EXTERN int NASDec_TS24301Msg_ModEPSBearerCtxtAcc (OSCTXT* pctxt
   , TS24301Msg_ModEPSBearerCtxtAcc* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtAcc (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ModEPSBearerCtxtAcc* pvalue);

EXTERN void asn1Init_TS24301Msg_ModEPSBearerCtxtAcc (
   TS24301Msg_ModEPSBearerCtxtAcc* pvalue);

/**************************************************************/
/*                                                            */
/*  ModEPSBearerCtxtRej                                       */
/*                                                            */
/**************************************************************/
/*
ModEPSBearerCtxtRej ::= SEQUENCE {
   esmCause [0] ESMCause,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ModEPSBearerCtxtRej {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ModEPSBearerCtxtRej;

EXTERN int NASEnc_TS24301Msg_ModEPSBearerCtxtRej (OSCTXT* pctxt
   , TS24301Msg_ModEPSBearerCtxtRej* pvalue);

EXTERN int NASDec_TS24301Msg_ModEPSBearerCtxtRej (OSCTXT* pctxt
   , TS24301Msg_ModEPSBearerCtxtRej* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ModEPSBearerCtxtRej* pvalue);

EXTERN void asn1Init_TS24301Msg_ModEPSBearerCtxtRej (
   TS24301Msg_ModEPSBearerCtxtRej* pvalue);

/**************************************************************/
/*                                                            */
/*  ModEPSBearerCtxtReq                                       */
/*                                                            */
/**************************************************************/
/*
ModEPSBearerCtxtReq ::= SEQUENCE {
   newEPSQoS [0] EPSQualityOfService OPTIONAL,
   tft [1] TFT OPTIONAL,
   newQoS [2] QualityOfService OPTIONAL,
   negotiatedLLCSAPI [3] LLCSAPIValue OPTIONAL,
   radioPriority [4] RadioPriorityValue OPTIONAL,
   packetFlowIdentifier [5] PacketFlowIdentValue OPTIONAL,
   apn-AMBR [6] APNAggMaxBitRate OPTIONAL,
   protocolConfigOptions [7] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_ModEPSBearerCtxtReq {
   struct {
      unsigned newEPSQoSPresent : 1;
      unsigned tftPresent : 1;
      unsigned newQoSPresent : 1;
      unsigned negotiatedLLCSAPIPresent : 1;
      unsigned radioPriorityPresent : 1;
      unsigned packetFlowIdentifierPresent : 1;
      unsigned apn_AMBRPresent : 1;
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24301IE_EPSQualityOfService newEPSQoS;
   TS24008IE_TFT tft;
   TS24008IE_QualityOfService newQoS;
   TS24008IE_LLCSAPIValue negotiatedLLCSAPI;
   TS24008IE_RadioPriorityValue radioPriority;
   TS24008IE_PacketFlowIdentValue packetFlowIdentifier;
   TS24301IE_APNAggMaxBitRate apn_AMBR;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_ModEPSBearerCtxtReq;

EXTERN int NASEnc_TS24301Msg_ModEPSBearerCtxtReq (OSCTXT* pctxt
   , TS24301Msg_ModEPSBearerCtxtReq* pvalue);

EXTERN int NASDec_TS24301Msg_ModEPSBearerCtxtReq (OSCTXT* pctxt
   , TS24301Msg_ModEPSBearerCtxtReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ModEPSBearerCtxtReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ModEPSBearerCtxtReq* pvalue);

EXTERN void asn1Init_TS24301Msg_ModEPSBearerCtxtReq (
   TS24301Msg_ModEPSBearerCtxtReq* pvalue);

/**************************************************************/
/*                                                            */
/*  PDNConnectRej                                             */
/*                                                            */
/**************************************************************/
/*
PDNConnectRej ::= SEQUENCE {
   esmCause [0] ESMCause,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL,
   ...,
   [[ 10:
      t3396Value [2] GPRSTimer3 OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_PDNConnectRej {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned t3396ValuePresent : 1;
   } m;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
   TS24008IE_GPRSTimer3 t3396Value;
} TS24301Msg_PDNConnectRej;

EXTERN int NASEnc_TS24301Msg_PDNConnectRej (OSCTXT* pctxt
   , TS24301Msg_PDNConnectRej* pvalue);

EXTERN int NASDec_TS24301Msg_PDNConnectRej (OSCTXT* pctxt
   , TS24301Msg_PDNConnectRej* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_PDNConnectRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDNConnectRej* pvalue);

EXTERN void asn1Init_TS24301Msg_PDNConnectRej (TS24301Msg_PDNConnectRej* pvalue);

/**************************************************************/
/*                                                            */
/*  PDNConnectReq                                             */
/*                                                            */
/**************************************************************/
/*
PDNConnectReq ::= SEQUENCE {
   pdnType [0] PDNType,
   requestType [1] RequestTypeValue,
   esmInfoXferFlag [2] ESMInfoXferFlag OPTIONAL,
   accessPointName [3] AccessPointName OPTIONAL,
   protocolConfigOptions [4] ProtocolConfigOptions OPTIONAL,
   ...,
   [[ 10:
      deviceProperties [5] DeviceProperties OPTIONAL
   ]]
}
*/
typedef struct EXTERN TS24301Msg_PDNConnectReq {
   struct {
      unsigned esmInfoXferFlagPresent : 1;
      unsigned accessPointNamePresent : 1;
      unsigned protocolConfigOptionsPresent : 1;
      unsigned _v10ExtPresent : 1;
      unsigned devicePropertiesPresent : 1;
   } m;
   TS24301IE_PDNType pdnType;
   TS24008IE_RequestTypeValue requestType;
   TS24301IE_ESMInfoXferFlag esmInfoXferFlag;
   TS24008IE_AccessPointName accessPointName;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
   TS24008IE_DeviceProperties deviceProperties;
} TS24301Msg_PDNConnectReq;

EXTERN int NASEnc_TS24301Msg_PDNConnectReq (OSCTXT* pctxt
   , TS24301Msg_PDNConnectReq* pvalue);

EXTERN int NASDec_TS24301Msg_PDNConnectReq (OSCTXT* pctxt
   , TS24301Msg_PDNConnectReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_PDNConnectReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDNConnectReq* pvalue);

EXTERN void asn1Init_TS24301Msg_PDNConnectReq (TS24301Msg_PDNConnectReq* pvalue);

/**************************************************************/
/*                                                            */
/*  PDNDisconnRej                                             */
/*                                                            */
/**************************************************************/
/*
PDNDisconnRej ::= SEQUENCE {
   esmCause [0] ESMCause,
   protocolConfigOptions [1] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_PDNDisconnRej {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   TS24301IE_ESMCause esmCause;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_PDNDisconnRej;

EXTERN int NASEnc_TS24301Msg_PDNDisconnRej (OSCTXT* pctxt
   , TS24301Msg_PDNDisconnRej* pvalue);

EXTERN int NASDec_TS24301Msg_PDNDisconnRej (OSCTXT* pctxt
   , TS24301Msg_PDNDisconnRej* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_PDNDisconnRej (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDNDisconnRej* pvalue);

EXTERN void asn1Init_TS24301Msg_PDNDisconnRej (TS24301Msg_PDNDisconnRej* pvalue);

/**************************************************************/
/*                                                            */
/*  PDNDisconnReq                                             */
/*                                                            */
/**************************************************************/
/*
PDNDisconnReq ::= SEQUENCE {
   spare [0] INTEGER (0..15) DEFAULT 0,
   linkedEPSBearerIdent [1] LinkedEPSBearerIdent,
   protocolConfigOptions [2] ProtocolConfigOptions OPTIONAL
}
*/
typedef struct EXTERN TS24301Msg_PDNDisconnReq {
   struct {
      unsigned protocolConfigOptionsPresent : 1;
   } m;
   OSUINT8 spare;
   TS24301IE_LinkedEPSBearerIdent linkedEPSBearerIdent;
   TS24008IE_ProtocolConfigOptions protocolConfigOptions;
} TS24301Msg_PDNDisconnReq;

EXTERN int NASEnc_TS24301Msg_PDNDisconnReq (OSCTXT* pctxt
   , TS24301Msg_PDNDisconnReq* pvalue);

EXTERN int NASDec_TS24301Msg_PDNDisconnReq (OSCTXT* pctxt
   , TS24301Msg_PDNDisconnReq* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_PDNDisconnReq (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDNDisconnReq* pvalue);

EXTERN void asn1Init_TS24301Msg_PDNDisconnReq (TS24301Msg_PDNDisconnReq* pvalue);

/**************************************************************/
/*                                                            */
/*  PDU                                                       */
/*                                                            */
/**************************************************************/
/*
PDU ::= SEQUENCE {
   secHdr [0] SecProtMsgHeader OPTIONAL,
   l3HdrOpts [1] L3HdrOptions,
   protoDiscr [2] NAS-PROTOCOL-CLASS.&protoDiscr ({TS24301-IE-OBJECTSET}),
   pti [3] CHOICE {
      value [0] INTEGER (0..255),
      noValue [1] NULL
   },
   msgType [4] NAS-PROTOCOL-CLASS.&msgType ({TS24301-IE-OBJECTSET}) (0..255),
   data [5] NAS-PROTOCOL-CLASS.&Value ({TS24301-IE-OBJECTSET}{@protoDiscr}{@msgType})
}
*/
typedef struct EXTERN TS24301Msg_PDU {
   struct {
      unsigned secHdrPresent : 1;
   } m;
   TS24007L3_SecProtMsgHeader secHdr;
   TS24007L3_L3HdrOptions l3HdrOpts;
   TS24007L3_ProtoDiscr protoDiscr;
   struct  {
      union {
         /* selector element = protoDiscr, value = 2 */
         OSUINT8 value;
         /* default case */
      } u;
   } pti;
   OSUINT8 msgType;
   struct {
      /**
       * information object selector
       */
      TS24301_IE_OBJECTSET_TVALUE t;

      /**
       * TS24301-IE-OBJECTSET information objects
       */
      union {
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-AttachAccept
          */
         TS24301Msg_AttachAccept *obj_AttachAccept;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-AttachComplete
          */
         TS24301Msg_AttachComplete *obj_AttachComplete;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-AttachReject
          */
         TS24301Msg_AttachReject *obj_AttachReject;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-AttachRequest
          */
         TS24301Msg_AttachRequest *obj_AttachRequest;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-AuthFailure
          */
         TS24301Msg_AuthFailure *obj_AuthFailure;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-AuthReject
          */
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-AuthRequest
          */
         TS24301Msg_AuthRequest *obj_AuthRequest;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-AuthResponse
          */
         TS24301Msg_AuthResponse *obj_AuthResponse;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-CSServiceNotif
          */
         TS24301Msg_CSServiceNotif *obj_CSServiceNotif;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-DetachAccept
          */
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-DetachRequest
          */
         TS24301Msg_DetachRequest *obj_DetachRequest;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-DLNASTransport
          */
         TS24301Msg_DLNASTransport *obj_DLNASTransport;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-EMMInformation
          */
         TS24301Msg_EMMInformation *obj_EMMInformation;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-EMMStatus
          */
         TS24301Msg_EMMStatus obj_EMMStatus;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-ExtServiceReq
          */
         TS24301Msg_ExtServiceReq *obj_ExtServiceReq;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-GUTIReallocCmd
          */
         TS24301Msg_GUTIReallocCmd *obj_GUTIReallocCmd;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-GUTIReallocCmplt
          */
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-IdentReq
          */
         TS24301Msg_IdentReq *obj_IdentReq;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-IdentResp
          */
         TS24301Msg_IdentResp *obj_IdentResp;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-SecModeCmd
          */
         TS24301Msg_SecModeCmd *obj_SecModeCmd;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-SecModeCmplt
          */
         TS24301Msg_SecModeCmplt *obj_SecModeCmplt;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-SecModeReject
          */
         TS24301Msg_SecModeReject obj_SecModeReject;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-ServiceReject
          */
         TS24301Msg_ServiceReject *obj_ServiceReject;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-TrkAreaUpdAccept
          */
         TS24301Msg_TrkAreaUpdAccept *obj_TrkAreaUpdAccept;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-TrkAreaUpdCmplt
          */
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-TrkAreaUpdReject
          */
         TS24301Msg_TrkAreaUpdReject *obj_TrkAreaUpdReject;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-TrkAreaUpdRequest
          */
         TS24301Msg_TrkAreaUpdRequest *obj_TrkAreaUpdRequest;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-ULNASTransport
          */
         TS24301Msg_ULNASTransport *obj_ULNASTransport;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-ULGenNASTransport
          */
         TS24301Msg_ULGenNASTransport *obj_ULGenNASTransport;
         /**
          * protoDiscr: epsMobMgmt
          * msgType: mt-DLGenNASTransport
          */
         TS24301Msg_DLGenNASTransport *obj_DLGenNASTransport;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ActvDedEPSBearerCtxtAcc
          */
         TS24301Msg_ActvDedEPSBearerCtxtAcc *obj_ActvDedEPSBearerCtxtAcc;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ActvDedEPSBearerCtxtRej
          */
         TS24301Msg_ActvDedEPSBearerCtxtRej *obj_ActvDedEPSBearerCtxtRej;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ActvDedEPSBearerCtxtReq
          */
         TS24301Msg_ActvDedEPSBearerCtxtReq *obj_ActvDedEPSBearerCtxtReq;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ActvDfltEPSBearerCtxtAcc
          */
         TS24301Msg_ActvDfltEPSBearerCtxtAcc *obj_ActvDfltEPSBearerCtxtAcc;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ActvDfltEPSBearerCtxtRej
          */
         TS24301Msg_ActvDfltEPSBearerCtxtRej *obj_ActvDfltEPSBearerCtxtRej;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ActvDfltEPSBearerCtxtReq
          */
         TS24301Msg_ActvDfltEPSBearerCtxtReq *obj_ActvDfltEPSBearerCtxtReq;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-BearerResAllocRej
          */
         TS24301Msg_BearerResAllocRej *obj_BearerResAllocRej;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-BearerResAllocReq
          */
         TS24301Msg_BearerResAllocReq *obj_BearerResAllocReq;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-BearerResModRej
          */
         TS24301Msg_BearerResModRej *obj_BearerResModRej;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-BearerResModReq
          */
         TS24301Msg_BearerResModReq *obj_BearerResModReq;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-DeactEPSBearerCtxtAcc
          */
         TS24301Msg_DeactEPSBearerCtxtAcc *obj_DeactEPSBearerCtxtAcc;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-DeactEPSBearerCtxtReq
          */
         TS24301Msg_DeactEPSBearerCtxtReq *obj_DeactEPSBearerCtxtReq;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ESMInfoReq
          */
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ESMInfoResp
          */
         TS24301Msg_ESMInfoResp *obj_ESMInfoResp;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ESMStatus
          */
         TS24301Msg_ESMStatus obj_ESMStatus;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ModEPSBearerCtxtAcc
          */
         TS24301Msg_ModEPSBearerCtxtAcc *obj_ModEPSBearerCtxtAcc;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ModEPSBearerCtxtRej
          */
         TS24301Msg_ModEPSBearerCtxtRej *obj_ModEPSBearerCtxtRej;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-ModEPSBearerCtxtReq
          */
         TS24301Msg_ModEPSBearerCtxtReq *obj_ModEPSBearerCtxtReq;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-PDNConnectRej
          */
         TS24301Msg_PDNConnectRej *obj_PDNConnectRej;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-PDNConnectReq
          */
         TS24301Msg_PDNConnectReq *obj_PDNConnectReq;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-PDNDisconnRej
          */
         TS24301Msg_PDNDisconnRej *obj_PDNDisconnRej;
         /**
          * protoDiscr: epsSessMgmt
          * msgType: mt-PDNDisconnReq
          */
         TS24301Msg_PDNDisconnReq *obj_PDNDisconnReq;
      } u;
   } data;
} TS24301Msg_PDU;

EXTERN int NASEnc_TS24301Msg_PDU (OSCTXT* pctxt, TS24301Msg_PDU* pvalue);

EXTERN int NASDec_TS24301Msg_PDU (OSCTXT* pctxt, TS24301Msg_PDU* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_PDU (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_PDU* pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_AttachAccept
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_AttachAccept *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_AttachComplete
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_AttachComplete *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_AttachReject
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_AttachReject *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_AttachRequest
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_AttachRequest *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_AuthFailure
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_AuthFailure *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_AuthReject
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_AuthRequest
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_AuthRequest *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_AuthResponse
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_AuthResponse *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_CSServiceNotif
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_CSServiceNotif *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_DetachAccept
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_DetachRequest
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_DetachRequest *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_DLNASTransport
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_DLNASTransport *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_EMMInformation
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_EMMInformation *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_EMMStatus
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_EMMStatus value);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ExtServiceReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ExtServiceReq *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_GUTIReallocCmd
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_GUTIReallocCmd *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_GUTIReallocCmplt
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_IdentReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_IdentReq *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_IdentResp
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_IdentResp *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_SecModeCmd
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_SecModeCmd *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_SecModeCmplt
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_SecModeCmplt *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_SecModeReject
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_SecModeReject value);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ServiceReject
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ServiceReject *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_TrkAreaUpdAccept
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_TrkAreaUpdAccept *pvalue)
   ;

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_TrkAreaUpdCmplt
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_TrkAreaUpdReject
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_TrkAreaUpdReject *pvalue)
   ;

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_TrkAreaUpdRequest
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_TrkAreaUpdRequest *pvalue)
   ;

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ULNASTransport
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ULNASTransport *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ULGenNASTransport
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ULGenNASTransport *pvalue)
   ;

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_DLGenNASTransport
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_DLGenNASTransport *pvalue)
   ;

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ActvDedEPSBearerCtxtAcc
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ActvDedEPSBearerCtxtAcc 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ActvDedEPSBearerCtxtRej
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ActvDedEPSBearerCtxtRej 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ActvDedEPSBearerCtxtReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ActvDedEPSBearerCtxtReq 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ActvDfltEPSBearerCtxtAcc
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ActvDfltEPSBearerCtxtAcc 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ActvDfltEPSBearerCtxtRej
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ActvDfltEPSBearerCtxtRej 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ActvDfltEPSBearerCtxtReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ActvDfltEPSBearerCtxtReq 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_BearerResAllocRej
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_BearerResAllocRej *pvalue)
   ;

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_BearerResAllocReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_BearerResAllocReq *pvalue)
   ;

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_BearerResModRej
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_BearerResModRej *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_BearerResModReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_BearerResModReq *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_DeactEPSBearerCtxtAcc
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_DeactEPSBearerCtxtAcc 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_DeactEPSBearerCtxtReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_DeactEPSBearerCtxtReq 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ESMInfoReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ESMInfoResp
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ESMInfoResp *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ESMStatus
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ESMStatus value);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ModEPSBearerCtxtAcc
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ModEPSBearerCtxtAcc 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ModEPSBearerCtxtRej
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ModEPSBearerCtxtRej 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_ModEPSBearerCtxtReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_ModEPSBearerCtxtReq 
   *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_PDNConnectRej
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_PDNConnectRej *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_PDNConnectReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_PDNConnectReq *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_PDNDisconnRej
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_PDNDisconnRej *pvalue);

EXTERN void asn1SetTC_TS24301Msg_PDU_obj_PDNDisconnReq
   (OSCTXT* pctxt, TS24301Msg_PDU* pElem, TS24301Msg_PDNDisconnReq *pvalue);

EXTERN void asn1Init_TS24301Msg_PDU (TS24301Msg_PDU* pvalue);

/**************************************************************/
/*                                                            */
/*  ServiceRequest                                            */
/*                                                            */
/**************************************************************/
/*
 8.2.25 Service request 

ServiceRequest ::= SEQUENCE {
   l3HdrOpts [0] L3HdrOptions,
   protoDiscr [1] ProtoDiscr,
   ksiAndSequenceNumber [2] KSIAndSequenceNumber,
   shortMAC [3] ShortMAC
}
*/
typedef struct EXTERN TS24301Msg_ServiceRequest {
   TS24007L3_L3HdrOptions l3HdrOpts;
   TS24007L3_ProtoDiscr protoDiscr;
   TS24301IE_KSIAndSequenceNumber ksiAndSequenceNumber;
   TS24301IE_ShortMAC shortMAC;
} TS24301Msg_ServiceRequest;

EXTERN int NASEnc_TS24301Msg_ServiceRequest (OSCTXT* pctxt
   , TS24301Msg_ServiceRequest* pvalue);

EXTERN int NASDec_TS24301Msg_ServiceRequest (OSCTXT* pctxt
   , TS24301Msg_ServiceRequest* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_ServiceRequest (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_ServiceRequest* pvalue);

EXTERN void asn1Init_TS24301Msg_ServiceRequest (TS24301Msg_ServiceRequest* pvalue);

/**************************************************************/
/*                                                            */
/*  Notification                                              */
/*                                                            */
/**************************************************************/
/*
Notification ::= SEQUENCE {
   length [0] INTEGER (1),
   value [1] INTEGER (0..255)
}
*/
typedef struct EXTERN TS24301Msg_Notification {
   OSUINT8 length;
   OSUINT8 value;
} TS24301Msg_Notification;

EXTERN int NASEnc_TS24301Msg_Notification (OSCTXT* pctxt
   , TS24301Msg_Notification* pvalue);

EXTERN int NASDec_TS24301Msg_Notification (OSCTXT* pctxt
   , TS24301Msg_Notification* pvalue);

EXTERN int asn1PrtToStrm_TS24301Msg_Notification (OSCTXT *pctxt, 
   const char* name, const TS24301Msg_Notification* pvalue);

/* Value definitions */

#define ASN1V_ts24301Msg_mt_AttachAccept 66
#define ASN1V_ts24301Msg_mt_AttachComplete 67
#define ASN1V_ts24301Msg_mt_AttachReject 68
#define ASN1V_ts24301Msg_mt_AttachRequest 65
#define ASN1V_ts24301Msg_mt_AuthFailure 92
#define ASN1V_ts24301Msg_mt_AuthReject 84
#define ASN1V_ts24301Msg_mt_AuthRequest 82
#define ASN1V_ts24301Msg_mt_AuthResponse 83
#define ASN1V_ts24301Msg_mt_CSServiceNotif 100
#define ASN1V_ts24301Msg_mt_DetachAccept 70
#define ASN1V_ts24301Msg_mt_DetachRequest 69
#define ASN1V_ts24301Msg_mt_DLNASTransport 98
#define ASN1V_ts24301Msg_mt_EMMInformation 97
#define ASN1V_ts24301Msg_mt_EMMStatus 96
#define ASN1V_ts24301Msg_mt_ExtServiceReq 76
#define ASN1V_ts24301Msg_mt_GUTIReallocCmd 80
#define ASN1V_ts24301Msg_mt_GUTIReallocCmplt 81
#define ASN1V_ts24301Msg_mt_IdentReq 85
#define ASN1V_ts24301Msg_mt_IdentResp 86
#define ASN1V_ts24301Msg_mt_SecModeCmd 93
#define ASN1V_ts24301Msg_mt_SecModeCmplt 94
#define ASN1V_ts24301Msg_mt_SecModeReject 95
#define ASN1V_ts24301Msg_mt_ServiceReject 78
#define ASN1V_ts24301Msg_mt_TrkAreaUpdAccept 73
#define ASN1V_ts24301Msg_mt_TrkAreaUpdCmplt 74
#define ASN1V_ts24301Msg_mt_TrkAreaUpdReject 75
#define ASN1V_ts24301Msg_mt_TrkAreaUpdRequest 72
#define ASN1V_ts24301Msg_mt_ULNASTransport 99
#define ASN1V_ts24301Msg_mt_DLGenNASTransport 104
#define ASN1V_ts24301Msg_mt_ULGenNASTransport 105
#define ASN1V_ts24301Msg_mt_ActvDedEPSBearerCtxtAcc 198
#define ASN1V_ts24301Msg_mt_ActvDedEPSBearerCtxtRej 199
#define ASN1V_ts24301Msg_mt_ActvDedEPSBearerCtxtReq 197
#define ASN1V_ts24301Msg_mt_ActvDfltEPSBearerCtxtAcc 194
#define ASN1V_ts24301Msg_mt_ActvDfltEPSBearerCtxtRej 195
#define ASN1V_ts24301Msg_mt_ActvDfltEPSBearerCtxtReq 193
#define ASN1V_ts24301Msg_mt_BearerResAllocRej 213
#define ASN1V_ts24301Msg_mt_BearerResAllocReq 212
#define ASN1V_ts24301Msg_mt_BearerResModRej 215
#define ASN1V_ts24301Msg_mt_BearerResModReq 214
#define ASN1V_ts24301Msg_mt_DeactEPSBearerCtxtAcc 206
#define ASN1V_ts24301Msg_mt_DeactEPSBearerCtxtReq 205
#define ASN1V_ts24301Msg_mt_ESMInfoReq 217
#define ASN1V_ts24301Msg_mt_ESMInfoResp 218
#define ASN1V_ts24301Msg_mt_ESMStatus 232
#define ASN1V_ts24301Msg_mt_ModEPSBearerCtxtAcc 202
#define ASN1V_ts24301Msg_mt_ModEPSBearerCtxtRej 203
#define ASN1V_ts24301Msg_mt_ModEPSBearerCtxtReq 201
#define ASN1V_ts24301Msg_mt_Notification 219
#define ASN1V_ts24301Msg_mt_PDNConnectRej 209
#define ASN1V_ts24301Msg_mt_PDNConnectReq 208
#define ASN1V_ts24301Msg_mt_PDNDisconnRej 211
#define ASN1V_ts24301Msg_mt_PDNDisconnReq 210

#ifdef __cplusplus
}
#endif

#endif
