#ifndef EXTMSGID_H_
#define EXTMSGID_H_

/*GSM Radio parameter starts = 1000
 * WCDMA Radio parameter starts = 2000
 * LTE Radio parameter starts = 3000
 */

enum
{

	/*********For SYSTEM *********/
	SYSTEM_TIME_CMD = 101,
	/*********For GSM*************/
	GSM_L1_BRUST_METRICS =1000,
	GSM_PAGING_DATA,
	GRR_CELL_RESELECTION_MEASURMENT,
	GSM_RR_STATE_MESSAGE,
	GSM_RR_SIGNALING_MESSAGE,
	GSM_RR_RACH_CONTROL_PARAMETRES,
	GSM_RR_CELLINFORM,
	GSM_RR_CHANNEL_CONFIGURE,
	GSM_RR_SACCH_REPORT,
	GSM_RR_CONTROL_CHANNEL_DESC_PARAMS,
	GSM_RR_CELL_OPTIONS,
	GSM_RR_RADIO_LINK_TIMEOUT_COUNTER,
	GRR_PACKET_SYSTEM_INFORMATION,
	GSM_RLC_UL_STATISTICS,
	GPRS_OR_EGPRS_RLC_UPLINK_HEADER,
	GPRS_OR_EGPRS_RLC_DOWNLINK_HEADER,
	GPRS_EGPRS_RLC_UL_STATISTICS,
	GSM_RLC_DL_STATICS,
	RLC_DL_ACK_OR_NACK_PARAMETERS,
	EGPRS_RLC_DOWNLINK_ACK_OR_NACK,
	RLC_UL_ACK_OR_NACK_PARAMETERS,
	GSM_LLC_ME_INFORMATION,
	GSM_MAC_UL_TBF_ESTABLISH,
	MAC_DL_TBF_ESTABLISH,
	GPRS_OR_EGPRS_MAC_UPLINK_ACK_OR_NACK,
	GSM_TIMING_ADVANCE,
	GSM_L1_BRUST_METRICS_A,
	GSM_L1_MESSAGE_METRICS_A,
	EGPRS_RLC_UPLINK_ACK_NACK,
	GSM_L1_ENHANCED_MESSAGE_METRICS,
	GRR_STATE,
	LLC_PDU_STATISTICS,


	/*********For WCDMA*************/

	WCDMA_CELL_RESELECTION_PACKET =2000,
	WCDMA_L1_POWER_CONTROLL_WITH_COMPRESSED_MODE_PKT,
	WCDMA_PHYSICAL_CHANNELS_UPLINKS,
	WCDMA_PRACH,
	WCDMA_ACTIVE_SET,
	WCDMA_NEIGHBOR_SET,
	WCDMA_BLER,
	WCDMA_RRC_STATES,
	WCDMA_CELL_ID,
	WCDMA_RRC_SIGNALING_MESSAGE,
	WCDMA_RLC_DL_AM_CONFIGURATION_V1,
	WCDMA_RLC_UL_AM_STATISTICS_VER_2,
	WCDMA_RACH_PARAMETERS,
	WCDMA_RLC_DL_AM_STATISTICS,
	HS_DSCH_HARQ_STA_LOG_PKT,
	HS_CQI_STATISTICS,
	MAC_HS_CONFIG_LOG_PKT,
	MAC_HS_HEADER_LOG_PKT,
	MAC_HS_STATUS_LOG_PKT,
	MAC_HS_RESET_LOG_PKT,
	HS_DECODE_STATUS_LOG_PKT_VER_2,
	UL_HS_DPCCH_DEBUG_LOG_PkT,
	EUL_L1_MAC_STATISTICS_LOG_PKT,
	HS_DECODE_STATUS_LOG_PKT_EDITION_3,
	WCDMA_LIST_SEARCH_VER_5,
	WCDMA_TEMPORAL_ANALYSIS_ED2,
	WCDMA_PN_SEARCH_LOG_PACKET_ED2,

	/*********For LTE*************/

	MAC_RACH_CFG_SUBPACKET=3000,
	MAC_RACH_ATTEMPT_SUBPACKET,
	LTE_MAC_DL_TRANSPORT_BLOCK,
	MAC_UL_TB_SUBPACKET,
	MAC_UL_TX_STATS_SUBPACKET,
	LTE_RLC_DL_STATISTICS,
	LTE_RLC_UL_STATISTICS,
	LTE_OTA_MESSAGE,
	LTE_MIB_MESSAGE,
	LTE_SERVING_CELL_INFO,
	LTE_NAS_ESM_BEARER_CONTEXT_INFO,
	LTE_LL1_PDSCH_DECORDINR_RESULTS,
	LTE_LL1_PUSCH_TX_REPORT,
	LTE_ML1_PRACH_CONFIGURATION,
	LTE_ML1_DCI_INFORMATION_REPORT,
	LTE_ML1_SERVING_CELL_MEASUREMENT_AND_EVALUTION,
	LTE_ML1_SERVING_CELL_MEASUREMENT,
	LTE_LL1_PUCCH_CSF,
	LTE_NAS_EMM_STATE,
	LTE_ML1_RANDOM_ACCESS_REQUEST_REPORT,
	LTE_ML1_SRS_POWER_CONTROLL_REPORT,
	LTE_ML1_PDSCH_STAT_INDICATON,
	LTE_ML1_PUCCH_POWER_CONTROLL,
	LTE_ML1_RANDOM_ACCESS_RESPONSE_REPORT,
	PDCP_DL_STATISTICS,
	PDCP_UL_STATISTICS,
	LTE_ML1_PDCCH_PHICH_INDICATION_REPORT,
	LTE_ML1_GM_TX_REPORT,


/*******************for NAS ********************/

	UMTS_NAS_GMM_STATE=4000,
	UMTS_NAS_MM_STATE,
	UMTS_NAS_SIGNALING,
	UMTS_NAS_CS_CONNECTION_MANAGEMENT_CALL_SETUP,
	LTE_NAS_ESM_PLAIN_OTA_INCOMING_MSG,
	LTE_NAS_ESM_PLAIN_OTA_OUTGOING_MSG,
	UMTS_UE_DYNAMIC_ID,
	LTE_NAS_EMM_PLAIN_OTA_INCOMING_MSG,
	LTE_NAS_EMM_PLAIN_OTA_OUTGOING_MSG,

/****************EVENTS*****************************/
 /***LTE***/
	LTE_EVENT_RRC_STATE_CHANGE = 5000,       /*NL (ID: 1606) 18*/
	LTE_EVENT_NAS_EMM_OTA_INCOMING_MESSAGE , /*NL ID: 1966 19*/
	LTE_EVENT_NAS_EMM_OTA_OUTGOING_MESSAGE,  /*NL(ID: 1967) 20*/
	LTE_EVENT_NAS_ESM_OTA_INCOMING_MESSAGE,  /*NLID: 1968 21*/
	LTE_EVENT_NAS_ESM_OTA_OUTGOING_MESSAGE,  /*NlID: 1969 22*/
	LTE_EVENT_MOBILITY_FROM_E_UTRA_STARTED,  /*NL ID: 1615*/
	LTE_EVENT_MOBILITY_FROM_E_UTRA_FAILED,   /*NL ID:1616 */
	LTE_EVENT_NEW_CELL_INDICATION,           /*NL ID: 1611 */
	LTE_EVENT_RRC_DOWNLINK_MESSAGE,          /*NL ID: 1609*/
	LTE_EVENT_RRC_UPLINK_MESSAGE,            /*NL  ID: 1610 */
	LTE_HANDOVER_FAILURE, 					 /*NL ID :1613 */
	LTE_EVENT_INTER_RAT_RESELECTION_FROM_E_UTRAN_START, /*NL 1617*/
	LTE_EVENT_INTER_RAT_RESELECTION_FROM_E_UTRAN_END, /*NL 1618*/
    LTE_EVENT_INTER_RAT_REDIRECTION_FROM_E_UTRAN_START, /*NL :1807 */
	LTE_EVENT_INTER_RAT_REDIRECTION_FROM_E_UTRAN_END, /*NL : 1808 */
	LTE_EVENT_RADIO_LINK_FAILURE,     /* 1608 */
	LTE_EVENT_RADIO_LINK_FAILURE_STAT, /*1995*/
	LTE_EVENT_NAS_ESM_INCOMING_MESSAGE, /*1635*/
	LTE_EVENT_NAS_ESM_OUTGOING_MESSAGE,/*1636 */
	LTE_EVENT_RACH_ACCESS_START,/* 1501*/
	LTE_EVENT_RACH_ACCESS_RESULT, /*1503*/

/**********************CDMA*******************************************/
	  EVDO_AIR_LINK_SUMMARY = 6000, // not used
	  EVDO_POWER_LOG, //used
	  EVDO_STATE_LOG, //not used
	  EVDO_SECTOR_LOG, //not used
	  EVDO_FINGER_LOG, //used // to be removed
	  EVDO_PILOT_SETS_LOG_VER_2, //not used
	  ACTIVE_SET_LOG, //not used
	  SRCH_TNG_FINGER_STATUS, //used
	  SRCH_TNG_1X_SEARCHER_DUMP,//used
	  SRACH_TNG_GENERAL_STATUS, //used
	  SRCH_TNG_DEMOD_INFO, //used
	  SRCH_TNG_SLEEP_STATS, //used
	  SRCH_TNG_QUICK_PAGING_CHANNEL_INFO,//not needed
	  SRCH_TNG_ACQUISITION_INFO, //not needed
	  SRCH_TNG_FINGER_CHANNEL_ESTIMATE, //used
	  EVDO_REV_ARL_GAINS, //not used
	  EVDO_MULTICARRIER_POWER, //used
	  EVDO_PILOT_SETS_LOG_VER_3, //not used
	  EVDO_DEBUG_DISPLAY,//not used
	  CM_PHONE_EVENT,//not used
	  EVDO_EQUALIZER_DATA,//not used
	//  CM_SERVING_SYSTEM_EVENT,//not used
	 // POSITION_ENGINE_FULL,//not used
	  TEMPORAL_ANALYZER_GRAPH //used // request
 	 // EXTENDED_BUILD_ID_RESPONSE // used  request-response
};

u_int16_t convert_into_external_code (u_int16_t command_code);
int  buffer_to_file_write(char *timebuff,int timelength,u_int16_t command_code,char *buff, int len);
#endif /* EXTMSGID_H_ */
