/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.1, Date: 04-Mar-2013.
 */
#include "CSNRR.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

EXTERN const char* gs_CSNRR_TBCDString_CharSet =
"#*0123456789abc";

EXTERN const char* gs_CSNRR_TBCDString3_CharSet =
"#*0123456789abc";

EXTERN const char* gs_CSNRR_GSMRR_IMSI_CharSet =
"#*0123456789abc";

EXTERN const char* gs_CSNRR_GSMRR_IMEI_CharSet =
"#*0123456789abc";

EXTERN const char* gs_CSNRR_GSMRR_IMEISV_CharSet =
"#*0123456789abc";

static const OSEnumItem GSMRRProtoDiscr_ENUMTAB[] = {
   { OSUTF8("bcc"), 1, 3, 4 },
   { OSUTF8("callCtrl"), 3, 8, 0 },
   { OSUTF8("epsMobMgmt"), 7, 10, 3 },
   { OSUTF8("epsSessMgmt"), 2, 11, 1 },
   { OSUTF8("gcc"), 0, 3, 6 },
   { OSUTF8("gprsMobMgmt"), 8, 11, 7 },
   { OSUTF8("gttp"), 4, 4, 9 },
   { OSUTF8("mobMgmt"), 5, 7, 2 },
   { OSUTF8("nonCallSS"), 11, 9, 5 },
   { OSUTF8("rrMgmt"), 6, 6, 11 },
   { OSUTF8("sessMgmt"), 10, 8, 10 },
   { OSUTF8("sms"), 9, 3, 8 }
} ;
#define GSMRRProtoDiscr_ENUMTABSIZE 12

const OSUTF8CHAR* GSMRRProtoDiscr_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < GSMRRProtoDiscr_ENUMTABSIZE) {
      return GSMRRProtoDiscr_ENUMTAB
         [GSMRRProtoDiscr_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int GSMRRProtoDiscr_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, GSMRRProtoDiscr* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);

   return GSMRRProtoDiscr_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int GSMRRProtoDiscr_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, GSMRRProtoDiscr* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, GSMRRProtoDiscr_ENUMTAB, 
      GSMRRProtoDiscr_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (GSMRRProtoDiscr)GSMRRProtoDiscr_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem GSMRRMBSEnum_ENUMTAB[] = {
   { OSUTF8("mbs0"), 0, 4, 0 },
   { OSUTF8("mbs1"), 1, 4, 1 },
   { OSUTF8("mbs2"), 2, 4, 2 },
   { OSUTF8("mbs4"), 4, 4, 3 },
   { OSUTF8("mbs5"), 5, 4, 4 },
   { OSUTF8("mbs6"), 6, 4, 5 }
} ;
#define GSMRRMBSEnum_ENUMTABSIZE 6

const OSUTF8CHAR* GSMRRMBSEnum_ToString (OSINT32 value)
{
   OSINT32 idx = rtxLookupEnumByValue (value, GSMRRMBSEnum_ENUMTAB, 
      GSMRRMBSEnum_ENUMTABSIZE);

   if (idx >= 0 && idx < GSMRRMBSEnum_ENUMTABSIZE) {
      return GSMRRMBSEnum_ENUMTAB[idx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int GSMRRMBSEnum_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, GSMRRMBSEnum* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return GSMRRMBSEnum_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int GSMRRMBSEnum_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, GSMRRMBSEnum* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, GSMRRMBSEnum_ENUMTAB, 
      GSMRRMBSEnum_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (GSMRRMBSEnum)GSMRRMBSEnum_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem GSMRRGSM400Struct_bandsSupported_ENUMTAB[] = {
   { OSUTF8("band1"), 1, 5, 0 },
   { OSUTF8("band2"), 2, 5, 1 },
   { OSUTF8("band3"), 3, 5, 2 }
} ;
#define GSMRRGSM400Struct_bandsSupported_ENUMTABSIZE 3

const OSUTF8CHAR* GSMRRGSM400Struct_bandsSupported_ToString (OSINT32 value)
{
   OSINT32 idx = value - 1;

   if (idx >= 0 && idx < GSMRRGSM400Struct_bandsSupported_ENUMTABSIZE) {
      return GSMRRGSM400Struct_bandsSupported_ENUMTAB
         [GSMRRGSM400Struct_bandsSupported_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int GSMRRGSM400Struct_bandsSupported_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, GSMRRGSM400Struct_bandsSupported* pvalue)
{
   OSSIZE valueLen = rtxUTF8LenBytes (value);
   return GSMRRGSM400Struct_bandsSupported_ToEnum2 (pctxt, value, valueLen, pvalue);
}

int GSMRRGSM400Struct_bandsSupported_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, 
      GSMRRGSM400Struct_bandsSupported* pvalue)
{
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      GSMRRGSM400Struct_bandsSupported_ENUMTAB, 
      GSMRRGSM400Struct_bandsSupported_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (GSMRRGSM400Struct_bandsSupported)
         GSMRRGSM400Struct_bandsSupported_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

void asn1Init_MCCMNCPair (MCCMNCPair* pvalue)
{
	if (0 == pvalue) return;

	pvalue->mcc[0] = '\0';
	pvalue->mnc[0] = '\0';
}

void asn1Init_GSMRRMobileIdentity_TMGI (GSMRRMobileIdentity_TMGI* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_MCCMNCPair (&pvalue->mcc_mnc);
}

void asn1Init_GSMRRMobileIdentity (GSMRRMobileIdentity* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

void asn1Init_GSMRRMobileIdentity_top (GSMRRMobileIdentity_top* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRMobileIdentity (&pvalue->mobid);
}

void asn1Init_GSMRRPageMode (GSMRRPageMode* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spare = 0;
}

void asn1Init_GSMRRPagingReqType1 (GSMRRPagingReqType1* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRPageMode (&pvalue->pagemode);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity1);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity2);
}

void asn1Init_GSMRRPagingReqType2 (GSMRRPagingReqType2* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRPageMode (&pvalue->pagemode);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity1);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity2);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity3);
}

void asn1Init_GSMRRPagingReqType3 (GSMRRPagingReqType3* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRPageMode (&pvalue->pagemode);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity1);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity2);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity3);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity4);
}

void asn1Init_GSMRRCipheringKeySeqNum (GSMRRCipheringKeySeqNum* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spare = 0;
}

void asn1Init_GSMRRPagingResp (GSMRRPagingResp* pvalue)
{
   if (0 == pvalue) return;
   pvalue->sparehalfoctet = 0;
   asn1Init_GSMRRCipheringKeySeqNum (&pvalue->cipheringkeyseqnum);
   asn1Init_GSMRRMobileIdentity_top (&pvalue->mobileIdentity);
}

void asn1Init_GSMRRMeasurementResults_octet4 (
   GSMRRMeasurementResults_octet4* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spare = 0;
}

void asn1Init_GSMRRMeasurementResults (GSMRRMeasurementResults* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRMeasurementResults_octet4 (&pvalue->octet4);
}

void asn1Init_GSMRRMeasurementReport (GSMRRMeasurementReport* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRMeasurementResults (&pvalue->measurementresults);
}

void asn1Init_GSMRRType8PSKStruct (GSMRRType8PSKStruct* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
}

void asn1Init_GSMRRGERANIuModeCap (GSMRRGERANIuModeCap* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spareBits.numbits = 0;
}

void asn1Init_GSMRRDTMGPRSStruct (GSMRRDTMGPRSStruct* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
}

void asn1Init_GSMRRMobileStationClassmark3_dtmGPRSStruct2 (
   GSMRRMobileStationClassmark3_dtmGPRSStruct2* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
}

void asn1Init_GSMRRMobileStationClassmark3 (
   GSMRRMobileStationClassmark3* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_GSMRRType8PSKStruct (&pvalue->an_8_PSKStruct);
   asn1Init_GSMRRDTMGPRSStruct (&pvalue->dtmGPRSStruct);
   asn1Init_GSMRRGERANIuModeCap (&pvalue->geranIuModeCap);
   pvalue->zerobit = FALSE;
   asn1Init_GSMRRMobileStationClassmark3_dtmGPRSStruct2 (&pvalue->dtmGPRSStruct2);
   pvalue->spareBits.numbits = 0;
   pvalue->spareBits.data = 0;
}

void asn1Init_GSMRRClassmarkChange (GSMRRClassmarkChange* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRMobileStationClassmark3 (&pvalue->additionalmobilestationclassmarkinfo);
}

void asn1Init_GSMRRRoutingAreaIdentification (
   GSMRRRoutingAreaIdentification* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_MCCMNCPair (&pvalue->mcc_mnc);
}

void asn1Init_GSMRRServiceSupport (GSMRRServiceSupport* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spare = 0;
}

void asn1Init_GSMRRGPRSSuspensionRequest (GSMRRGPRSSuspensionRequest* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRRoutingAreaIdentification (&pvalue->routingareaidentification);
   asn1Init_GSMRRServiceSupport (&pvalue->servicesupport);
}

void asn1Init_ARFCN (ARFCN* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spare = 0;
}

void asn1Init_HoppingChannel (HoppingChannel* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

void asn1Init_HoppingChannel2 (HoppingChannel2* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

void asn1Init_GSMRRChannelDescription2 (GSMRRChannelDescription2* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_HoppingChannel (&pvalue->hoppingchannel);
}

void asn1Init_GSMRRChannelDescription (GSMRRChannelDescription* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_HoppingChannel2 (&pvalue->hoppingchannel);
}

void asn1Init_GSMRRPowerCommand (GSMRRPowerCommand* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spare = 0;
}

void asn1Init_GSMRRAssignmentCommand (GSMRRAssignmentCommand* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRChannelDescription2 (&pvalue->descriptionofthefirstchannelaftertime);
   asn1Init_GSMRRPowerCommand (&pvalue->powercommand);
   asn1Init_GSMRRChannelDescription (&pvalue->descriptionofthesecondchannelaftertime);
   asn1Init_GSMRRChannelDescription2 (&pvalue->descriptionofthefirstchannelbeforetime);
   asn1Init_GSMRRChannelDescription (&pvalue->descriptionofthesecondchannelbeforetime);
}

void asn1Init_GSMRRDedicatedModeOrTbf (GSMRRDedicatedModeOrTbf* pvalue)
{
   if (0 == pvalue) return;
   pvalue->spare = 0;
}

void asn1Init_GSMRRChannelDescriptionChoice (
   GSMRRChannelDescriptionChoice* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

void asn1Init_ImmediateAssign (ImmediateAssign* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_GSMRRPageMode (&pvalue->pagemode);
   asn1Init_GSMRRDedicatedModeOrTbf (&pvalue->dedicatedmodeortbf);
   asn1Init_GSMRRChannelDescriptionChoice (&pvalue->channeldescriptionchoice);
}

