/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.1, Date: 04-Mar-2013.
 */
#include "CSNRR.h"
#include "rtsrc/rtPrintToStream.h"
#include "rtxsrc/rtxCommon.h"
#include "rtxsrc/rtxDiagBitTrace.h"

int asn1PrtToStrm_TBCDString (OSCTXT *pctxt, 
		const char* name, const TBCDString pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamCharStr (pctxt, name, pvalue);
	return 0;
}

int asn1PrtToStrm_TBCDString3 (OSCTXT *pctxt, 
		const char* name, const TBCDString3 pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamCharStr (pctxt, name, pvalue);
	return 0;
}

int asn1PrtToStrm_GSMRR_IMSI (OSCTXT *pctxt, 
		const char* name, const GSMRR_IMSI pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamCharStr (pctxt, name, pvalue);
	return 0;
}

int asn1PrtToStrm_GSMRR_IMEI (OSCTXT *pctxt, 
		const char* name, const GSMRR_IMEI pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamCharStr (pctxt, name, pvalue);
	return 0;
}

int asn1PrtToStrm_GSMRR_IMEISV (OSCTXT *pctxt, 
		const char* name, const GSMRR_IMEISV pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamCharStr (pctxt, name, pvalue);
	return 0;
}

int asn1PrtToStrm_GSMRRProtoDiscr (OSCTXT *pctxt, 
		const char* name, const GSMRRProtoDiscr* pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtxPrintToStream (pctxt, name);
	switch (*pvalue) {
		case 0:
			rtxPrintToStream (pctxt, " = gcc\n");
			break;
		case 1:
			rtxPrintToStream (pctxt, " = bcc\n");
			break;
		case 2:
			rtxPrintToStream (pctxt, " = epsSessMgmt\n");
			break;
		case 3:
			rtxPrintToStream (pctxt, " = callCtrl\n");
			break;
		case 4:
			rtxPrintToStream (pctxt, " = gttp\n");
			break;
		case 5:
			rtxPrintToStream (pctxt, " = mobMgmt\n");
			break;
		case 6:
			rtxPrintToStream (pctxt, " = rrMgmt\n");
			break;
		case 7:
			rtxPrintToStream (pctxt, " = epsMobMgmt\n");
			break;
		case 8:
			rtxPrintToStream (pctxt, " = gprsMobMgmt\n");
			break;
		case 9:
			rtxPrintToStream (pctxt, " = sms\n");
			break;
		case 10:
			rtxPrintToStream (pctxt, " = sessMgmt\n");
			break;
		case 11:
			rtxPrintToStream (pctxt, " = nonCallSS\n");
			break;
		default:
			rtxPrintToStream (pctxt," = ???\n");
			break;
	}

	return 0;
}

int asn1PrtToStrm_GSMRRRSupport (OSCTXT *pctxt, 
		const char* name, const GSMRRRSupport* pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, name, *pvalue);
	return 0;
}

int asn1PrtToStrm_GSMRRHSCSDMultiSlotCap (OSCTXT *pctxt, 
		const char* name, const GSMRRHSCSDMultiSlotCap* pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, name, *pvalue);
	return 0;
}

int asn1PrtToStrm_GSMRRMBSEnum (OSCTXT *pctxt, 
		const char* name, const GSMRRMBSEnum* pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtxPrintToStream (pctxt, name);
	switch (*pvalue) {
		case 0:
			rtxPrintToStream (pctxt, " = mbs0\n");
			break;
		case 1:
			rtxPrintToStream (pctxt, " = mbs1\n");
			break;
		case 2:
			rtxPrintToStream (pctxt, " = mbs2\n");
			break;
		case 4:
			rtxPrintToStream (pctxt, " = mbs4\n");
			break;
		case 5:
			rtxPrintToStream (pctxt, " = mbs5\n");
			break;
		case 6:
			rtxPrintToStream (pctxt, " = mbs6\n");
			break;
		default:
			rtxPrintToStream (pctxt," = ???\n");
	}

	return 0;
}

int asn1PrtToStrm_GSMRRGSM400Struct_bandsSupported (OSCTXT *pctxt, 
		const char* name, const GSMRRGSM400Struct_bandsSupported* pvalue)
{
	rtPrintToStreamIndent (pctxt);
	rtxPrintToStream (pctxt, name);
	switch (*pvalue) {
		case 1:
			rtxPrintToStream (pctxt, " = band1\n");
			break;
		case 2:
			rtxPrintToStream (pctxt, " = band2\n");
			break;
		case 3:
			rtxPrintToStream (pctxt, " = band3\n");
			break;
		default:
			rtxPrintToStream (pctxt," = ???\n");
	}

	return 0;
}

int asn1PrtToStrm_MCCMNCPair (OSCTXT *pctxt, 
		const char* name, const MCCMNCPair* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	asn1PrtToStrm_TBCDString3 (pctxt, "mcc", pvalue->mcc);

	asn1PrtToStrm_TBCDString3 (pctxt, "mnc", pvalue->mnc);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileIdentity_TMGI (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileIdentity_TMGI* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "mbmsSessIdInd", pvalue->mbmsSessIdInd);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "mccMncInd", pvalue->mccMncInd);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "mbmsServiceID", 3, pvalue->mbmsServiceID);

	asn1PrtToStrm_MCCMNCPair (pctxt, "mcc_mnc", &pvalue->mcc_mnc);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "mbmsSessionID", pvalue->mbmsSessionID);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileIdentity (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileIdentity* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	switch (pvalue->t)
	{
		/* imsi */
		case 1:
			{
				asn1PrtToStrm_GSMRR_IMSI (pctxt, "imsi", pvalue->u.imsi);
				break;
			}
			/* imei */
		case 2:
			{
				asn1PrtToStrm_GSMRR_IMEI (pctxt, "imei", pvalue->u.imei);
				break;
			}
			/* imeisv */
		case 3:
			{
				asn1PrtToStrm_GSMRR_IMEISV (pctxt, "imeisv", pvalue->u.imeisv);
				break;
			}
			/* tmsi */
		case 4:
			{
				rtPrintToStreamIndent (pctxt);
				rtPrintToStreamHexStr (pctxt, "tmsi", 4, pvalue->u.tmsi);
				break;
			}
			/* tmgi */
		case 5:
			{
				asn1PrtToStrm_GSMRRMobileIdentity_TMGI (pctxt, "tmgi", &pvalue->u.tmgi);
				break;
			}
		default:;
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileIdentity_top (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileIdentity_top* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "lengthmobID", pvalue->lengthmobID);


	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "oddevenindic", pvalue->oddevenindic);

	asn1PrtToStrm_GSMRRMobileIdentity (pctxt, "mobid", &pvalue->mobid);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRPageMode (OSCTXT *pctxt, 
		const char* name, const GSMRRPageMode* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "pm", pvalue->pm);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRChannelNeeded (OSCTXT *pctxt, 
		const char* name, const GSMRRChannelNeeded* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "channelsecond", pvalue->channelsecond);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "channelfirst", pvalue->channelfirst);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRPagingReqType1 (OSCTXT *pctxt, 
		const char* name, const GSMRRPagingReqType1* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "presence_bitmask", pvalue->presence_bitmask);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "msgType", pvalue->msgType);

	asn1PrtToStrm_GSMRRChannelNeeded (pctxt, "channelneedmob1and2", &pvalue->channelneedmob1and2);

	asn1PrtToStrm_GSMRRPageMode (pctxt, "pagemode", &pvalue->pagemode);

	asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity1", &pvalue->mobileIdentity1);

	if (pvalue->presence_bitmask & GSM_PAGING_REQ1_MOBILE_IDENTITY2_PRESENT)
	{
		asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity2", &pvalue->mobileIdentity2);
	}
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "p1restoctets", 17, pvalue->p1restoctets);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRPagingReqType2 (OSCTXT *pctxt, 
		const char* name, const GSMRRPagingReqType2* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "presence_bitmask", pvalue->presence_bitmask);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "pagingreq2msgType", pvalue->pagingreq2msgType);

	asn1PrtToStrm_GSMRRChannelNeeded (pctxt, "channelneedmob1and2", &pvalue->channelneedmob1and2);

	asn1PrtToStrm_GSMRRPageMode (pctxt, "pagemode", &pvalue->pagemode);

	asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity1", &pvalue->mobileIdentity1);

	asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity2", &pvalue->mobileIdentity2);

	if (pvalue->presence_bitmask & GSM_PAGING_REQ2_MOBILE_IDENTITY3_PRESENT)
	{
		asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity3", &pvalue->mobileIdentity3);
	}
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "p2restoctets", 11, pvalue->p2restoctets);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRPagingReqType3 (OSCTXT *pctxt, 
		const char* name, const GSMRRPagingReqType3* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "pagingreq3msgType", pvalue->pagingreq3msgType);

	asn1PrtToStrm_GSMRRChannelNeeded (pctxt, "channelneedmob1and2", &pvalue->channelneedmob1and2);

	asn1PrtToStrm_GSMRRPageMode (pctxt, "pagemode", &pvalue->pagemode);

	asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity1", &pvalue->mobileIdentity1);

	asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity2", &pvalue->mobileIdentity2);

	asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity3", &pvalue->mobileIdentity3);

	asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity4", &pvalue->mobileIdentity4);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "p3restoctets", 3, pvalue->p3restoctets);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRCipheringKeySeqNum (OSCTXT *pctxt, 
		const char* name, const GSMRRCipheringKeySeqNum* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "keysequence", pvalue->keysequence);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileStationClassmark1 (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileStationClassmark1* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "revLevel", pvalue->revLevel);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "esInd", pvalue->esInd);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "a5_1_alg", pvalue->a5_1_alg);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rfPowerCap", pvalue->rfPowerCap);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileStationClassmark2_octet4 (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileStationClassmark2_octet4* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "psCapability", pvalue->psCapability);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "ssScreeningInd", pvalue->ssScreeningInd);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "smCapability", pvalue->smCapability);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "vbsNotifRecept", pvalue->vbsNotifRecept);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "vgcsNotifRecept", pvalue->vgcsNotifRecept);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "fcFreqCap", pvalue->fcFreqCap);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileStationClassmark2_octet5 (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileStationClassmark2_octet5* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "cm3", pvalue->cm3);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "lcsvaCap", pvalue->lcsvaCap);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "ucs2Treatment", pvalue->ucs2Treatment);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "soLSA", pvalue->soLSA);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "cmsp", pvalue->cmsp);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "a5_3_alg", pvalue->a5_3_alg);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "a5_2_alg", pvalue->a5_2_alg);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileStationClassmark2 (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileStationClassmark2* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "lengthmobilestationclassmark2", pvalue->lengthmobilestationclassmark2);

	asn1PrtToStrm_GSMRRMobileStationClassmark1 (pctxt, "cm1", &pvalue->cm1);

	asn1PrtToStrm_GSMRRMobileStationClassmark2_octet4 (pctxt, "octet4", &pvalue->octet4);

	asn1PrtToStrm_GSMRRMobileStationClassmark2_octet5 (pctxt, "octet5", &pvalue->octet5);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRPagingResp (OSCTXT *pctxt, 
		const char* name, const GSMRRPagingResp* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "pagingrespmsgType", pvalue->pagingrespmsgType);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "sparehalfoctet", pvalue->sparehalfoctet);

	asn1PrtToStrm_GSMRRCipheringKeySeqNum (pctxt, "cipheringkeyseqnum", &pvalue->cipheringkeyseqnum);

	asn1PrtToStrm_GSMRRMobileStationClassmark2 (pctxt, "mobilestationclassmark2", &pvalue->mobilestationclassmark2);

	asn1PrtToStrm_GSMRRMobileIdentity_top (pctxt, "mobileIdentity", &pvalue->mobileIdentity);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet2 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet2* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "baUsed", pvalue->baUsed);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "dtxUsed", pvalue->dtxUsed);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevFullServingCell", pvalue->rxlevFullServingCell);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet3 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet3* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "baUsed3g", pvalue->baUsed3g);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "measvalid", pvalue->measvalid);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevSubServingCell", pvalue->rxlevSubServingCell);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet4 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet4* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxqualFullServingCell", pvalue->rxqualFullServingCell);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxqualSubServingCell", pvalue->rxqualSubServingCell);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "noNCellMHighPart", pvalue->noNCellMHighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet5 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet5* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "noNCellMLowPart", pvalue->noNCellMLowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell1", pvalue->rxlevNCell1);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet6 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet6* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bcchFreqNCell1", pvalue->bcchFreqNCell1);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bsicNCell1HighPart", pvalue->bsicNCell1HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet7 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet7* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bsicNCellLowPart", pvalue->bsicNCellLowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell2HighPart", pvalue->rxlevNCell2HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet8 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet8* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "rxlevNCell2LowPart", pvalue->rxlevNCell2LowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bcchFreqNCell2", pvalue->bcchFreqNCell2);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bsicNCell2HighPart", pvalue->bsicNCell2HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet9 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet9* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bsicNCell2LowPart", pvalue->bsicNCell2LowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell3HighPart", pvalue->rxlevNCell3HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet10 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet10* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell3LowPart", pvalue->rxlevNCell3LowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bcchFreqNCell3", pvalue->bcchFreqNCell3);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "bsicNCell3HighPart", pvalue->bsicNCell3HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet11 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet11* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bsicNCell3HighPart", pvalue->bsicNCell3HighPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell4HighPart", pvalue->rxlevNCell4HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet12 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet12* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell4LowPart", pvalue->rxlevNCell4LowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bcchFreqNCell4", pvalue->bcchFreqNCell4);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet13 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet13* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bsicNCell4", pvalue->bsicNCell4);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell5HighPart", pvalue->rxlevNCell5HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet14 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet14* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell5LowPart", pvalue->rxlevNCell5LowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bcchFreqNCell5HighPart", pvalue->bcchFreqNCell5HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet15 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet15* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "bcchFreqNCell5LowPart", pvalue->bcchFreqNCell5LowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bsicNCell5", pvalue->bsicNCell5);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "rxlevNCell6HighPart", pvalue->rxlevNCell6HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet16 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet16* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rxlevNCell6LowPart", pvalue->rxlevNCell6LowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bcchFreqNCell6HighPart", pvalue->bcchFreqNCell6HighPart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults_octet17 (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults_octet17* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bcchFreqNCell6LowPart", pvalue->bcchFreqNCell6LowPart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "bsicNCell6", pvalue->bsicNCell6);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementResults (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementResults* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	asn1PrtToStrm_GSMRRMeasurementResults_octet2 (pctxt, "octet2", &pvalue->octet2);

	asn1PrtToStrm_GSMRRMeasurementResults_octet3 (pctxt, "octet3", &pvalue->octet3);

	asn1PrtToStrm_GSMRRMeasurementResults_octet4 (pctxt, "octet4", &pvalue->octet4);

	asn1PrtToStrm_GSMRRMeasurementResults_octet5 (pctxt, "octet5", &pvalue->octet5);

	asn1PrtToStrm_GSMRRMeasurementResults_octet6 (pctxt, "octet6", &pvalue->octet6);

	asn1PrtToStrm_GSMRRMeasurementResults_octet7 (pctxt, "octet7", &pvalue->octet7);

	asn1PrtToStrm_GSMRRMeasurementResults_octet8 (pctxt, "octet8", &pvalue->octet8);

	asn1PrtToStrm_GSMRRMeasurementResults_octet9 (pctxt, "octet9", &pvalue->octet9);

	asn1PrtToStrm_GSMRRMeasurementResults_octet10 (pctxt, "octet10", &pvalue->octet10);

	asn1PrtToStrm_GSMRRMeasurementResults_octet11 (pctxt, "octet11", &pvalue->octet11);

	asn1PrtToStrm_GSMRRMeasurementResults_octet12 (pctxt, "octet12", &pvalue->octet12);

	asn1PrtToStrm_GSMRRMeasurementResults_octet13 (pctxt, "octet13", &pvalue->octet13);

	asn1PrtToStrm_GSMRRMeasurementResults_octet14 (pctxt, "octet14", &pvalue->octet14);

	asn1PrtToStrm_GSMRRMeasurementResults_octet15 (pctxt, "octet15", &pvalue->octet15);

	asn1PrtToStrm_GSMRRMeasurementResults_octet16 (pctxt, "octet16", &pvalue->octet16);

	asn1PrtToStrm_GSMRRMeasurementResults_octet17 (pctxt, "octet17", &pvalue->octet17);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMeasurementReport (OSCTXT *pctxt, 
		const char* name, const GSMRRMeasurementReport* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "measurementreportmsgType", pvalue->measurementreportmsgType);

	asn1PrtToStrm_GSMRRMeasurementResults (pctxt, "measurementresults", &pvalue->measurementresults);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRCipheringModeSetting (OSCTXT *pctxt, 
		const char* name, const GSMRRCipheringModeSetting* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "algorithmidentifier", pvalue->algorithmidentifier);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "sc", pvalue->sc);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRCipherResponse (OSCTXT *pctxt, 
		const char* name, const GSMRRCipherResponse* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "cr", pvalue->cr);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMSMeasurementCap (OSCTXT *pctxt, 
		const char* name, const GSMRRMSMeasurementCap* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "smsValue", pvalue->smsValue);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "smValue", pvalue->smValue);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRType8PSKStruct (OSCTXT *pctxt, 
		const char* name, const GSMRRType8PSKStruct* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "modulationCap", pvalue->modulationCap);

	if (pvalue->m.rfPowerCap1Present) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "rfPowerCap1", pvalue->rfPowerCap1);
	}

	if (pvalue->m.rfPowerCap2Present) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "rfPowerCap2", pvalue->rfPowerCap2);
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRGERANIuModeCap (OSCTXT *pctxt, 
		const char* name, const GSMRRGERANIuModeCap* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "length", pvalue->length);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "floIuCap", pvalue->floIuCap);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBitStrBraceText (pctxt, "spareBits", pvalue->spareBits.numbits, pvalue->spareBits.data);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRA5Bits (OSCTXT *pctxt, 
		const char* name, const GSMRRA5Bits* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "a5_7", pvalue->a5_7);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "a5_6", pvalue->a5_6);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "a5_5", pvalue->a5_5);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "a5_4", pvalue->a5_4);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMultibandSupported (OSCTXT *pctxt, 
		const char* name, const GSMRRMultibandSupported* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	asn1PrtToStrm_GSMRRMBSEnum (pctxt, "supported", &pvalue->supported);

	asn1PrtToStrm_GSMRRA5Bits (pctxt, "a5bits", &pvalue->a5bits);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "assocRadioCap2", pvalue->assocRadioCap2);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "assocRadioCap1", pvalue->assocRadioCap1);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRGSM400Struct (OSCTXT *pctxt, 
		const char* name, const GSMRRGSM400Struct* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	asn1PrtToStrm_GSMRRGSM400Struct_bandsSupported (pctxt, "bandsSupported", &pvalue->bandsSupported);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "assocRadioCap", pvalue->assocRadioCap);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRDTMGPRSStruct (OSCTXT *pctxt, 
		const char* name, const GSMRRDTMGPRSStruct* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "dtmGPRSMultiSlotClass", pvalue->dtmGPRSMultiSlotClass);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "singleSlotDTM", pvalue->singleSlotDTM);

	if (pvalue->m.dtmEGPRSMultiSlotClassPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "dtmEGPRSMultiSlotClass", pvalue->dtmEGPRSMultiSlotClass);
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileStationClassmark3_extDtmGPRSStruct (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileStationClassmark3_extDtmGPRSStruct* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "extDtmGPRSMultiSlotClass", pvalue->extDtmGPRSMultiSlotClass);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "extDtmEGPRSMultiSlotClass", pvalue->extDtmEGPRSMultiSlotClass);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileStationClassmark3_dtmGPRSStruct2 (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileStationClassmark3_dtmGPRSStruct2* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "dtmGPRSHighMultiSlotClass", pvalue->dtmGPRSHighMultiSlotClass);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "offsetRequired", pvalue->offsetRequired);

	if (pvalue->m.dtmEGPRSHighMultiSlotClassPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "dtmEGPRSHighMultiSlotClass", pvalue->dtmEGPRSHighMultiSlotClass);
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileStationClassmark3 (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileStationClassmark3* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "length", pvalue->length);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "spare", pvalue->spare);

	asn1PrtToStrm_GSMRRMultibandSupported (pctxt, "multiband", &pvalue->multiband);

	if (pvalue->m.rSupportPresent) {
		asn1PrtToStrm_GSMRRRSupport (pctxt, "rSupport", &pvalue->rSupport);
	}

	if (pvalue->m.hscsdMultiSlotCapPresent) {
		asn1PrtToStrm_GSMRRHSCSDMultiSlotCap (pctxt, "hscsdMultiSlotCap", &pvalue->hscsdMultiSlotCap);
	}

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "ucs2Treatment", pvalue->ucs2Treatment);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "extMeasurementCap", pvalue->extMeasurementCap);

	if (pvalue->m.msMeasurementCapPresent) {
		asn1PrtToStrm_GSMRRMSMeasurementCap (pctxt, "msMeasurementCap", &pvalue->msMeasurementCap);
	}

	if (pvalue->m.msPositioningMethodCapPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "msPositioningMethodCap", pvalue->msPositioningMethodCap);
	}

	if (pvalue->m.ecsdMultiSlotCapPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "ecsdMultiSlotCap", pvalue->ecsdMultiSlotCap);
	}

	if (pvalue->m.an_8_PSKStructPresent) {
		asn1PrtToStrm_GSMRRType8PSKStruct (pctxt, "an_8_PSKStruct", &pvalue->an_8_PSKStruct);
	}

	if (pvalue->m.gsm400StructPresent) {
		asn1PrtToStrm_GSMRRGSM400Struct (pctxt, "gsm400Struct", &pvalue->gsm400Struct);
	}

	if (pvalue->m.gsm850AssocRadioCapPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "gsm850AssocRadioCap", pvalue->gsm850AssocRadioCap);
	}

	if (pvalue->m.gsm1900AssocRadioCapPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "gsm1900AssocRadioCap", pvalue->gsm1900AssocRadioCap);
	}

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "umtsFDDRadioAccessTechCap", pvalue->umtsFDDRadioAccessTechCap);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "umts384McpsTDDRadioAccessTechCap", pvalue->umts384McpsTDDRadioAccessTechCap);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "cdma2000RadioAccessTechCap", pvalue->cdma2000RadioAccessTechCap);

	if (pvalue->m.dtmGPRSStructPresent) {
		asn1PrtToStrm_GSMRRDTMGPRSStruct (pctxt, "dtmGPRSStruct", &pvalue->dtmGPRSStruct);
	}

	if (pvalue->m.singleBandSupportPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "singleBandSupport", pvalue->singleBandSupport);
	}

	if (pvalue->m.gsm750AssocRadioCapPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "gsm750AssocRadioCap", pvalue->gsm750AssocRadioCap);
	}

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "umts1_28McpsTDDRadioAccessTechCap", pvalue->umts1_28McpsTDDRadioAccessTechCap);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "geranFeaturePackage1", pvalue->geranFeaturePackage1);

	if (pvalue->m.extDtmGPRSStructPresent) {
		asn1PrtToStrm_GSMRRMobileStationClassmark3_extDtmGPRSStruct (pctxt, "extDtmGPRSStruct", &pvalue->extDtmGPRSStruct);
	}

	if (pvalue->m.highMultislotCapPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "highMultislotCap", pvalue->highMultislotCap);
	}

	if (pvalue->m.geranIuModeCapPresent) {
		asn1PrtToStrm_GSMRRGERANIuModeCap (pctxt, "geranIuModeCap", &pvalue->geranIuModeCap);
	}

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "geranFeaturePackage2", pvalue->geranFeaturePackage2);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "gmskMultislotPowerProfile", pvalue->gmskMultislotPowerProfile);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "multislotPowerProfile8PSK", pvalue->multislotPowerProfile8PSK);

	if (pvalue->m.tgsm400StructPresent) {
		asn1PrtToStrm_GSMRRGSM400Struct (pctxt, "tgsm400Struct", &pvalue->tgsm400Struct);
	}

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "zerobit", pvalue->zerobit);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "downlinkAdvancedRcvrPerf", pvalue->downlinkAdvancedRcvrPerf);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "dtmEnhancementsCap", pvalue->dtmEnhancementsCap);

	if (pvalue->m.dtmGPRSStruct2Present) {
		asn1PrtToStrm_GSMRRMobileStationClassmark3_dtmGPRSStruct2 (pctxt, "dtmGPRSStruct2", &pvalue->dtmGPRSStruct2);
	}

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "repeatedACCHCap", pvalue->repeatedACCHCap);

	if (pvalue->m.gsm710AssocRadioCapPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "gsm710AssocRadioCap", pvalue->gsm710AssocRadioCap);
	}

	if (pvalue->m.tgsm810AssocRadioCapPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "tgsm810AssocRadioCap", pvalue->tgsm810AssocRadioCap);
	}

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "cipheringModeSettingCap", pvalue->cipheringModeSettingCap);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "additionalPositioningCap", pvalue->additionalPositioningCap);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "e_UTRA_FDD_support", pvalue->e_UTRA_FDD_support);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "e_UTRA_TDD_support", pvalue->e_UTRA_TDD_support);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "e_UTRA_MeasAndReportSupport", pvalue->e_UTRA_MeasAndReportSupport);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "priorityBasedReselectionSupport", pvalue->priorityBasedReselectionSupport);

	if (pvalue->m._v9ExtPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamBoolean (pctxt, "uTRA_CSG_Cells_Reporting", pvalue->uTRA_CSG_Cells_Reporting);
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "vAMOS_Level", pvalue->vAMOS_Level);
	}

	if (pvalue->m._v10ExtPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "tighterCapability", pvalue->tighterCapability);
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamBoolean (pctxt, "selCiphOf_DL_SACCH", pvalue->selCiphOf_DL_SACCH);
	}

	if (pvalue->m.spareBitsPresent) {
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamBitStrBraceText (pctxt, "spareBits", pvalue->spareBits.numbits, pvalue->spareBits.data);
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRCipheringModeCommand (OSCTXT *pctxt, 
		const char* name, const GSMRRCipheringModeCommand* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "cipheringmodecmdmsgType", pvalue->cipheringmodecmdmsgType);

	asn1PrtToStrm_GSMRRCipherResponse (pctxt, "cipherresponse", &pvalue->cipherresponse);

	asn1PrtToStrm_GSMRRCipheringModeSetting (pctxt, "cipheringmodesetting", &pvalue->cipheringmodesetting);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRClassmarkChange (OSCTXT *pctxt, 
		const char* name, const GSMRRClassmarkChange* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "presence_bitmask", pvalue->presence_bitmask);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "classmarkchangemsgType", pvalue->classmarkchangemsgType);

	asn1PrtToStrm_GSMRRMobileStationClassmark2 (pctxt, "mobilestationclassmark2", &pvalue->mobilestationclassmark2);

	if(pvalue->presence_bitmask & GSM_CLASSMARK_CHANGE_ADDITIONAL_MOBILE_STATION_CLASSMARK_INFO_PRESENT)
	{
		asn1PrtToStrm_GSMRRMobileStationClassmark3 (pctxt, "additionalmobilestationclassmarkinfo", &pvalue->additionalmobilestationclassmarkinfo);
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRUtranClassmark (OSCTXT *pctxt, 
		const char* name, const GSMRRUtranClassmark* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "utranclassmarklength", 1, pvalue->utranclassmarklength);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "utranclassmarkvalue", pvalue->utranclassmarklength, pvalue->utranclassmarkvalue);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRUtranClassmarkChange (OSCTXT *pctxt, 
		const char* name, const GSMRRUtranClassmarkChange* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "utranclassmarkchangemsgType", pvalue->utranclassmarkchangemsgType);

	asn1PrtToStrm_GSMRRUtranClassmark (pctxt, "utranclassmark", &pvalue->utranclassmark);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRAssignmentComp (OSCTXT *pctxt, 
		const char* name, const GSMRRAssignmentComp* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "assignmentcompmsgType", pvalue->assignmentcompmsgType);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rrcause", pvalue->rrcause);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRRoutingAreaIdentification (OSCTXT *pctxt, 
		const char* name, const GSMRRRoutingAreaIdentification* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	asn1PrtToStrm_MCCMNCPair (pctxt, "mcc_mnc", &pvalue->mcc_mnc);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "lac", 2, pvalue->lac);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "rac", 1, pvalue->rac);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRServiceSupport (OSCTXT *pctxt, 
		const char* name, const GSMRRServiceSupport* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "mbmsbroadcast", pvalue->mbmsbroadcast);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRGPRSSuspensionRequest (OSCTXT *pctxt, 
		const char* name, const GSMRRGPRSSuspensionRequest* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "presence_bitmask", pvalue->presence_bitmask);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "gprssuspensionreqmsgType", pvalue->gprssuspensionreqmsgType);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "temporarylogicallinkidentity", 4, pvalue->temporarylogicallinkidentity);

	asn1PrtToStrm_GSMRRRoutingAreaIdentification (pctxt, "routingareaidentification", &pvalue->routingareaidentification);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "suspensioncause", pvalue->suspensioncause);
	if(pvalue->presence_bitmask & GSM_GPRS_SUSPENSION_REQUEST_SERVICE_SUPPORT)
	{
		asn1PrtToStrm_GSMRRServiceSupport (pctxt, "servicesupport", &pvalue->servicesupport);
	}
	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRChannelRelease (OSCTXT *pctxt, 
		const char* name, const GSMRRChannelRelease* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "channelreleasemsgType", pvalue->channelreleasemsgType);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "rrcause", pvalue->rrcause);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_MAIO (OSCTXT *pctxt, const char* name, const MAIO* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "maiohighpart", pvalue->maiohighpart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "maiolowpart", pvalue->maiolowpart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_MAIO2 (OSCTXT *pctxt, const char* name, const MAIO2* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "maiohighpart", pvalue->maiohighpart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "maiolowpart", pvalue->maiolowpart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "hsn", pvalue->hsn);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_ARFCN (OSCTXT *pctxt, const char* name, const ARFCN* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "arfcnhighpart", pvalue->arfcnhighpart);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "arfcnlowpart", pvalue->arfcnlowpart);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_HoppingChannel (OSCTXT *pctxt, 
		const char* name, const HoppingChannel* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	switch (pvalue->t)
	{
		/* maio */
		case 1:
			{
				asn1PrtToStrm_MAIO (pctxt, "maio", &pvalue->u.maio);
				break;
			}
			/* arfcn */
		case 2:
			{
				asn1PrtToStrm_ARFCN (pctxt, "arfcn", &pvalue->u.arfcn);
				break;
			}
		default:;
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_HoppingChannel2 (OSCTXT *pctxt, 
		const char* name, const HoppingChannel2* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	switch (pvalue->t)
	{
		/* maio */
		case 1:
			{
				asn1PrtToStrm_MAIO2 (pctxt, "maio", &pvalue->u.maio);
				break;
			}
			/* arfcn */
		case 2:
			{
				asn1PrtToStrm_ARFCN (pctxt, "arfcn", &pvalue->u.arfcn);
				break;
			}
		default:;
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRChannelDescription2 (OSCTXT *pctxt, 
		const char* name, const GSMRRChannelDescription2* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "channeltypeandtdmaoffset", pvalue->channeltypeandtdmaoffset);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "tn", pvalue->tn);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "tsc", pvalue->tsc);

   asn1PrtToStrm_HoppingChannel2 (pctxt, "hoppingchannel", &pvalue->hoppingchannel);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRChannelDescription (OSCTXT *pctxt, 
		const char* name, const GSMRRChannelDescription* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "channeltypeandtdmaoffset", pvalue->channeltypeandtdmaoffset);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "tn", pvalue->tn);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "tsc", pvalue->tsc);

	asn1PrtToStrm_HoppingChannel2 (pctxt, "hoppingchannel", &pvalue->hoppingchannel);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRFrequencyList (OSCTXT *pctxt, 
		const char* name, const GSMRRFrequencyList* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "length", pvalue->length);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "value", pvalue->length, pvalue->value);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMultislotAllocation (OSCTXT *pctxt, 
		const char* name, const GSMRRMultislotAllocation* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "length", pvalue->length);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "value", pvalue->length, pvalue->value);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRMobileAllocation (OSCTXT *pctxt, 
		const char* name, const GSMRRMobileAllocation* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "length", pvalue->length);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "value", pvalue->length, pvalue->value);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRStartingTime (OSCTXT *pctxt, 
		const char* name, const GSMRRStartingTime* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "value", 2, pvalue->value);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRFrequencyChannelSequence (OSCTXT *pctxt, 
		const char* name, const GSMRRFrequencyChannelSequence* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "value", 9, pvalue->value);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRPowerCommand (OSCTXT *pctxt, 
		const char* name, const GSMRRPowerCommand* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "epcmode", pvalue->epcmode);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "fpcepc", pvalue->fpcepc);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "powerlevel", pvalue->powerlevel);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRAssignmentCommand (OSCTXT *pctxt, 
		const char* name, const GSMRRAssignmentCommand* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "presence_bitmask", pvalue->presence_bitmask);
	
	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "assignmentcommandmsgType", pvalue->assignmentcommandmsgType);

	asn1PrtToStrm_GSMRRChannelDescription2 (pctxt, "descriptionofthefirstchannelaftertime", &pvalue->descriptionofthefirstchannelaftertime);

	asn1PrtToStrm_GSMRRPowerCommand (pctxt, "powercommand", &pvalue->powercommand);

	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_FREQUENCY_LIST_AFTER_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRFrequencyList (pctxt, "freqlistaftertime", &pvalue->freqlistaftertime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_CELL_CHANNEL_DESCRIPTION_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamHexStr (pctxt, "cellchanneldescription", 17, pvalue->cellchanneldescription);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_DESCRIPTION_OF_MULTISLOT_ALLOCATION_PRESENT)
	{
		asn1PrtToStrm_GSMRRMultislotAllocation (pctxt, "descriptionofthemultislotconfig", &pvalue->descriptionofthemultislotconfig);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_FIRST_CHANNEL_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeoffirstchannel", pvalue->modeoffirstchannel);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_CHANNEL_SET_2_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeofchannelset2", pvalue->modeofchannelset2);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_CHANNEL_SET_3_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeofchannelset3", pvalue->modeofchannelset3);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_CHANNEL_SET_4_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeofchannelset4", pvalue->modeofchannelset4);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_CHANNEL_SET_5_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeofchannelset5", pvalue->modeofchannelset5);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_CHANNEL_SET_6_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeofchannelset6", pvalue->modeofchannelset6);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_CHANNEL_SET_7_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeofchannelset7", pvalue->modeofchannelset7);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_CHANNEL_SET_8_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeofchannelset8", pvalue->modeofchannelset8);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_DESCRIPTION_OF_SECOND_CHANNEL_AFTER_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRChannelDescription (pctxt, "descriptionofthesecondchannelaftertime", &pvalue->descriptionofthesecondchannelaftertime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MODE_OF_SECOND_CHANNEL_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamUnsigned (pctxt, "modeofsecondchannel", pvalue->modeofsecondchannel);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MOBILE_ALLOCATION_AFTER_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRMobileAllocation (pctxt, "mobileallocationaftertime", &pvalue->mobileallocationaftertime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_STARTING_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRStartingTime (pctxt, "startingtime", &pvalue->startingtime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_FREQUENCY_LIST_BEFORE_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRFrequencyList (pctxt, "freqlistbeforetime", &pvalue->freqlistbeforetime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_DESCRIPTION_OF_FIRST_CHANNEL_BEFORE_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRChannelDescription2 (pctxt, "descriptionofthefirstchannelbeforetime", &pvalue->descriptionofthefirstchannelbeforetime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_DESCRIPTION_OF_SECOND_CHANNEL_BEFORE_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRChannelDescription (pctxt, "descriptionofthesecondchannelbeforetime", &pvalue->descriptionofthesecondchannelbeforetime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_FREQUENCY_CHANNEL_SEQUENCE_BEFORE_TIME_PRESENT)
	{
		rtPrintToStreamIndent (pctxt);
		rtPrintToStreamHexStr (pctxt, "freqchannelsequencebeforetime", 9, pvalue->freqchannelsequencebeforetime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_MOBILE_ALLOCATION_BEFORE_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRMobileAllocation (pctxt, "mobileallocationbeforetime", &pvalue->mobileallocationbeforetime);
	}


	if (pvalue->presence_bitmask & GSM_ASSIGNMENT_COMMAND_CIPHER_MODE_SETTING_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRCipheringModeSetting (pctxt, "cipheringmodesetting", &pvalue->cipheringmodesetting);
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRDedicatedModeOrTbf (OSCTXT *pctxt, 
		const char* name, const GSMRRDedicatedModeOrTbf* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "spare", pvalue->spare);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "tma", pvalue->tma);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "downlink", pvalue->downlink);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamBoolean (pctxt, "tbfordedicated", pvalue->tbfordedicated);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRChannelDescriptionChoice (OSCTXT *pctxt, 
		const char* name, const GSMRRChannelDescriptionChoice* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	switch (pvalue->t)
	{
		/* channeldescription */
		case 1:
			{
				asn1PrtToStrm_GSMRRChannelDescription (pctxt, "channeldescription", &pvalue->u.channeldescription);
				break;
			}
			/* packetchanneldescription */
		case 2:
			{
				rtPrintToStreamIndent (pctxt);
				rtPrintToStreamHexStr (pctxt, "packetchanneldescription", 3, pvalue->u.packetchanneldescription);
				break;
			}
		default:;
	}

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_GSMRRRequestReference (OSCTXT *pctxt, 
		const char* name, const GSMRRRequestReference* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "randomaccessinfo", pvalue->randomaccessinfo);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "t1", pvalue->t1);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "t3high", pvalue->t3high);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "t3low", pvalue->t3low);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "t2", pvalue->t2);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

int asn1PrtToStrm_ImmediateAssign (OSCTXT *pctxt, 
		const char* name, const ImmediateAssign* pvalue)
{
	rtPrintToStreamOpenBrace (pctxt, name);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "skipInd", pvalue->skipInd);

	asn1PrtToStrm_GSMRRProtoDiscr (pctxt, "protoDiscr", &pvalue->protoDiscr);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamUnsigned (pctxt, "immediateassignmsgType", pvalue->immediateassignmsgType);

	asn1PrtToStrm_GSMRRPageMode (pctxt, "pagemode", &pvalue->pagemode);

	asn1PrtToStrm_GSMRRDedicatedModeOrTbf (pctxt, "dedicatedmodeortbf", &pvalue->dedicatedmodeortbf);

	asn1PrtToStrm_GSMRRChannelDescriptionChoice (pctxt, "channeldescriptionchoice", &pvalue->channeldescriptionchoice);

	asn1PrtToStrm_GSMRRRequestReference (pctxt, "requestreference", &pvalue->requestreference);

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "timingadvance", 1, pvalue->timingadvance);

	asn1PrtToStrm_GSMRRMobileAllocation (pctxt, "mobileallocation", &pvalue->mobileallocation);

	if (pvalue->presence_bitmask & GSM_IMMEDIATE_ASSIGNMENT_STARTING_TIME_PRESENT)
	{
		asn1PrtToStrm_GSMRRStartingTime (pctxt, "startingtime", &pvalue->startingtime);
	}

	rtPrintToStreamIndent (pctxt);
	rtPrintToStreamHexStr (pctxt, "iarestoctets", 11, pvalue->iarestoctets);

	rtPrintToStreamCloseBrace (pctxt);
	return 0;
}

